### PR TITLE
Abstract Profile - Contrast enhancement -- Selective Editing Cam16 and JzCzHz - improvments

### LINKED ISSUE #7147: Preview anomaly when toggling a custom DCP tone curve on and off with Selective Editing tools activated
Toggling the DCP Tone curve (Color Management > Input Profile) on and off when a Selective Editing tool has been added to a spot, progressively increases the brightness and contrast of the preview. The exported jpeg is normal.
Steps to reproduce:
-Open an image with a Neutral profile
-Load a DCP profile into: Color Management > Input Profile > Custom
-Activate Selective Editing, add any type of spot and activate for example the 'Color appearance' tool. 
-Return to the Input Profile menu and toggle the DCP tone curve on and off.

The image will become progressively brighter and the contrast will increase. Switching to the 'Camera standard' profile and back again will reset the preview. 
The anomaly occurs also in the 5.10 release.

### LINKED ISSUE #7241: Abstract Profile - resetting Gamma & Slope sliders changes the default values
When the Abstract Profile tool is opened for the first time, the default/initial values for Slope and Gamma are:
Gamma = 2.4
Slope = 12.92
which correspond to an sRGB TRC

If you simply click on the reset arrows for the corresponding sliders without changing anything else, the values become:
Gamma = 2.222
Slope = 4.5
which correspond to a BT709 TRC

The Ctrl + Click function works correctly i.e. the sliders revert to the initial sRGB values.

### LINKED ISSUE #7283: Typo in paramsedited.cc?
paramsedited.cc, line 1368, reads:

locallab.spots.at(j).clcurve = locallab.spots.at(j).clcurve && pSpot.cccurve == otherSpot.clcurve;

I suppose that this is a typo; "cccurve" should really be "clcurve".

### PR DESCRIPTION
**Pull request by Desmis**
**Contrast Enhancement**

**Purpose**
This module complements the Tonal Response Curve (TRC) in the Abstract Profile (Color tab) and allows the user to carry out tonal contrast adjustments. 

**Is tonal contrast a difficult concept?**
Traditionally, any graphics software can be used to retouch contrast. Empirically, this can be translated as modifying the difference in luminosity between the light and dark parts of an image.
There are various algorithms some of which may or may not take into account the following:
* the dynamic range ;
* the whole or just part of the image (using masks or spots).

Contrast acts on the luminance channel, whether in RGB (or its HSV derivatives, etc.) or Lab mode. and can be modified using various tools of varying complexity, linear or non-linear. For example by using functions such as log encoding, Laplacians, wavelets, guided filters, tone curves, sigmoid curves etc.

**The special case of wavelets:**
Wavelets are a little-known mathematical tool that is not widely used as such in image-processing software but can be the basis for other tools. Rawtherapee is, to my knowledge, the only one to have a coherent and grouped set of tools using wavelets. Unfortunately, the whole package may seem complex and off-putting.
Extensive information about the principles of wavelets and the various tools can be found in RawPedia so I won’t repeat the information here. To summarise:
* The image details are decomposed into groups of pixels, sorted according to their size (from 2x2 up to 1024x1024 pixels if the system allows it), and distributed across the wavelet decomposition levels (one size per level). The details in each level are then assigned values which correspond to the amount of contrast in each detail (i.e. in each group of pixels) and are only generated if there is a variation between neighbouring pixels (in R,G,B or L,a,b mode).
They are then sorted according to whether the values are positive or negative for the horizontal, vertical and diagonal directions. The decomposition method used allows the user to choose the number of Daubechies vanishing moments, which affect the quality and finesse of the decomposition.
* The undecomposed part, which no longer has any variations in the values of neighbouring pixels (beyond the maximum value chosen by the user), constitutes the residual image and can be processed using the same tools as a traditional image.

The following tools are available in Rawtherapee:
* Contrast by level -this tool can be found in various forms in:
-The Selective Editing tab
	-Local Contrast & Wavelets > Pyramid 2 > Contrast by level
	-Contrast by Detail Levels
-The Advanced tab (Advanced > Wavelet Levels > Contrast)
-The Detail tab (Contrast by Detail Levels)
It allows you to modify the contrast values of each group of pixels on a per-level basis in each of the 3 directions and for both the positive and negative values. However visible artefacts can appear fairly quickly (noise, blurring, distortion, sculpting effects, etc.) even when taking measures such as progressively reducing the strength of the action for high levels of detail. Additional tools can be used to reduce - but not eliminate - these artefacts (“Attenuation response”, “Selective luminance range”, etc.).
* Edge sharpness (Advanced > Wavelet Levels and in Selective Editing > Local Contrast & Wavelets) is used both to reinforce edges, similar to the methods used in sharpening tools, and to soften backgrounds (similar to tools such as darktable's “diffuse or sharpen”). Refer to RawPedia for details.
* Other tools such as Clarity and “Blur levels” (both in Advanced > Wavelet Levels and in Selective Editing > Local Contrast & Wavelets) etc., allow effects that virtually only wavelets can provide.

* Local contrast: faced with the problems inherent in contrast by level, I decided a few years ago (around 2013) to take a different approach to wavelet contrast. For each level and direction, I evaluate the shape of the signal (average, standard deviation, maximum for positive and negative values). The whole thing is modelled in such a way that the user is faced with a single curve for modifying the contrast, whatever the level. This curve uses the characteristics of the signal to position the mean value at the centre of the graph, take into account the variations on either side of the mean and position the maximum at the far right of the graph. It weakens the action for large values close to the maximum. The system's behaviour avoids the majority of artefact problems, and acts in a fairly similar way across the different levels of detail. I've called this approach 'Local contrast', but this doesn't really convey what it does. This tool is present in Rawtherapee in the Wavelet Levels > Final Touchup module, in several other modules such as Wavelet Levels > “Edge sharpness” and in Selective Editing > Local Contrast & Wavelets. It can also be found in ART.
Curiously, until now this tool has not been available separately in the tools available in full-image mode.

**Variable contrast**
However, despite this improvement, the system cannot, at the same time, and with the same quality as seen from the user's point of view, process the levels containing small details (from 0 to around 6) and those containing large details (from around 5 to 9) in the same way.This is why I propose to combine the action of the two systems (“Contrast by levels” and Local Contrast) into a single system.

In this new system, which I have called Contrast Enhancement, per-level contrast is contained in a series of contrast-profile presets, which provide the information needed to adjust the amount of local contrast in each of the levels.

**Each preset contains a selection of decomposition levels.**
In each of these levels, the contrast values are divided up into ten discrete samples ranging from the lowest to the highest values. The low-contrast-value samples and the high-contrast-value samples (which are often synonymous with artifacts) are then attenuated. The nature and intensity of this attenuation depends on the preset and whether or not "Highlight attenuation" has been activated.
Each preset also contains information used to weight the overall level data to either attenuate the data for the first level (to reduce noise) or to progressively attenuate it for the higher levels. 
-the resulting data from each decomposition level is then sent to the curve, which should be preferably “bell shaped” to concentrate the action on the useful levels and attenuate the action at the extremities. 

**The Contrast Enhancement module has the following characteristics:** 
* it works on the whole image,
* it differentiates the action according to the existing contrast values of the detail levels,
* it avoids artefacts by reducing the action on the upper and lower contrast values in each pixel group. 
* it introduces the notion of “Variable contrast”, which allows the user to control the areas (small, large, dark or light) where they want to modify the sharpness, structure and differentiation of the highlights, with the minimum number of commands and in the most intuitive way possible, without having to master the mathematical concepts and language of wavelets.
What does this tool consist of?
It consists of three parts: 
A “Contrast profile” slider that lets you select several contrast-profile presets as described above.These presets offer a selection of possible degrees of contrast.

**These presets are classified :** 
* from the least aggressive, corresponding essentially to the lower settings of the Contrast by Detail Levels tool, with the number of detail levels limited to 6, and an attenuated first level to take account of noise.
* to the most aggressive, going so far as to use the maximum possibilities of the system (memory, size of the Preview).
At the same time, these presets progressively weaken the action of the “Variable contrast” curve as you move the “Contrast profile” slider to the right.

The **“Variable contrast” curve** , which is the heart of the system, is used to modify the existing contrast values, based on the size of the pixel groups, their contrast and possible artefacts. The information contained in the presets determines the behaviour of the curve. However, whatever the preset and the level of detail: a) the mid-point of the x-axis corresponds to the most important contrast value for the action; b) the maximum point, to the right of x-axis, corresponds to the maximum contrast found. It is recommended to reduce the variable contrast beyond the mean value.

A **Refinement expander**, which can be used to modify: a) the distribution of the action between the low, medium and high values of the “Variable contrast” curve, in particular by widening or narrowing the effects of the width of the curve; b) adjust the residual image after decomposition to compensate for excessive effects linked to the action of the curve and the presets.

**Moving the Color Management module**
The Color Management module (which includes the Abstract Profile) has been moved up in the Color tab and positioned just after the White Balance module. This is to improve it’s visibility and to take into account the fact that it is likely to be used more frequently.

**Selective Editing Cam16**
In Source Data Adjustments > Highlight attenuation & RGB channels, The RGB Channel Slope module has been improved to better use the tone mapping algorithm.

### CODE REVIEW

**Comment by Desmis** [comment]
Some additions:
* I harmonized certain parts of Selective editing (wavelet) so that they have approximately the same capabilities as the new module in Abstract Profile - Contrast Enhancements : for example "Local Contrast" (discrete samples ranging).
* I have also fixed some bad behavior when using zoom.

As it is said in the text, the number of vanishing moments has been changed and increased to a maximum of 20. Affects edge detection as well as the general quality of the first levels. However the quality is not strictly related to this coefficient and can vary depending on image and use.

You can choose : D2 low (Harr), D4 - standard (default), D6- standard plus, D10 - medium, D14 - high, D20 - high plus.
This choice can be made in:
*  "Wavelet levels" for the tools in this panel, and for "Abstract Profile - Contrast enhancement"
*  Selective editings - settings, for all tools Selective editings

https://en.wikipedia.org/wiki/Daubechies_wavelet

jacques

**Comment by Desmis** [comment]
I didn't mention the start of my changes which concern the Selective Editing > Color Appearance > Source Data Adjustments module

The RGB Channels slope choice allows you to take full advantage of Freeman's "Tone mapping" algorithm.
* you can act on each of the R, G, B channels as "RGB Curve" does, but in Dynamic Range mode. You also have the “Luminosity” mode at your disposal, with the same possible undesirable effects (more pronounced than RGB curves, but it works in easy cases, and this mode was in high demand a few years ago).
* you can scale both "Yb Scene" and "Yb viewing"
* a “highlight attenuation only” mode allows you to use only the part located for lights and highlights (like Gamma based mode). In this case, you have the "attenuation threshold" slider which allows you to vary the threshold (normally Yb scene) from which you act on the lights.

**Comment by Desmis** [comment]
@Lawrence37 
I will be away from home until the beginning of August. I'm going to the mountains in Mercantour (behind Nice) a few tens of kilometers away.

Of course I will continue to follow the project and the current PRs, but I am not sure about the Internet connection

Jacques

**Comment by Lawrence37** [comment]
@Desmis Enjoy your trip :)

**Comment by Desmis** [comment]
I have just added in "Source Data Adjustments", an additional method for processing highlights and contrast. I copied the "**Sigmoid tone mapper**" method from Darktable. Thanks to Alberto for the work that makes things easier with his sigmoid.ctl.

I changed some basic settings and automated "Black point" and "White point"

Jacques

**Comment by Desmis** [comment]
@Lawrence37 
@Wayne_Sutton50 sent me a message while testing this branch.
"I think there is a malfunction when using a DCP as an input profile with the associated tone curve. If we deactivate the curve and then reapply it several times, the effect is cumulative to something like this:"
image

This problem seems specific to a link with Selective Editing and has been since its first version. I tried versions 5.9 and 5.10 which achieve the same result.
The problem does not appear for JPG/TIF output.

I immediately thought of a pipeline and “events” problem. I looked at the level of "events" for all DCP events. They are all at "ALLNORAW" except those in question here with "RGBCURVE | M_AUTOEXP" - the same as for Selective Editing.
I made a change in refreshmap.cc
    ALLNORAW, //RGBCURVE | M_AUTOEXP, // EvDCPToneCurve, 21 july 2024
    ALLNORAW,         // EvDCPIlluminant,
and
    ALLNORAW, //RGBCURVE | M_AUTOEXP, // EvDCPApplyLookTable,  21 july 2024
    ALLNORAW, //RGBCURVE | M_AUTOEXP, // EvDCPApplyBaselineExposureOffset, 21 july 2024
    ALLNORAW,         // EvDCPApplyHueSatMap

The problem seems to be fixed.
Should I open an **issue** to keep track and/or open a specific PR, where processing in that PR is enough.
Your opinion ?

I just saw that Wayne opened an issue
#7147

Thank you

**Comment by Desmis** [comment]
Short summary of the changes:

Main:
* Abstract profiles : contrast enhancement with "Variable contrast wavelets"
* Checkbox "black and white" visible in all cases
* Tone curve 1 - in standard mode Color appearance and Lighting

Selective Editing:
Colorappearance (Cam16 and JzCzHz)
In Source Data Adjustments
* improve RGB channels (RGB Channels Slope) - uses all the features of Freeman tone-mapper
* Sigmoid added (replace old version) in Cam16 and JzCzHz and trial version for Slope based Q and Sigmoid Q
* Checkbox "black and white" visible in all cases 

In Cam16 Images adjustments
* Curves visibles in Basic mode, juste at the beggining of the GUI

Various bug (DCP) and GUI bad behvior.

**Comment by Lawrence37** [comment]
I finally had some time to try this out! Wavelets are great for adjusting local contrast. I use it a lot in the wavelet levels tool and selective editing and really like it. This new feature is familiar and works as well as its counterparts in wavelet levels and selective editing, but is more accessible. I'm curious why it is a part of abstract profile? It feels like it could be a tool on its own in the details tab. I guess it has something to do with it's location in the pipeline?

**Comment by Desmis** [comment]
@Lawrence37 
Thanks for this review.

We can discuss endlessly where to put an algorithm?

In Selective Editing this functionality is provided (with differences however in the selection of levels, but it is the same algorithm) and can be placed anywhere, with others tools and used as many times as you want in global / full image / normal / excluding mode. Here we are at the beginning of the pipe-line.

Here, in the case of "Abstract profile", in my opinion and with discussions with Wayne @waynesutton50  there emerged a need to add contrast. Sigmoid or Log encoding type solutions are complex to implement at the GUI level, and act on the overall contrast.  This "Local contrast" tool that I imagined in 2012/2013 is simple and intuitive, even if the theory is complex.

From the discussions I had with Andy Astbury  @AndyAstbury appears that Abstract profile (gamma - slope...) and wavelets which provides local contrast was a good solution.

So I tried to simplify for the user, at best local contrast wavelets (which I prefer to call variable).

It was also necessary to be able to easily adjust the global contrast and the values ​​(display) of white point and black point, hence a displacement of the curves both in Ciecam and in Cam16

Its position which complements "gamma-slope-midtones" allows to adjust a very large majority of cases without having to use the "Exposure" module and Auto-matched tone curve. Here we are at the end of the pipe-line. 

Use with Ciecam and Cam16 (simpler) allows the integration of physiological aspects (eye/brain couple)

But of course I am open to any discussion.

Thank you

Jacques

**Comment by waynesutton50** [comment]
> So I tried to simplify for the user

For new or occasional users (I try and help a small group of friends and family) it does help if the different elements of a particular part of the workflow can be grouped together in the same tab. This is certainly the case when using Auto Levels or the Auto-matched tone curve as the starting point for adjusting exposure and tonal contrast.  It's also the case if we use Selective Editing > Color Appearance (CAM16 etc.). The TRC in the Abstract Profile tends to be the odd man out in this respect because you have to change tabs to fine tune the contrast. From a purely ergonomic point of view, it probably doesn't change much, but it does mean that the tool is not as self-contained as the tools mentioned above or similar tools such as Filmic or Sigmoid.

**Comment by Desmis** [comment]
@Lawrence37 
Hello Lawrence

I tested the PR of the 'apseimprov' branch again and found an important bug.

This bug concerns the procedure I've set up to switch to 'Global' mode and avoid the remanent actions of mask settings (Full image, etc.).
This is what you'll find in the 'voids' of the type below :
 _//new function Global
void Locallabcie::updateguicie(int spottype)_

With at the end to ‘clean’
 _if(spottype == 3) {
                showmaskcieMethodChanged();
  }_

These functions work correctly except in 2 cases: 'Color appearance' and 'Log encoding'.
In these 2 cases, if 'Automatic' is checked in 'Scene conditions', the system loops without stopping.

I only found (with difficulty) that it was because of this - the 'auto' button which calculates the Black-Ev and White-Ev values and therefore the DR, was ‘disabled’.

Previously I checked the GUI code - complex which passes mask parameters between Locallab, Locallabtools, Toolpanelcoord, Iplocallab, improccoordinator, etc. - and found no anomalies. 

The problem - which I hadn't noticed because I'd deactivated 'auto' - is probably due to the interaction of 'events' in the pipeline. The calculation of Blackev and WhiteEv is done just before in the pipeline with the function 'ipf.getAutoLogloc'.

I tried (it's not my strong point) to remedy this, either by changing the 'updateguicie' and 'updateguilog' functions by deactivating the masks and/or the 'auto' function, or by trying to change the 'events' in improccoordinator.
After many, many attempts, I haven't come up with a satisfactory result.

There may be a solution, but it's not essential. Of course, if you can come up with a simple solution without spending a lot of time on it, it would be most welcome.

To simplify things, I suggest deleting the following lines in these 2 functions only 'Color appearance' and 'Log encoding' (locallabtool2.cc)
_if(spottype == 3) {
                showmaskcieMethodChanged();
 }_
and the same with _showmaskLMethodChanged();_

So as not to disrupt your review work, I suggest that either you do it directly in the PR - like other anomalies you may find, or that I do it afterwards.

Thank you

Jacques

**Comment by Desmis** [comment]
@Lawrence37  @waynesutton50

Finally I think I found the solution (the big bug described above) to this problem of taking into account the  "idiotics" masks (and modifications) in Full-image and in Global.

I was looking via the GUI to solve this problem which seems easy, but which is not. I had started from the solution used to cancel the other masks when using another one... but it turns out that it works badly or very badly, to apply to the masks and modifications of the Current Spot. 

The system was looping by repeating the entire Improcoordinator.cc process....without a solution (White balance and other processes were continuously re-executed). I found workarounds but they were mediocre.

Finally I decided to do it differently and much simpler. The GUI is now only used to hide the expanders, sliders, etc.
Everything is done inside iplocallab.cc by activating or not the masks, modifications, PreviewdeltaE, depending on whether we use Global or something else. For this I use "lp.fullim == 3 " or not... (3 = Global, 2 = fullimage...)

In total about twenty lines of code where now appears in the "lp.fullim" decisions,  and only concern masks and modifications. Nothing else is changed.

Now when we go from Full-image to Global, even if the masks or the modifications, or the PreviewdE is active. The whole is canceled, but we keep if we return to Full-image to the previous settings (we keep the mask settings, etc.). Only the checkbox 'Enable mask' must be reactivated.

I implemented this solution in the PR on GHS, because this random behavior was annoying me. I hope I haven't forgotten anything...

I have prepared a change for this PR - branch 'apse improv', but I am waiting for your 'green light' to push the commit, as it may disrupt the review.

What should I do? Wait, push for change - which is very simple? or ??

Thank you

Jacques

**Comment by Lawrence37** [comment]
Is it really necessary to fix the problem in two separate pull requests?

**Comment by Lawrence37** [comment]
I did some more testing and found some bugs and usability issues.

1. Contrast profiles 3 and 4 produce similar or identical results. Is this expected?
2. The variable contrast curve doesn't expand fully. It's the same problem as #3525.
3. When using the batch editor, the variable contrast curve doesn't revert properly when going back in history. Steps to reproduce:
    1. Apply different variable contrast curves to two images.
    2. Select both images in the file browser.
    3. Use the Batch Edit tab to change the variable contrast curve.
    4. Undo the change using the history panel.
    5. Check the variable contrast curves of the two images. They are identical, but they should be different because they were set different in step 1.
4. The abstract profile tool-tip is very annoying. For example, the tool-tip keeps popping up when you try to adjust the variable contrast curve. It makes it hard to see the curve. To make the tool-tip less intrusive, it should only appear while hovering over the Abstract Profile title.
5. The Abstract Profile tool collapses every time after opening an image. The expand/collapse state should be maintained.

I don't know if anyone else feels this way, but I find the tool-tips to be hard to understand. I will explain in a separate comment.

**Comment by Desmis** [comment]
@Lawrence37 
"Is it really necessary to fix the problem in two separate pull requests?"

**Yes, Yes, Ye**s unless we admit that on the first try once in Dev, users will say it won't work, for example putting WB auto at the same time results in unusability. 

Of course you can say that I just had to try it "before". This is a problem that I have been trying to solve for several months. I thought it was solved, but when I tried the GHS PR, I found the same problem... It's the same code.
Having 2 PRs open at the same time that modify and use the same parts of code is difficult to solve. This PR is old, it reminds me of the "very heated" debate that took place in 2020/2021 when I presented this concept of "Abstract profile" ... in short it was "What is this bullshit ?". At the time I was called all sorts of names, there was talk of an inquisition... I was ready to leave Rawtherapee for good... (I have been ill for 5 to 10 years and all this does not help)

 The action of the contrast levels depends on each image and the result of the decomposition by the Debauchies method... Yes, in many cases, there is a gap, sometimes small.

The tooltips problem is complex, some that I will not name for decency said that we should not put any.
Their content is complex, what should we put that is simple and understandable, the majority of these tooltips (not all) have been seen by Wayne and me, but nothing is perfect.

But probably to get back to this PR, the simplest thing is to delete it, and I'm not kidding... This will be followed by my final departure from RT. The idiot, the old bastard...will no longer be there.

Jacques

**Comment by waynesutton50** [comment]
> the majority of these tooltips (not all) have been seen by Wayne and me

I'm sorry I haven't had time to review the GHS tooltips or the latest changes to the Abstract Profile tooltips.

**Comment by Desmis** [comment]
@waynesutton50 

Thank you

**Comment by Lawrence37** [comment]
@Desmis

I wish I could understand French because then it would be easier for us to collaborate. I try my best, but I still have a hard time understanding what you write and communicating my thoughts to you.

You sound frustrated. I'm concerned because it's so sudden and I'm not sure what happened recently to make you feel so strongly. If it is something I said, I'm sorry for not being more careful in wording my replies. I would never degrade you personally or your work. Whatever feedback I write here is always intended to help you improve your work.

In an earlier comment, you referred to the "idiotic" masks. If I'm correct in knowing what you were referencing, then let me tell you that you shouldn't let one person's rant consume your emotions. I saw that thread. I was tempted to participate, but I refused to give any attention that the person obviously did not deserve. Feedback should always be constructive. When someone mixes in insults, I treat it as purely a rant. Any requests or demands they include, I automatically consider them to be unserious and rhetorical. There is no need to entertain their opinions and you have every reason to completely ignore them.

**Comment by Desmis** [comment]
@Lawrence37 
Hello Lawrence
I think that the language problem, but also our deep differences in terms of our character, our work habits, our origins, our ages, my state of health are factors that lead to these misunderstandings.

I attach great importance to what is said - don't forget that a large part of my activity has concerned human factors, change management, sociology, ergonomy, strategy - and it disturbs me enormously. The history of masks, but also the opinions that users can express (sometimes without having tried it...) on innovative subjects or those that seem complex (Abstract profile, Wavelets, Ciecam, etc.) are very often derogatory, condescending... I even received personal messages telling me the bad things people thought of these "things". Fortunately there are also very positive personal messages.

As for our relationship, and I put this down to the factors I just mentioned above. I feel like we're working "alongside" and "not together". For example, the PR you opened (I don't dispute the possible differences of technical opinions), on "FFTW Blur radius fix" had been preceded by a branch  open with other changes concerning this subject. I said it (maybe wrongly), maybe you misunderstood it, it s write in the "issue". Still, seeing a new branch appear that doesn't take into account what I had done is at the very least very frustrating.

Another point - these are just anecdotes - concerns what I say about the dysfunction between Global and Fullimage. You can answer me, why do this in 2 separate PRs... Simply because in this "Abstract profile" branch if the user uses the new functions (Sigmoid, etc.), the system will crash when for example AutoWB Itcwb is active. I don't dare to talk about "merging" these defects, the first day there will be a significant number of complaints.

Now a point concerning working together. If you find anomalies, rather than reporting them to me and waiting for my change which with the deadlines, the time difference leads to delays, discussions, I propose that you make the modifications directly. After of course telling me that there were anomalies and my agreement in principle. You are much better than me in IT, in quality of code, and I see there - on the contrary - only a good principle of collaboration.

I will open a second and third page on the changes made or to be made.

Jacques

**Comment by Desmis** [comment]
@Lawrence37  @waynesutton50 

For the various "technical" points that you mentioned or that I mentioned.

I just pushed 2 to 3 commits to:
* solve the "Gloabal  / Fullimage" problem - I hope I haven't forgotten anything
* make the "Abstract profile" Expander stay Open (very simple). I received personal messages on this subject, asking me to do the opposite and even to delete this bullshit.

For the GUI behavior with a curve and sliders, it's an old bug not specific to here... I don't have a solution, it's totally out of my skills - which are algorithms first. Maybe switching to Gtk4 will solve the thing.

For the behavior, in Batch mode, I'm just - like a monkey - copying what's elsewhere to manage batch mode... I'm unable to provide an assessment and a fix. Maybe it's due to the Expander above? 

For the tooltips, beyond the content, which is not easy, especially in different languages ​​- when Wayne, whom I thank infinitely, does not have time to translate and especially to exchange with me for the understanding of the wording, I write it with the translator in "franglais", which is not great, but better than nothing.
Could we also put for the "main" tooltips the same option in Preferences as for Selective Editing (show or hide them)?

I'm going to make a more substantial text - I could do it immediately in French, but the translator is needed - on wavelets here in Contrast enhancement - on how it works, the subtleties of the settings, in particular the one you're talking about, but also the changes I made to SE Wavelets (small) in this PR, but also on Wavelets in RT and elsewhere.
I'll do that during the day.

Thanks for reading.

Jacques

**Comment by Desmis** [comment]
@Lawrence37 @waynesutton50 

Here is a text that, in the absence of Rawpedia, at least allows you to understand the wavelets and the new features brought by this PR. I used DeepL ...

[Wavalet_novels_RT2024.zip](https://github.com/user-attachments/files/18150962/Wavalet_novels_RT2024.zip)

I hope that's understandable
Jacquesd

**Comment by Lawrence37** [comment]
I'm sorry to hear about the negative message you have received. I will never understand why some people think it's ok to complain about things they get for free, made by people who do it without expecting anything in return. If you get condescending private messages telling you what you must or must not do, I suggest you tell them to post their "suggestion" publicly here on GitHub. There is no reason for people to pressure you privately to do what they want you to do. Make them post their demand here and force them to justify it to the broader RawTherapee community.

Regarding the FFTW blur, there are 3 reasons why I decided to create a separate branch. First is that I already started working on the fix. I shared what I had at the time to solicit feedback while I cleaned up the code and made additional changes. Second, the backward compatibility of pp3s is very important for many users. I had already done the math and verified the results empirically, so I felt it was more appropriate for me to implement the backward compatibility myself rather than explain and ask you to do it. Finally (this concerns why I didn't add the backward compatibility to your branch), I stick to certain protocols when developing. Part of the reason is personal, and the other part is habit (from my professional background, for example). The protocols tell me to keep unrelated changes in separate branches and pull requests. There are many benefits of this, including organization and efficiency. Sorry for making you feel like I ignored you work. It was just simpler for me to create a separate branch. Your branch of course can still be used for the other fixes.

If I had time, I would do so many more things. I would fix the bugs I found in this and in other pull requests. I would implement the popular feature requests. I would also be submitting more of my own features. Unfortunately, I don't have that much time. I barely have time to respond to new issues during weekdays. I do most things on the weekends, but I also want to have a life outside of RawTherapee. I know I'm not the only one. Everyone on this project can only dedicate so much time. I don't want to force you to address every one of my comments yourself, but I also only have enough time to help a little. The difficult truth is that responding to new issues, fixing existing bugs, adding camera support, and releasing RawTherapee have higher priority. Someone has to do these things. Roel has left the project, and Maciek is not as active as before. I have taken up the responsibility, even though I'd rather be doing other things, because keeping this project running smoothly is a prerequisite to allow me to do the things I actually want to do.

My question about fixing things in 2 pull requests is just a small question. Because you wanted to add the fix in two places, I had thought that it may be because the issue is in `dev`. After all, what are the odds of both branches having the same issue if they don't inherit it from `dev`? If that were the case, then fixing it in `dev` then merging `dev` back into the two branches would have been the best way to handle the issue. However, after testing all three branches, I see that the looping issue is only present in this PR. Correct me if I'm wrong, but I think the answer to my original question is that *this* is the branch where the fix actually matters. If that's the case, then you can of course add the fix here. For future reference, any minor bug fixes will not disrupt reviews.

**Comment by Desmis** [comment]
@Lawrence37 

Ok I understand, thank you very much.

And I fixed this important bug yesterday

Thank you

Jacques

**Comment by Desmis** [comment]
@Lawrence37 @waynesutton50 

I just update the wavelet novels.
Now in pdf
[Wavelet_novels_RT2024-2.pdf](https://github.com/user-attachments/files/18163687/Wavelet_novels_RT2024-2.pdf)

Jacques

**Comment by Lawrence37** [comment]
Back to the topic of this PR,

I'm following up on my previous comment [here](https://github.com/Beep6581/RawTherapee/pull/7111#issuecomment-2543409264).
1. Regarding contrast profiles 3 and 4: I tried with multiple images, but I still cannot see a difference between 3 and 4. Can you show me an example of the difference between 3 and 4? If you don't have an example, can you explain what differences I should be seeing and what kind of images will show the effect?
2. Contrast curve getting hidden: The related problem had a simple fix (https://github.com/Beep6581/RawTherapee/pull/6781/files). The container holding the curve (`ToolParamBlock`) was missing a function. It's worth a try to add the same function to whatever is holding the contrast curve.
3. Batch edit curve reset: I tested the tone curve in the Exposure tool and it did not have any problem. The editing history feature is complex, so the problem may be hard to find. It could be the processing parameters not being saved properly, the pedited parameter not set correctly, the batch edit add/set code is wrong, or something else.
4. Abstract profile tooltip: I'm not going to debate what should go in the tooltips or if the tooltip should exist. That is not what my comment was about. My issue with the tooltip is that it pops up everywhere so it almost always covers up the next thing I want to adjust. Most tooltips only pop up when you hover over the slider or spinner. Abstract profile is not an adjustment, but a tool, so it's a little different. However, a similar principle can be applied. If the tooltip only activates when hovering over the title, that would improve the usability significantly.
5. Abstract profile expand/collapsed state: What I mean is that Abstract profile should "remember" if it was expanded or collapsed. If it was collapsed, then it should stay collapsed. If it was expanded, then it should stay expanded. The sub-tools inside Lens / Geometry is a good example.

I also tested the other changes in this pull request and found a GUI issue. In Selective Editing > Color Appearance > Source Data Adjustments, using the RGB channels Slope tone mapper with Link R G & B enabled, adjusting red or blue causes adjusters to jump back to the original value. Adjusting green is difficult because the adjuster stops responding to the cursor movement after red and blue are updated. Also, the preview does not reflect the updated red and blue values. I know GUI issues are difficult for you, but there is a working example you can analyze in Raw tab > Sensor with Bayer Matrix > Raw Black Points. With Link greens enabled, the two green adjusters are synchronized and work well.

Other than that, everything else seems to function properly. I did not look at the code yet. I will do that next.

**Comment by Desmis** [comment]
@Lawrence37 
I changed the progressiveness and aggressiveness of "Contrast enhancement" to make it more visible?  Very easy to do for me. this is algorithm work - the code is secondary

Softer for 2 and 3, a little different for 4 and more aggressive for 5 and 6. All these choices are quite arbitrary, but very easy to make. Finding the right compromise for each image and each setting of Wavelet Daubechies moments is not easy. I think this new understanding is overall better

Point 2. Bad GUI behavior with the link to Toolparamblock is typically the kind of thing that is beyond me. I already said it, I don't really understand what I'm doing and copy (like a monkey what is done elsewhere). In this case - I'm not at all sure that this is the solution, I replaced a VBox with ToolParamBlock. This kind of problem where you seem to have "the solution" is typical of the modification that you could do directly in the PR

I will have a look for 3, 4, 5... and behavior but not sure that my poor skills will allow me to solve these problems.

I will also look (still from the GUI) at the synchronization of the sliders using the RGB channels Slope tone mapper.
Just for information, I think it was me, even if it had to be improved later, who made this modification > Raw tab > Sensor with Bayer Matrix > Raw Black Points. With Link greens

Thank you very much.

Jacques

**Comment by Desmis** [comment]
I just made some changes with limited resources. For the holidays I am in Paris, at my daughter's and my materials are minimal.

Maybe the batch problem is solved, I don't check, but there was a missing instruction in ICM, for curve opacityshapeWLI.

I also changed the behavior you reported on the 3 sliders in RGB slope. I replaced a call by improccoordinator, by GUI. but to simplify all the sliders become equivalent when you do "Link R & G & B". Nevertheless it is the "green" which serves as a reference - I removed the word (lead)

Merry Christmas

Jacques

**Comment by Lawrence37** [comment]
1. Contrast profiles: I see a distinct difference between 3 and 4 now. However, 5 and 6 look identical. I looked at your commit and it seems like `level_hr` is the one that results in the biggest visual differences. Before the commit, `level_hr` was different for all profiles except between 3 and 4 (both were `wavelet_lev`). After the commit, `level_hr` was different for all profiles except between 5 and 6 (both are `wavelet_lev + 2`). For my understanding, can you tell me what `level_bl`, `level_hl`, `level_br`, and `level_hr` are?
2. Contrast curve partially hidden: It seems to be fixed.
3. Contrast curve reset in batch edit: It is working properly now.
4. Abstract profile tooltip: It's just a matter of adding the tooltip to a different widget. I could do it myself, but I don't know if you are ok with moving the tooltip.
5. Abstract profile expand/collapse state: I think the state is automatically managed, so you just have to remove any code that expands or collapses the tool.
6. Link RGB: The red and blue adjuster behavior is improved, but the preview is still wrong, and the adjusters still stop responding while I'm trying to drag them.

**Comment by Desmis** [comment]
@Lawrence37 
level_bl, level_hl, level_br, level_hr : represent the values ​​actually used and indirectly the "force" transitions (this is not the right word) of the whole decomposition.
_bl = bottom left - the lowest level used
_hl = hight left - the second low level used. If different from _bl - a transition (in wavelet maths) will be applied 
_br = bottom right - the biggest level used
-hr = hight right - the second biggest level used . If hr < br a transition (in wavelet maths) is applied
Of course, I predefine an average choice and apply values ​​of +1, +2, -1, -2 depending on the case.

In addition, for each of this level range, for each level, each direction, I apply a "MeaLut" which divides the signal into 10 "slices" and applies a variable weighting to take more or less account of the main signal (wavelet) and the artifacts.
Thus with the same _bl, _hl, _br, _hr we will have a different response depending on the images.
This response is also change with "offset" and "Attenuation response". They change the amplitude of the response and its position in the signal.

Another problem often mentioned is the size of the preview. If it is not able to pass 1024x1024 pixels the last level will be ignored in the preview.
But other parameters come into play depending on the images and the wavelet settings. If the images are noisy, with fringes or not, with lens blurs or not, with different vertical, longitudinal, diagonal details... the responses will be different. The system is absolutely not linear. And of course if we change in 'Settings' (SE or Wavelets levels) the number of moments of the wavelets, then there too the answer is different - default D4 - standard.

The simplest is that I reduce by 1 the number of choices of "Contrast enhancement". I will do it today. In fact we hide the miseries of our system. 

For 4) and 5) of your questions, you can change tooltips or anything without any problems, no problem for me. Just wait until I push the next commit on "contrast enhancement".

for Link RGB, I will see another time, but the solution is the "same in principle" as that taken elsewhere (black point, SE Vibrance, etc.. There must be something else...the CIE GUI is very complex and heavy.

Jacques

**Comment by Desmis** [comment]
I just change the number of choices in Contrast enhancement... very easy.

Jacques

**Comment by Lawrence37** [comment]
@Desmis I addressed points 4, 5, and 6.

4. I moved the Abstract Profile tool-tip so that it only shows when hovering over the title (b9c4b61).
5. I removed the code that collapses/shows the expanders when reading processing parameters. Since the expanders are not standalone tools, their states are not persisted between sessions. When opening RawTherappe, Abstract Profile will be collapsed. All its sub-expanders are expanded. The states will be preserved during a session. I also noticed inconsistencies with the right-click to expand behavior. I have fixed it so that all expanders behave correctly (the clicked expander expands and all its siblings collapse). 6b108da
6. The preview for the RGB slope tone mapping was incorrect because the adjusters were synchronized after triggering the preview update. I fix this by performing the synchronization before requesting the update (e3f42b5). I figured out the adjusters stop responding because they were getting hidden then re-shown. This was happening to all the adjusters in the tone mapping section with the Basic complexity. I removed the unnecessary hiding which fixed the issue (8f52751).

**Comment by Desmis** [comment]
@Lawrence37 
Thank you very much for all this work

I am trying with an olf pc of my grandson to reconstitute a provisory system..
I don't know when my Pc will work again, 3 weeks, 1 or 2 mounths ?
Maybe the old an slow pc will work, for a minimal work.

From my smartphone 

Thank you very much
Jacques

File: rtdata/languages/default [hunk 1]
```diff
@@ -1308,19 +1308,19 @@ HISTORY_MSG_1075;Local - CIECAM Surround viewing
 HISTORY_MSG_1076;Local - CIECAM Scope
 HISTORY_MSG_1077;Local - CIECAM Mode
 HISTORY_MSG_1078;Local - Red and skin protection
-HISTORY_MSG_1079;Local - CIECAM Sigmoid strength J
-HISTORY_MSG_1080;Local - CIECAM Sigmoid threshold
-HISTORY_MSG_1081;Local - CIECAM Sigmoid blend
+HISTORY_MSG_1079;Local - CIECAM Sigmoid Q contrast
+HISTORY_MSG_1080;Local - CIECAM Sigmoid Q skew
+HISTORY_MSG_1081;Local - CIECAM Sigmoid Q - Display white point
```
Comment (Lawrence37) [inline rtdata/languages/default]: Are these improvements to the history messages, or are they completely different messages?

File: rtdata/languages/default [hunk 2]
```diff
@@ -1465,23 +1465,41 @@ HISTORY_MSG_ICM_GAMUT;Gamut control
...
 HISTORY_MSG_ICM_WORKING_ILLUM_METHOD;Illuminant method
 HISTORY_MSG_ICM_WORKING_PRIM_METHOD;Primaries method
 HISTORY_MSG_ICM_WORKING_SLOPE;TRC - Slope
 HISTORY_MSG_ICM_WORKING_TRC_METHOD;TRC method
 HISTORY_MSG_ILLUM;CAL - SC - Illuminant
+HISTORY_MSG_LOCAL_CIE_CONTSIG;Local CIECAM - Sigmoid contrast
+HISTORY_MSG_LOCAL_CIE_SKEWSIG;Local CIECAM - Sigmoid skew
+HISTORY_MSG_LOCAL_CIE_KSLOPESMOR;Local CIECAM - Red TRC balance
+HISTORY_MSG_LOCAL_CIE_KSLOPESMOG;Local CIECAM - Green TRC balance
+HISTORY_MSG_LOCAL_CIE_KSLOPESMOB;Local CIECAM - Blue TRCb balance
```
Comment (Lawrence37) [inline rtdata/languages/default]:
```suggestion
HISTORY_MSG_LOCAL_CIE_KSLOPESMOB;Local CIECAM - Blue TRC balance
```

Is there a stray `b` after `TRC`?

File: rtdata/languages/default [hunk 3]
```diff
@@ -1465,23 +1465,41 @@ HISTORY_MSG_ICM_GAMUT;Gamut control
...
+HISTORY_MSG_LOCAL_CIE_SMOOTHTH;Local CIECAM - Attenation threshold
```
Comment (Lawrence37) [inline rtdata/languages/default]:
```suggestion
HISTORY_MSG_LOCAL_CIE_SMOOTHTH;Local CIECAM - Attenuation threshold
```

File: rtdata/languages/default [hunk 4]
```diff
@@ -1514,9 +1532,9 @@ HISTORY_MSG_LOCAL_CIE_GAMUTCIE;Local - CIECAM Gamut
 HISTORY_MSG_LOCAL_CIE_GREXL;Local - CIECAM Green X
 HISTORY_MSG_LOCAL_CIE_GREYL;Local - CIECAM Green Y
 HISTORY_MSG_LOCAL_CIE_ILL;Local - CIECAM TRC Illuminant
-HISTORY_MSG_LOCAL_CIE_LOGCIEQ;Local - CIECAM Log encoding Q
+HISTORY_MSG_LOCAL_CIE_LOGCIEQ;Local - CIECAM Log Encoding Q
 HISTORY_MSG_LOCAL_CIE_MIDT;Local - CIECAM Mid Tones
-HISTORY_MSG_LOCAL_CIE_NORM;Local - CIECAM Normalize L
+HISTORY_MSG_LOCAL_CIE_NORM;Local - CIECAM Scale Yb scene
```
Comment (Lawrence37) [inline rtdata/languages/default]: Is this meant to be the same message but with different wording, or is it supposed to be a new message?

File: rtdata/languages/default [hunk 5]
```diff
@@ -1526,9 +1544,10 @@ HISTORY_MSG_LOCAL_CIE_SHIFTXL;Local - CIECAM Shift x
 HISTORY_MSG_LOCAL_CIE_SHIFTYL;Local - CIECAM Shift y
 HISTORY_MSG_LOCAL_CIE_SIG;Local - Sigmoid
 HISTORY_MSG_LOCAL_CIE_SIGADAP;Local - CIECAM Sigmoid adaptability
-HISTORY_MSG_LOCAL_CIE_SIGMET;Local - CIECAM Sigmoid method
+HISTORY_MSG_LOCAL_CIE_SIGMET;Local - CIECAM Tone mapping Q
```
Comment (Lawrence37) [inline rtdata/languages/default:1545]: Is this meant to be the same message but with different wording, or is it supposed to be a new message?

File: rtdata/languages/default [hunk 6]
```diff
@@ -2282,6 +2302,8 @@ SORT_DESCENDING;Descending
 TC_LOCALLAB_PRIM_SHIFTX;Shift x
 TC_LOCALLAB_PRIM_SHIFTX_TOOLTIP;In combination with "Refine colors", allows you to:\n 1) for low values, adjust the image purity.\n 2) for higher values, carry out moderate color toning.\nBe careful not to go outside the CIE xy diagram.
 TC_LOCALLAB_PRIM_SHIFTY;Shift y
+TP_LOCALLAB_PROCESSWAV;Show modified areas with Wavelets
+TP_LOCALLAB_PROCESSWAV_TOOLTIP;Wavelet decomposition: \nShows the changes made by the wavelet settings.\n\n In Wavelet levels (Advanced tab), you see the results of the decomposition even when there is no action on the wavelet settings.\n\n In Selective Editing Wavelets, you see the changes made to the decomposed image when you act on the wavelet settings, taking into account deltaE and transitions.\n The double slider 'Wavelet levels', allows you to select the entire levels, or a particular range, or a specific level.
```
Comment (Lawrence37) [inline rtdata/languages/default]:
```suggestion
TP_LOCALLAB_PROCESSWAV_TOOLTIP;Wavelet decomposition:\nShows the changes made by the wavelet settings.\n\nYou see the changes made to the decomposed image, factoring in the deltaE and transitions, when you modify the wavelet settings. Note that this is different from Wavelet levels in the Advanced tab in which you always see the results of the decomposition.
```

When you refer to the Wavelets tool in the Advanced tab, I assume you are cautioning the user that the behavior is not identical. If I'm wrong, then my suggested change is not correct.

I also removed the part about the "Wavelet levels" threshold adjuster because it has a tooltip itself.

File: rtdata/languages/default [hunk 7]
```diff
@@ -3603,81 +3637,95 @@ TP_LOCALLAB_SHARP_TOOLNAME;Sharpening
...
 TP_LOCALLAB_SIGBLACKSSCIE;Blacks distribution
 TP_LOCALLAB_SIGCIE;Sigmoid
-TP_LOCALLAB_SIGFRA;Sigmoid Q
+TP_LOCALLAB_SIGFRA;Sigmoid Q & Slope based
 TP_LOCALLAB_SIGGAMJCIE;Gamma
 TP_LOCALLAB_SIGJZFRA;Sigmoid Jz
 TP_LOCALLAB_SIGMAWAV;Attenuation response
-TP_LOCALLAB_SIGMOID16_TOOLTIP;Allows you to simulate a tone mapping appearance using both 'Ciecam' and 'Sigmoid Q'. Sigmoid Q has three sliders:\na) Contrast acts on the shape of the sigmoid curve and consequently on the strength\nb) Threshold (Gray point) distributes the action according to the luminance\nc) Adaptability weights the action of the sigmoid by action on the internal exponential function.
-TP_LOCALLAB_SIGMOIDBL;Blend
+TP_LOCALLAB_SIGMOID16_TOOLTIP;Allows you to simulate a tone mapping appearance using both 'Ciecam' and 'Sigmoid Q' or 'Slope based Q'. Sigmoid Q has three sliders:\na) Contrast acts on the shape of the sigmoid curve and consequently on the strength\nb) Skew (gray point) distributes the action according to the luminance.\nc) Display White point (cd/m2) - mode advanced. \n\nSlope based has only one slider Gray balance (slope).
```
Comment (Lawrence37) [inline rtdata/languages/default]:
```suggestion
TP_LOCALLAB_SIGMOID16_TOOLTIP;Allows you to simulate a tone mapping appearance using both 'Ciecam' and 'Sigmoid Q' or 'Slope based Q'. Sigmoid Q has three sliders:\na) Contrast acts on the shape of the sigmoid curve and consequently on the strength\nb) Skew (gray point) distributes the action according to the luminance.\nc) Display White point (cd/m2) - mode advanced. \n\nSlope based has only one slider: Gray balance (slope).
```

File: rtdata/languages/default [hunk 8]
```diff
@@ -3603,81 +3637,95 @@ TP_LOCALLAB_SHARP_TOOLNAME;Sharpening
...
+TP_LOCALLAB_SIGMOIDBL;Display White point (cd/m2)
```
Comment (Lawrence37) [inline rtdata/languages/default:3698]: Are blend and display white point the same thing?

File: rtdata/languages/default [hunk 9]
```diff
@@ -3603,81 +3637,95 @@ TP_LOCALLAB_SHARP_TOOLNAME;Sharpening
...
 TP_LOCALLAB_SIGMOIDSENSI;Adaptability
-TP_LOCALLAB_SIGMOIDTH;Threshold (Gray point)
-TP_LOCALLAB_SIGMOIDWHITESCIE_TOOLTIP;Allows you, in Automatic when the dynamic range of the image is high, to change the distribution of lights in whites and deep blacks.\nCan be used with Log encoding or Sigmoid with Black Ev and White Ev enabled.\n\nThe algorithm does not change the basic data, but acts on the components necessary to calculate the Dynamic range, Black Ev, White Ev and the Gray point.
-TP_LOCALLAB_SIGMOID_TOOLTIP;Allows you to simulate a tone mapping appearance using both the 'Jz' and 'Sigmoid' function. Three sliders:\na) Contrast acts on the shape of the sigmoid curve and consequently on the strength\nb) Threshold (Gray point) distributes the action according to the luminance\nc)Blend acts on the final aspect of the image, contrast and luminance.
+//TP_LOCALLAB_SIGMOIDTH;Threshold (Gray point)
```
Comment (Lawrence37) [inline rtdata/languages/default]:
```suggestion
```
`//` only works in C++ code.

File: rtdata/languages/default [hunk 10]
```diff
@@ -3603,81 +3637,95 @@ TP_LOCALLAB_SHARP_TOOLNAME;Sharpening
...
+TP_LOCALLAB_SLOPESMOOTHG;Green Slope
+TP_LOCALLAB_SLOPESMOOTHB;Blue Slope
+TP_LOCALLAB_SLOPESMOOTRCR;Red balance (TRC)
+TP_LOCALLAB_SLOPESMOOTRCG;Green balance (TRC)
 TP_LOCALLAB_SLOPESMOOTHG;Green balance (Slope)
 TP_LOCALLAB_SLOPESMOOTHR;Red balance (Slope)
+TP_LOCALLAB_SLOPESMOOTRCB;Blue balance (TRC)
 TP_LOCALLAB_SLOSH;Slope
 TP_LOCALLAB_SMOOTHCIE;Highlight Attenuation
+TP_LOCALLAB_SMOOTHCIE_LNK;Link R & G & B
```
Comment (Lawrence37) [inline rtdata/languages/default]:
```suggestion
TP_LOCALLAB_SMOOTHCIE_LNK;Link R, G, & B
```

File: rtdata/languages/default [hunk 11]
```diff
@@ -3603,81 +3637,95 @@ TP_LOCALLAB_SHARP_TOOLNAME;Sharpening
...
+TP_LOCALLAB_SMOOTHCIE_TRC;Increase gamma-based attenuation
+TP_LOCALLAB_SMOOTHCIE_TRCREL;Relative gamma mode
 TP_LOCALLAB_SMOOTHCIE_LUM;Luminosity mode
 TP_LOCALLAB_SMOOTHCIE_SCA;Scale Yb Scene
-TP_LOCALLAB_SMOOTHCIE_TOOLTIP;Completes the processing carried out by gamma, slope and midtones by causing a slight lowering of lights. Please note this does not replace Highlight reconstruction.\n\nGamma based and Slope based (Standard and Advanced) allow you to simulate a tone mapping using:\na) Scene conditions: Black-Ev, White-Ev, Mean luminance (Yb%)\nb) Viewing conditions: Mean luminance (Yb%).\n\nScale Yb Scene is function of White-Ev.
+TP_LOCALLAB_SMOOTHCIE_TOOLTIP;Completes the processing carried out by gamma, slope and midtones by causing a slight lowering of lights. Please note this does not replace Highlight reconstruction.\n\nGamma based and Slope based (Standard and Advanced) allow you to simulate a tone mapping using:\na) Scene conditions: Black-Ev, White-Ev, Mean luminance (Yb%)\nb) Viewing conditions: Mean luminance (Yb%).\n\nScale Yb Scene is function of White-Ev.\n\nSigmoid allow you to simulate a tone mapping with Contrast and Skew.
```
Comment (Lawrence37) [inline rtdata/languages/default]:
```suggestion
TP_LOCALLAB_SMOOTHCIE_TOOLTIP;Completes the processing carried out by gamma, slope and midtones by causing a slight lowering of lights. Please note this does not replace Highlight reconstruction.\n\nGamma based and Slope based (Standard and Advanced) allow you to simulate a tone mapping using:\na) Scene conditions: Black-Ev, White-Ev, Mean luminance (Yb%)\nb) Viewing conditions: Mean luminance (Yb%).\n\nScale Yb Scene is function of White-Ev.\n\nSigmoid applies tone mapping with Contrast and Skew.
```

Sigmoid is tone mapping, not just a simulation.

File: rtdata/languages/default [hunk 12]
```diff
@@ -4294,6 +4343,8 @@ TP_WAVELET_LEVELS_TOOLTIP;Choose the number of wavelet decomposition levels for
 TP_WAVELET_LEVF;Contrast
 TP_WAVELET_LEVFOUR;Level 5-6 denoise and guided threshold
 TP_WAVELET_LEVLABEL;Preview maximum possible levels = %1
+//TP_WAVELET_LEVLOCLABEL;Preview maximum levels=%1 - Preset=%2
```
Comment (Lawrence37) [inline rtdata/languages/default]:
```suggestion
```

`//` only works in C++ code.

File: rtdata/languages/default [hunk 13]
```diff
@@ -4331,6 +4383,11 @@ TP_WAVELET_OPACITYWL_TOOLTIP;Modify the final local contrast at the end of the w
 TP_WAVELET_PASTEL;Pastel chroma
 TP_WAVELET_PROC;Process
 TP_WAVELET_PROTAB;Protection
+TP_WAVELET_PYRWAVTRC;Contrast profile
+TP_WAVELET_PYRWAVTRC_TOOLTIP;The 'Contrast profile' slider lets you select a series of presets that will significantly modify the effect of the “Variable contrast” curve. The presets range from least to most aggressive in ascending order.\n\nFor the upper preset levels, the visibility of the result in the preview window will depend on the image size and the system configuration. Increase the preview window size if this is the case.
```
Comment (Lawrence37) [inline rtdata/languages/default]: The description of the contrast profile is vague and does not seem to match what it actually does. My understanding, from experimentation and reading your comments, is that it affects the range of wavelet levels used and adjusts the strength of each level to minimize noise and halos. If I'm correct, then I suggest the following.

```suggestion
TP_WAVELET_PYRWAVTRC_TOOLTIP;A series of presets defining the strength of the contrast adjustment at different detail levels. Lower presets only affect fine details while higher presets affect both fine and coarse details.\n\nNote: The effect on coarse details may not be visible in the preview if the preview is too small.
```

File: rtdata/languages/default [hunk 14]
```diff
@@ -4331,6 +4383,11 @@ TP_WAVELET_OPACITYWL_TOOLTIP;Modify the final local contrast at the end of the w
...
+TP_WAVELET_PYRWAVTRC_CURVE_TOOLTIP;The Variable contrast curve takes into account the information provided by the presets. The mid-point of the x-axis corresponds to the predominant contrast value, irrespective of the detail level and the selected preset. The maximum point, to the right of the x-axis, corresponds to the maximum contrast value. It is recommended to reduce the variable contrast beyond the mid-point.
```
Comment (Lawrence37) [inline rtdata/languages/default]: This says the variable contrast is affected by the contrast profile, but doesn't explain how. From what I read in the comments, the effect of the variable contrast is reduced with higher presets. The tooltip also doesn't say why the variable contrast should be reduced after the midpoint. I assume it's to avoid harsh contrast and halos. The following suggestion is based on my assumptions. Please adapt it so that the information is correct.

```suggestion
TP_WAVELET_PYRWAVTRC_CURVE_TOOLTIP;The left end of the horizontal axis corresponds to zero contrast, while the right end corresponds to the strongest contrast in the image. The midpoint of the horizontal axis corresponds to the predominant contrast strength across all detail levels.\n\nThe effect of this curve is reduced for higher Contrast profile presets.\n\nTo avoid harsh contrast and halos, refrain from increasing the right half of the curve.
```

File: rtdata/languages/default [hunk 15]
```diff
@@ -4331,6 +4383,11 @@ TP_WAVELET_OPACITYWL_TOOLTIP;Modify the final local contrast at the end of the w
...
+TP_WAVELET_PYRWAVTRC_RESID_TOOLTIP;Residual contrast, adjusts the residual image after decomposition to compensate for excessive effects linked to the action of the curve and the presets (relief effect, contrast differences between structure and uniform areas).
```
Comment (Lawrence37) [inline rtdata/languages/default]: I'm having a hard time understanding the second half of this tooltip, and I'm sure others will feel this way. For example, what does it mean for the effects to be excessive? Too much contrast? What is "relief effect"? How are the contrast difference between structure (detailed?) and uniform areas problematic? How does the residual contrast compensate for these?

If it was up to me, I would simply explain what the residual contrast does and let the user decide if it helps solve an issue they have. Something like this:
```suggestion
TP_WAVELET_PYRWAVTRC_RESID_TOOLTIP;Adjusts the contrast for all detail levels larger than those covered by the selected Contrast profile.
```

File: rtdata/languages/default [hunk 16]
```diff
@@ -4331,6 +4383,11 @@ TP_WAVELET_OPACITYWL_TOOLTIP;Modify the final local contrast at the end of the w
...
+TP_WAVELET_PYRWAVTRC_SIGMA_TOOLTIP;Attenuation response, distributes the action between the low, medium and high values of the “Variable contrast” curve by widening or narrowing the width of the curve.
```
Comment (Lawrence37) [inline rtdata/languages/default]: This can be more concise.

```suggestion
TP_WAVELET_PYRWAVTRC_SIGMA_TOOLTIP;Stretches the width of the "Variable contrast" curve. A value of 1 means no stretching.
```

**Review by Lawrence37 — COMMENTED** [review]
@Desmis
It's going to take me a while to finish reviewing the code. I just finished `default`. I'm sharing my comments so you can read them while I review the rest of the code.

File: rtengine/curves.h [hunk 17]
```diff
@@ -1611,6 +1611,31 @@ class WavOpacityCurveWL
     }
 };
 
+class IcmOpacityCurveWL
```
Comment (Lawrence37) [inline rtengine/curves.h]: What's the difference between this class (`IcmOpacityCurveWL`) and `WavOpacityCurveWL` and possibly others? They look identical.

**Comment by Desmis** [comment]
@Lawrence37 @waynesutton50 
First of all, please excuse my bad English. For me it's a difficult exercise to make myself understood in French and then to translate into fluent English. I'll use DeepL…. a lot of time spent translating and perhaps not being understood.

I've just picked up my grandson's computer - who very kindly lent it to me while I waited for my computer to arrive.  I'm waiting today (30 december) for UPS to pick it up today. I'm gradually installing what I need to develop on this old computer, but I have a few warnings (which I don't think are too important).

But above all, I haven't recovered “everything”, especially the files where I write down my “tricks”, either for compiling, or certain algorithm choices. I haven't recovered the many exchanges we've had with Wayne on Labels, Tooltips and, above all, Rawpedia content, which touches on all the functions you seem to have mentioned in your comments on “rtdata”. This collaboration with Wayne has been very fruitful, and I'd like to thank him for his advice, particularly in clarifying vocabulary on difficult subjects (Wavelets, Ciecam, Abstract Profile, etc.).

So:
* I'm happy with this very slow machine, on which I'm gradually installing what's necessary (e.g. Kdiff3, Msys2, etc.).
* I have no record of my exchanges with Wayne, which began with Wavelets Levels a few years ago. These exchanges have been very rich, both in terms of translation and in terms of how it's done (what it's used for).
* some modifications go back several years and may have been forgotten or reused to avoid creating a new “event”.

But before I start reading your comments - thank you for all your hard work - a few general explanations to help you understand how I work.

**As I said, I'm not a computer scientist, not at all. My background is :**
* railway maintenance (in particular high-speed trains - TGV), both in technical design (conception of brakes, traction systems, etc.), maintenance design, and managerial management of a maintenance workshop, all of which has nothing to do with IT.
* sociology and human factors on the evolution of maintenance (breakdowns, accidents, professions, etc.), and change management. I did this first within the SNCF company, then as an independent consultant, both to “help” companies and to train managers and specialists.
* I didn't start “doing IT” until 2006, when I started working on colorimetry, and then on Dcraw, in particular with Emil Martinec (who contributed a lot to Rawtherapee).

My cognitive and psychological profile is very atypical. My colleagues in the company used to call me “The 5-legged sheep”. This profile poses major problems of integration with the hierarchy and colleagues who often “don't get it”. I'm not looking to impress, nor to receive praise, nor to develop my ego, but simply to set myself challenges and (try) to solve them - my biggest difficulty is linked to my poor computer coding skills and not always knowing how to translate what I want to do into code.

**The process environment linked to your comments**
The “rtdata” comments essentially concern 4 subjects: Wavelets, Ciecam, Abstract profile and LA (Selective Editing - I won't go into detail here about its history, which began in 2014).
In all 4 cases, I went off the beaten track (this is not to say that other programs that don't use these functions are bad or better, but they are different). My many years spent studying human behavior are a source of understanding for these differences: a) resistance, disapproval, incomprehension, rejection... or, b) conversely, admiration, discovery of another way of doing things. The remarks made over the last few years are clearly more of type a), even if it's obvious that fewer people say they're satisfied than say it's bullshit.

**Wavelet (whether in Wavelets levels or SE wavelet, or SE denoise).**
Comments are often made that Gimp is simpler or that Darktable uses Diffuse and Sharpen. If you look at the principles I summarized in the text on Pixls.us.
https://discuss.pixls.us/t/slope-based-log-encoding-sigmoid-dynamic-range-trc-gamma-slope-abstract-profile-etc/45178/16
file Wavelet_novels_RT2024-2.pdf 
* Gimp does mostly layer manipulation; RT does signal processing.
* ART has used part of Wavelets levels (local contrast) and DT has developed a big communication on “Diffuse and Sharpen” which is "similar" in principle to “Edge sharpness” that I did around 2015 / 2016.
* One of the difficulties is to explain why these differences exist - the users have often long-standing habits (sociology, ergonomics...) that are difficult to change - concerns the language of wavelet decomposition, its principle, the shape of the signal. The debates that took place to write the Rawpedia section (I won't mention the names of the people involved at the time) were very lively, full of misunderstandings, notably the notion of Contrast, Local contrast, Edge sharpness, Attenuation response. Several weeks of exchanges that can best be described as “virile”...
* "Contrast enhancement” is a deliberate simplification of Wavelets that I've tried to summarize in the document Wavelet_novels_RT2024-2.pdf , but of course it uses concepts seen elsewhere (Attenuation response, contrast, etc.) and common definitions and aids (at least that's what I've tried to do).

**Ciecam (whether in “main” or SE Cam16)**
The origin was a request from a former RT member...who had seen some research in 2011. I set out to find out “what is it?”...only to discover researchers' web pages, an Excel spreadsheet and lines of (partial) code from Billy Biggs (I think...in 2003).
From there, this “adventure” began, with clearly 2 camps: a) those who supported this approach and understood the difficulties involved in setting it up; b) those who rejected it, almost on principle: “What's it for?”, “It's an engineer's trick that doesn't interest photographers” (what a mistake...).
I'm not referring here to Jz... which also comes from the work of researchers…

The major problem in getting to what we're interested in here is that Ciecam needs 6 variables open at the same time - J (lightness), Q (brightness), s (saturation) , C (chroma), M (colorfulness), h (hue.) and initially in double precision. So if we use normal programming processes, considerable resource requirements will be necessary. In this case, calling functions from the “loop” (Sigmoid, Log encoding, etc.) proves complex, and the parameters passed are not in a closed interval of type [0 1], but open...
Hence the many attempts - more or less successful - to try Sigmoid (first in a version simplified by the Gaussian function transform) and Log encoding... I gave up on TRC.
When I implemented DT's Sigmoid function embedded in the Ciecam loop, I reused old “events”, but perhaps some Labels or History are inappropriate or useless. 

These difficulties led me to take some of these functions out of the “Ciecam” loop by creating SDA (Source Data Adjustments), but also to try and keep the Sigmoid and Log encoding parts in the “loop” which is more in the Ciecam process.

**Abstract profile and TRC**
 Once again, the debate surrounding the presentation of this concept was full of misunderstandings and sterile (even insulting) debates. I'd like to thank Wayne, who saw the richness that could be reaped from this innovation. Indeed, daring to incorporate ICC into the code when it's neither an “Input”, nor an “Output”, nor a “Working”, gave rise to numerous - often sterile - debates, (very) negative messages addressed to me, and so on.
Those who weren't opposed to “the thing” saw it as a tool for special effects... Of course you can do special effects, but that's not the point. It's a tool for retouching tonality (light/shadows), but also colorimetry (primaries, dominant colors, etc.).

**Adapting several of these concepts to handle DR and attenuation of highlights**
I've found several ways of handling highlights (attenuation), and some algorithms are still being tested, pending approval of the rest of the code so as not to mix everything up.
So, for example, I've highlighted with the ToneMap Freeman algorithm: Gamma based, Slope Based, RGB Channel Slope. But I've also considered adapting the TRC part to each R, G and B channel. The GUI code is inactive, the one in Iplocallab.cc is neutralized (with comment), but the History messages are present. I'll see after the merge if I should keep or delete. Of course you can point out that this isn't rigorous or rational, but I've been doing it this way since I was a kid. 

**I'm now going to gradually, often from memory, make my remarks on your comments,** taking into account that these are neither my usual machine nor my usual tools.

Thanks to my grandson for lending me his computer.

At 2pm (French time) today 30 december,  UPS came to pick up my damaged computer...When will I get the return?

Jacques

File: rtdata/languages/default (hunk 1 above)
Comment (Desmis) [reply rtdata/languages/default]: These comments in history seem correct to me (the syntax may be approximate), but correspond to the reuse of old "events". They correspond to the 3 sliders in "Cam16 image adjustments" Sigmoid Q & slope based  - Sigmoid

File: rtdata/languages/default (hunk 2 above)
Comment (Desmis) [reply rtdata/languages/default]: These message are are part of the hidden and unused code (temporarily?) on the possible modification of the TRC in the 3 components R, G, B... code not used in iplocallab

File: rtdata/languages/default (hunk 3 above)
Comment (Desmis) [reply rtdata/languages/default]: Yes it's a mistake... of course you can (must) change

File: rtdata/languages/default (hunk 4 above)
Comment (Desmis) [reply rtdata/languages/default]: I think it is an old "event" which can be deleted

File: rtdata/languages/default (hunk 5 above)
Comment (Desmis) [reply rtdata/languages/default:1545]: This message replaces the old combobox label, previously it was a choice in the sIgmoid method type (gaussian type), now I reused the "event" for the choice in "Tone mapping Q" between Sigmoid and Slope based

File: rtdata/languages/default (hunk 13 above)
Comment (Desmis) [reply rtdata/languages/default]: I don't know what to answer, we are doing semantics, in English. Both are correct. But, detail, because you grouped the tooltips into one for the title, nothing appears in RT anymore.

Another "detail" is that the French and English languages ​​do not use the same syntax and the same conventions (we talked about this at length with Wayne). In addition, it is not easy to transcribe what is essential and here again, Latins and Anglo-Saxons do not seem to reason in the same way.
:)

File: rtdata/languages/default (hunk 14 above)
Comment (Desmis) [reply rtdata/languages/default]: Here again I don't know what to answer, except that the value 0 is not possible, otherwise it would not be in the decomposition.
I come to believe (it's a joke) that faced with the difficulty of explaining complex things simply, it is better to say nothing

File: rtdata/languages/default (hunk 15 above)
Comment (Desmis) [reply rtdata/languages/default]: Apart from my bad English, I prefer the first version.
Here again, how to write (quite) complex things simply.

The "relief effect" in my bad English translates the "structure", the result of the decomposition. If the user has forced too much on the decomposed part the image will give the impression of being a sculpture. The residual part allows (in part) to attenuate this effect

File: rtdata/languages/default (hunk 16 above)
Comment (Desmis) [reply rtdata/languages/default]: Again, I don't really know what to answer... The usual toolip is the one written below, but in other cases it is integrated into "wavelets" tools... Here it is the same tool, the same function but "hidden", we don't speak of wavelet (an engineer's thing)
I wanted to make a different annotation (so as not to scare), but it is not the exact truth... It is a "false" interpretation. Not easy to popularize


TP_LOCALLAB_WAT_SIGMALC_TOOLTIP;The effect of the local contrast adjustment is stronger for medium-contrast details and weaker for high and low-contrast details.\n This slider controls how quickly the effect dampens towards the extreme contrasts.\nThe higher the value of the slider, the wider the range of contrasts that will receive the full effect of the local contrast adjustment and the higher the risk of generating artifacts.\nThe lower the value, the more the effect will be pinpointed towards a narrow range of contrast values.

File: rtdata/languages/default (hunk 12 above)
Comment (Desmis) [reply rtdata/languages/default]: Not used...
Obviously I don't always delete unused messages... lack of rigor... but that's how I am. 
I almost never take notes (meetings, classes...), I only do it with memory... hence this disorder

File: rtdata/languages/default (hunk 2 above)
Comment (Lawrence37) [reply rtdata/languages/default]: Should these be deleted? If not, is it a typo? The red and green ones use "TRC".

File: rtdata/languages/default (hunk 13 above)
Comment (Lawrence37) [reply rtdata/languages/default]: > nothing appears in RT anymore

What do you mean by this? I don't think I removed anything, at least not intentionally.

File: rtdata/languages/default (hunk 14 above)
Comment (Lawrence37) [reply rtdata/languages/default]: The original tool-tip did not say what the left end of the horizontal axis is, and I don't see an explanation elsewhere. I just said it represents zero contrast as a placeholder. There are 3 pieces of information that should be replaced with the correct details.
1. What contrast the left end of the horizontal axis represents
2. How the contrast profile affects the variable contrast beyond the stated purpose of the contrast profile
3. Why the variable contrast should be reduced in the right half of the curve

File: rtdata/languages/default (hunk 15 above)
Comment (Lawrence37) [reply rtdata/languages/default]: I guess the preferred phrase in English is "unnatural results"? It is a common, albeit generic, phrase used by many photographers.

What do you prefer about the first version?

File: rtengine/curves.h (hunk 17 above)
Comment (Desmis) [reply rtengine/curves.h]: You can attribute this to my incompetence in C++, or an oversight, or inattention. In short, I will try to correct it. At the same time, it will allow me to test my environment (Msys, etc.), my access to Github, etc.
I will push a first commit with 2 changes - to see. Each compilation takes between 12 and 25 minutes.

I hope all will work :)

**Comment by Desmis** [comment]
@Lawrence37 @waynesutton50 
I just made a first "heavy" commit with my old computer...
I removed the KSLOPESMOx messages from the history, I commented the code in Iplocallab.cc , kept the one in locallabtools2, just in case, but in fact GHS does what I wanted to do and better. So we'll see

I remove also all the code of the Class IcmOpacityCurveWL.

I will see (today I think December 31) for the rest of your evaluations in particular the tooltips and prefer yours. On the one hand you are a user, on the other hand you are an English speaker.

Jacques

**Comment by Desmis** [comment]
@Lawrence37 @waynesutton50 
I just made a second commit which includes the changes you wanted for the tooltips.

All these changes on my old computer are slow - between 4 minutes just for the tooltips and almost 20 minutes to recompile the whole thing (of course when there are no errors), but it's better than nothing.

When I said that "nothing appears in RT anymore", I think it was due to my machine configuration, everything works now.

I will answer your question about the overall operation of "contrast enhancement" in more detail later this afternoon (in France)

Jacques

**Comment by Desmis** [comment]
@Lawrence37 @waynesutton50 
Excuse my bad english...

The questions you ask about what “Contrast enhancement” does, the curve and the attached sliders (attenuation, offset) are similar to those asked a few years ago.

I'll try to summarize as best I can, simplifying as much as possible:
* in the case of “Contrast enhancement”, I've chosen to use the maximum range, i.e. 10 levels from 0 to 9. Depending on usage, with the choice of the “contrast profile” slider, 4 to 9 will be used.
* Depending on the “contrast profile” setting, a transition is applied between certain levels, for example between 0 and 1 to minimize the impact of noise, or between 6 and 9 to only partially take into account levels 7, 8 and 9. This transition is not linear.
* A LUT, which I've called MeaLUT, accompanies each preset: on the one hand, it always attenuates in the same way the increase (or attenuation) that the user wishes to make, via the curve, for the part below the “mean”, and progressively attenuates the values above the mean (average). The higher the preset, the greater the attenuation of extreme values, which are usually artifacts.

**Decomposition**
To speak of contrast is an abuse of language, or a mathematical simplification. Depending on the decomposition method (in the case of RT Daubechies) and the developer's choices (in this case, mine).  Starting from the base image, we use a quarter of the image to avoid excessive use of ressources. This results in a (relative) loss of precision for small levels.

In our case (10 levels), we obtain 60 signals (60 = 10 levels * 3 directions * positive/negative).

Taking into account the detailed analysis and appropriate processing of each signal seems to me to be a far-fetched idea. So I tried to model the system according to systemic principles. For me (at least in France), this systemic approach, whose founding father is Jacques Mélèse, is a way of simplifying things while retaining the ability to analyze, diagnose and make decisions.
https://fr.wikipedia.org/wiki/Jacques_M%C3%A9l%C3%A8se

If we look at the “mean” (average) signal of these 60 signals - I've examined more than a dozen images in detail - we generally end up with a signal whose values range around a maximum average zone at :
* values below this “peak” (which is not a peak), which are low in volume
* values above this peak up to 10 or 15 times.
* So the signal is anything but Gaussian.

I believe - without being able to say for sure - I don't have a laboratory - that these non-peak values are the result of :
* the nature of the image, with a strong impact of noise
* the nature of the image, with a strong impact of architecture, leaves, etc.
* lens defects (chromatic aberration, blur, etc.), focus, camera shake, etc.
* decomposition methods: Haar, Morlet, Mallat, Daubechies, etc. Haar's “simple” method, by its very nature, results in less “clean” decomposition. Conversely, the vanishing moments of the Daubechies method - at least in theory - result in a cleaner signal. You can choose - by default 6 - all the way up to value 20 for these moments... The image and signal will be - at least in theory - cleaner.
https://en.wikipedia.org/wiki/Daubechies_wavelet

**How to model?**
In 2013, I decided to choose the average value of the signal data (for each direction, each level), but to simplify things a little, I allowed a certain form of symmetry for the positive and negative values. These values are amplitudes, so to use the word “contrast” seems to me a misuse of language (but let's move on, it's semantics). I call it “mean”.

Then, even if this distribution is not Gaussian, I chose to calculate the standard deviation “sigma” (even if it doesn't make much sense), in order to model the shape of the distribution for values above “mean”.
It's easy to see that very often the difference between near-zero signal values and “mean” (the assumed peak) is less than “sigma”. This is definitely not a Gaussian distribution.

Whatever the level, whatever the direction, I chose to match the middle of the curve to that of the assumed peak. Then the amplification (via a logarithmic scale) decreases up to 2 or 3 sigma or more, for values above the peak. For values below the peak, the standard deviation is useless; I apply a linear law of decay.

As I'm not sure of anything, I've introduced 2 corrective coefficients:
* Attenuation response (this term took a while to formulate, thanks to Wayne), to change the amplitude introduced by “sigma”.
* Offset - to move the peak - the "mean" value.

To indirectly answer the question "Why the variable contrast should be reduced in the right half of the curve". As you can see in my explanations, this is also the case in the left part - but in a more easily accessible way.
The parts outside those around the mean contain mostly artifacts, many on the right (with very high bad values). If we do nothing, we amplify the "good" part of the signal but also the bad ones. This is what happened in Wavelets levels (contrast) before all the improvements that were made. This is also what happens if we apply a uniform correction to each layer, when there is one.
The ideal is to try to reconstruct the "clean" signal, I am doing something that at least in spirit corresponds to a deconvolution - but it is not one at all. It is signal processing.... From my point of view, it is pure systemics, that is to say modeling a complex system, by mathematical simplifications as close as possible to reality.


**So, to simplify :**
* the image is broken down into 60 elements (signals)
* ‘mean’ and ‘sigma’ are calculated for each one - even if they're wrong.
* the action is modeled by a single curve based on the “mean” and “sigma” of each level/direction. A modulation of the signal and therefore of its amplification is applied by the basic algorithm.
* The user can choose a “range” of action via the “Contrast profile” - from the “softest” to the most “aggressive”.
* an additional weighting, specific to each “preset”, reduces the amplitude of the action initiated by the curve, fixed for values below “mean” and variable for values above “mean”.
* The user can choose to modify the basic values of “sigma” (Attenuation response) and “mean” (Offset).

Now it's December 31, I'm going to wish everyone (already) all the best for 2025 and may Rawtherapee prosper.

Jacques

File: rtengine/improcfun.cc [hunk 18]
```diff
@@ -1228,8 +1228,10 @@ void ImProcFunctions::ciecam_02float(CieImage* ncie, float adap, int pW, int pwb
                         Qpro = (Qpro == 0.f ? epsil : Qpro); // avoid division by zero
                         spro = 100.0f * sqrtf(Mpro / Qpro);
 
-                        if (Jpro > 99.9f) {
-                            Jpro = 99.9f;
+                        if(settings->autocielab) {//avoid artifacts
+                            if (Jpro > 99.9f) {
+                                Jpro = 99.9f;
+                            }
                         }
```
Comment (Lawrence37) [inline rtengine/improcfun.cc:1235]: Options that affect the image must be in the processing parameters.

File: rtengine/improcfun.h [hunk 19]
```diff
@@ -389,11 +389,19 @@ enum class BlurType {
...
     void tone_eqdehaz(ImProcFunctions *ipf, Imagefloat *rgb, int whits, int blacks, const Glib::ustring &workingProfile, double scale, bool multithread);
     void tone_eqcam(ImProcFunctions *ipf, Imagefloat *rgb, int midtone, const Glib::ustring &workingProfile, double scale, bool multithread);
+    void tonemapFreeman(float target_slope, float target_sloper, float target_slopeg , float target_slopeb, float white_point, float black_point, float mid_gray_scene, float mid_gray_view, bool rolloff, float smooththreshold, bool limslope, LUTf& lut, LUTf& lutr, LUTf& lutg, LUTf& lutb, int mode, bool scale, bool takeyb);
+    void tonemapFreemanQ(float Q, float &Qout, float target_slope, float white_point, float black_point, float mid_gray_scene, float mid_gray_view, bool rolloff, bool takeyb);
+
+    float do_get(float x, bool rolloff_, float mid_gray_scene, float gamma, float slopelim, float dr, float b, float c, float kmid);
+    float rolloff_function(float x, float dr, float b, float c, float kmid);
+    float scene_contrast(float x, float mid_gray_scene, float gamma);
```
Comment (Lawrence37) [inline rtengine/improcfun.h]: Give these functions more specific names.

File: rtengine/improcfun.h [hunk 20]
```diff
@@ -389,11 +389,19 @@ enum class BlurType {
...
+    void sigmoid_main(float r, float g, float b, float &rout, float &gout, float &bout, float middle_grey_contrast, float contrast_skewness, /* float white_point,*/ float MIDDLE_GREY, float black_point, float white_point_disp);
+    void sigmoid_QJ(float Q, float &Qout, float middle_grey_contrast, float contrast_skewness, float MIDDLE_GREY, float black_point, float white_point_disp);
```
Comment (Lawrence37) [inline rtengine/improcfun.h]:
```suggestion
    void sigmoid_main(float r, float g, float b, float &rout, float &gout, float &bout, float middle_grey_contrast, float contrast_skewness, /* float white_point,*/ float middle_grey, float black_point, float white_point_disp);
    void sigmoid_QJ(float Q, float &Qout, float middle_grey_contrast, float contrast_skewness, float middle_grey, float black_point, float white_point_disp);
```
It's best to reserve uppercase names for constants and `#define`s. It makes it easier to distinguish constants and avoids possible conflicts with `#define`s.

File: rtengine/improcfun.h [hunk 21]
```diff
@@ -463,6 +471,8 @@ enum class BlurType {
             int W_ab, int H_ab, const bool useChannelA, float *meanab, float *sigmaab);
     void Evaluate2(const wavelet_decomposition &WaveletCoeffs_L, float *mean, float *meanN, float *sigma, float *sigmaN, float *MaxP, float *MaxN, int numThreads);
     void Eval2(const float* const* WavCoeffs_L, int level, int W_L, int H_L, float *mean, float *meanN, float *sigma, float *sigmaN, float *MaxP, float *MaxN, int numThreads);
+    void localCont (LabImage * lab, LabImage * dst, const procparams::WaveletParams & waparams, const procparams::ColorManagementParams & cmparams, const WavOpacityCurveWL & cmOpacityCurveWL, int skip, int &level_hr, int &maxlevpo, bool &wavcurvecont);
+    void gamutCont (LabImage * lab, LabImage * dst, const procparams::WaveletParams & waparams, const procparams::ColorManagementParams & cmparams, int skip);
```
Comment (Lawrence37) [inline rtengine/improcfun.h]: Rename these functions to be more descriptive.

File: rtengine/iplocallab.cc [hunk 22]
```diff
@@ -3697,15 +3931,15 @@ void ImProcFunctions::ciecamloc_02float(struct local_params& lp, int sp, LabImag
 
             //simple local contrast in function luminance
             if (locwavCurvejz && locwavutilijz && wavcurvejz) {
-                float strengthjz = 1.2;
+                float strengthjz = 1.3f;
```
Comment (Lawrence37) [inline rtengine/iplocallab.cc]: Does this change the output of edits created in 5.11?

File: rtengine/iplocallab.cc [hunk 23]
```diff
@@ -4246,15 +4473,17 @@ void ImProcFunctions::ciecamloc_02float(struct local_params& lp, int sp, LabImag
...
-
+  //      float *datain = nullptr;
+  //      float *data = nullptr;
+  //      float *datanorm = nullptr;
+/*
         if ((sigmoidnorm  && issigq)  || params->locallab.spots.at(sp).logcieq) {
             datain = new float[width* height];
             data = new float[width * height];
             datanorm = new float[width * height];
+#ifdef _OPENMP
```
Comment (Lawrence37) [inline rtengine/iplocallab.cc]:
```suggestion
```
Duplicate line.

File: rtengine/iplocallab.cc [hunk 24]
```diff
@@ -4437,11 +4659,11 @@ void ImProcFunctions::ciecamloc_02float(struct local_params& lp, int sp, LabImag
...
                         Qpro = (Qpro == 0.f ? epsil : Qpro); // avoid division by zero
                         spro = 100.0f * sqrtf(Mpro / Qpro);
-
-                        if (Jpro > 99.9f) {
-                            Jpro = 99.9f;
+                        if(settings->autocielab) {//avoid artifacts
+                            if (Jpro > 99.9f) {
+                                Jpro = 99.9f;
+                            }
                         }
```
Comment (Lawrence37) [inline rtengine/iplocallab.cc]: Options that affect the image must be in the processing parameters.

File: rtengine/iplocallab.cc [hunk 25]
```diff
@@ -10964,8 +11224,8 @@ void ImProcFunctions::wavcontrast4(struct local_params& lp, float ** tmp, float
 //edge sharpness end
 
     if (locwavCurve && locwavutili && wavcurve) {//simple local contrast in function luminance
-        float strengthlc = 1.5f;
-        wavlc(*wdspot, level_bl, level_hl, maxlvl, level_hr, level_br, ahigh, bhigh, alow, blow, lp.sigmalc, strengthlc, locwavCurve, numThreads);
+        float strengthlc = 1.7f;
```
Comment (Lawrence37) [inline rtengine/iplocallab.cc]: Does this change the results of edits from 5.11?

File: rtengine/ipwavelet.cc [hunk 26]
```diff
@@ -3400,6 +3403,394 @@ void ImProcFunctions::calckoe (const float* WavCoeffs, float gradw, float tloww,
     }
 }
 
+void ImProcFunctions::gamutCont (LabImage * lab, LabImage * dst, const procparams::WaveletParams & waparams, const procparams::ColorManagementParams & cmparams, int skip)
```
Comment (Lawrence37) [inline rtengine/ipwavelet.cc]: This function doesn't appear to be related to wavelets. Move it to a more appropriate file, or remove it since it's not being used.

File: rtengine/ipwavelet.cc [hunk 27]
```diff
@@ -3400,6 +3403,394 @@ void ImProcFunctions::calckoe (const float* WavCoeffs, float gradw, float tloww,
...
+            // adapt maximum level wavelet to size of crop
+            while ((1 << maxlevelspot) >= minwin && maxlevelspot  > 1) {
+                --maxlevelspot ;
+            }
+
+            int wavelet_level = rtengine::min(level_hr, maxlevelspot);
+            int maxlvl = wavelet_level;
+            maxlevpo = maxlvl;
+            //decomposition wavelet , we can change Daublen (moment wavelet) in Tab - Wavelet Levels with subsampling = 1
+            wavelet_decomposition *wdspot = new wavelet_decomposition(lab->L[0], width, height, maxlvl, 1, skip, numThreads, DaubLen);
```
Comment (Lawrence37) [inline rtengine/ipwavelet.cc]:
```suggestion
            std::unique_ptr<wavelet_decomposition> wdspot = std::unique_ptr<wavelet_decomposition>(new wavelet_decomposition(lab->L[0], width, height, maxlvl, 1, skip, numThreads, DaubLen));
```
Use a unique pointer to avoid accidentally leaking memory.

File: rtengine/ipwavelet.cc [hunk 28]
```diff
@@ -3400,6 +3403,394 @@ void ImProcFunctions::calckoe (const float* WavCoeffs, float gradw, float tloww,
...
+
+                                }
+                            }
+                        }
+                    }
+                }
+            }
+            //reconstruct lab
+            wdspot->reconstruct(lab->L[0], 1.f);
+            delete wdspot;
```
Comment (Lawrence37) [inline rtengine/ipwavelet.cc]:
```suggestion
```
If `wdspot` is converted into a unique pointer, deletion is automatic.

File: rtengine/procparams.cc [hunk 29]
```diff
@@ -2713,9 +2733,13 @@ bool ColorManagementParams::operator ==(const ColorManagementParams& other) cons
...
         && wcat == other.wcat
-        && workingTRCGamma == other.workingTRCGamma
-        && workingTRCSlope == other.workingTRCSlope
+        && wGamma == other.wGamma
+        && wSlope == other.wSlope
         && wmidtcie == other.wmidtcie
+        && sigmatrc == other.sigmatrc
+        && offstrc == other.offstrc
+        && pyrwavtrc == other.pyrwavtrc
+        && opacityCurveWLI == other.opacityCurveWLI
```
Comment (Lawrence37) [inline rtengine/procparams.cc]: Missing a `residtrc == other.residtrc` here?

File: rtengine/procparams.cc [hunk 30]
```diff
@@ -10305,12 +10393,21 @@ int ProcParams::load(const Glib::ustring& fname, ParamsEdited* pedited)
...
+                assignFromKeyfile(keyFile, "Locallab", "slopesmoq_" + index_str, spot.slopesmoq, spotEdited.slopesmoq);
                 assignFromKeyfile(keyFile, "Locallab", "slopesmor_" + index_str, spot.slopesmor, spotEdited.slopesmor);
                 assignFromKeyfile(keyFile, "Locallab", "slopesmog_" + index_str, spot.slopesmog, spotEdited.slopesmog);
                 assignFromKeyfile(keyFile, "Locallab", "midtcie_" + index_str, spot.midtcie, spotEdited.midtcie);
                 assignFromKeyfile(keyFile, "Locallab", "slopesmob_" + index_str, spot.slopesmob, spotEdited.slopesmob);
+                assignFromKeyfile(keyFile, "Locallab", "kslopesmor_" + index_str, spot.kslopesmor, spotEdited.kslopesmor);
+                assignFromKeyfile(keyFile, "Locallab", "kslopesmog_" + index_str, spot.kslopesmog, spotEdited.kslopesmog);
+                assignFromKeyfile(keyFile, "Locallab", "kslopesmob_" + index_str, spot.kslopesmob, spotEdited.kslopesmob);
+                assignFromKeyfile(keyFile, "Locallab", "midtcie_" + index_str, spot.midtcie, spotEdited.midtcie);
```
Comment (Lawrence37) [inline rtengine/procparams.cc]:
```suggestion
```

This is a duplicate of line 10405.

File: rtengine/procparams.cc [hunk 31]
```diff
@@ -10218,7 +10302,7 @@ int ProcParams::load(const Glib::ustring& fname, ParamsEdited* pedited)
                 assignFromKeyfile(keyFile, "Locallab", "Sensicie_" + index_str, spot.sensicie, spotEdited.sensicie);
                 assignFromKeyfile(keyFile, "Locallab", "AutoGraycie_" + index_str, spot.Autograycie, spotEdited.Autograycie);
                 assignFromKeyfile(keyFile, "Locallab", "Forcejz_" + index_str, spot.forcejz, spotEdited.forcejz);
-                assignFromKeyfile(keyFile, "Locallab", "Forcebw_" + index_str, spot.forcebw, spotEdited.forcebw);
```
Comment (Lawrence37) [inline rtengine/procparams.cc:10221]: Does this break compatibility, or was it never used?

File: rtgui/icmpanel.cc [hunk 32]
```diff
@@ -645,6 +771,8 @@ void ICMPanel::updateRenderingIntent(const Glib::ustring &profile)
 ICMPanel::~ICMPanel()
 {
     idle_register.destroy();
+    delete opacityCurveEditorWLI;
+
```
Comment (Lawrence37) [inline rtgui/icmpanel.cc]: Make `opacityCurveEditorWLI` a unique pointer so that it is automatically deleted.

File: rtgui/locallabtools2.cc [hunk 33]
```diff
@@ -8491,16 +8540,15 @@ Locallabcie::Locallabcie():
...
     bwevMethod->append(M("TP_LOCALLAB_BWEVSIG"));
+    bwevMethod->append(M("TP_LOCALLAB_BWEVSLOP"));
     bwevMethod->set_active(1);
     bwevMethodConn = bwevMethod->signal_changed().connect(sigc::mem_fun(*this, &Locallabcie::bwevMethodChanged));
     modeHBoxbwev->pack_start(*bwevMethod);
 
     comprBox->pack_start(*comprcie);
     comprBox->pack_start(*strcielog);
     comprBox->pack_start(*satcie);
-    comprBox->pack_start(*logcieq);
```
Comment (Lawrence37) [inline rtgui/locallabtools2.cc]: Remove all references to `logcieq`.

File: rtgui/locallabtools2.cc [hunk 34]
```diff
@@ -8557,18 +8617,13 @@ Locallabcie::Locallabcie():
 
     expprecam->add(*gamcieBox, false);
 
-
+    sigfraBox->pack_start(*modeHBoxbwev);
+    sigfraBox->pack_start(*slopesmoq);
     sigfraBox->pack_start(*sigmoidldacie);
     sigfraBox->pack_start(*sigmoidthcie);
-    sigfraBox->pack_start(*sigmoidsenscie);
```
Comment (Lawrence37) [inline rtgui/locallabtools2.cc:8563]: Remove all references to `sigmoidsenscie`.

File: rtdata/languages/default [hunk 35]
```diff
@@ -1514,9 +1529,9 @@ HISTORY_MSG_LOCAL_CIE_GAMUTCIE;Local - CIECAM Gamut
 HISTORY_MSG_LOCAL_CIE_GREXL;Local - CIECAM Green X
 HISTORY_MSG_LOCAL_CIE_GREYL;Local - CIECAM Green Y
 HISTORY_MSG_LOCAL_CIE_ILL;Local - CIECAM TRC Illuminant
-HISTORY_MSG_LOCAL_CIE_LOGCIEQ;Local - CIECAM Log encoding Q
+HISTORY_MSG_LOCAL_CIE_LOGCIEQ;Local - CIECAM Log Encoding Q
 HISTORY_MSG_LOCAL_CIE_MIDT;Local - CIECAM Mid Tones
-HISTORY_MSG_LOCAL_CIE_NORM;Local - CIECAM Normalize L
+//HISTORY_MSG_LOCAL_CIE_NORM;Local - CIECAM Scale Yb scene
```
Comment (Lawrence37) [inline rtdata/languages/default]: `//` only works for C++

**Comment by Lawrence37** [comment]
I was trying to understand how the CAM16 and JzCzHz changed from 5.11 and found an issue applying 5.11 edits. The images come out much darker, almost completely black.

Sigmoid Jz: [jzazbz.pp3.txt](https://github.com/user-attachments/files/18270868/jzazbz.pp3.txt)
CAM16 Sigmoid Q: [cam16.pp3.txt](https://github.com/user-attachments/files/18270877/cam16.pp3.txt)

File: rtengine/improcfun.cc (hunk 18 above)
Comment (Desmis) [reply rtengine/improcfun.cc:1235]: This fix put in "Preferences" is a collective choice made in 2012 I think (or 2013?). We - designers and very limited users were confronted with the artifacts of the first version of ciecam02 (the very first). We put it in "settings" to not weigh down the already very busy Ciecam interface.
It only concerns Ciecam02.
Should it be removed from "Preferences" or kept for compatibility... Certainly Ciecam02 is obsolete - especially the first version - but RT must I think (nostalgia?) preserve traces of the past (Feedback)

File: rtengine/improcfun.h (hunk 20 above)
Comment (Desmis) [reply rtengine/improcfun.h]: I will change all MIDDLE_GREY and MIDDLE_GREYjz in improcfun.h and iplocallab.cc

I had only "copied" the code from ART and Darktable where MIDDLE_GREY is indeed a constant, whereas in RT it is a variable

File: rtengine/iplocallab.cc (hunk 22 above)
Comment (Desmis) [reply rtengine/iplocallab.cc]: To preserve compatibility , i Will change to 1.2 - very very low differences

File: rtengine/iplocallab.cc (hunk 23 above)
Comment (Desmis) [reply rtengine/iplocallab.cc]: OK

File: rtengine/iplocallab.cc (hunk 24 above)
Comment (Desmis) [reply rtengine/iplocallab.cc]: I think, with Cam16 we can remove this "old" code

File: rtengine/iplocallab.cc (hunk 25 above)
Comment (Desmis) [reply rtengine/iplocallab.cc]: To preserve compatibility I will change to 1.5... Very very low differences

File: rtengine/improcfun.h (hunk 19 above)
Comment (Desmis) [reply rtengine/improcfun.h]: The name of these functions - whose action I modified - is directly copied either from Freeman's code or from ART.
I admit, and even more so given my bad English, that I have trouble understanding why they were called like that. For example, the expression Rolloff is almost untranslatable in French or not with the meaning it has here

I change it to something that I think is more explicit

new names
get_freeman_parameters
rolloff_freeman_function
scene_referred_contrast

File: rtengine/improcfun.h (hunk 21 above)
Comment (Desmis) [reply rtengine/improcfun.h]: I remove completely Gamutcont.... lead to artifacts

I rename localCont as complete_local_contrast

File: rtengine/ipwavelet.cc (hunk 26 above)
Comment (Desmis) [reply rtengine/ipwavelet.cc]: I remove this function, not used and leads to artifacts

File: rtengine/ipwavelet.cc (hunk 27 above)
Comment (Desmis) [reply rtengine/ipwavelet.cc]: OK, no problem

File: rtengine/ipwavelet.cc (hunk 28 above)
Comment (Desmis) [reply rtengine/ipwavelet.cc]: of course

File: rtengine/procparams.cc (hunk 30 above)
Comment (Desmis) [reply rtengine/procparams.cc]: OK

File: rtengine/procparams.cc (hunk 29 above)
Comment (Desmis) [reply rtengine/procparams.cc]: OK I have forgotten...

File: rtgui/icmpanel.cc (hunk 32 above)
Comment (Desmis) [reply rtgui/icmpanel.cc]: I absolutely do not know how to do this... As I say I copy (like a monkey) what is elsewhere.
Can you give me the code, or change it yourself

Thank you

File: rtdata/languages/default (hunk 35 above)
Comment (Desmis) [reply rtdata/languages/default]: ok

File: rtengine/procparams.cc (hunk 31 above)
Comment (Desmis) [reply rtengine/procparams.cc:10221]: In all the changes I made to improve "Sigmoid" and "log encoding" with Ciecam, whether outside the Ciecam loop (SDA) or inside the loop I forgot to remove "forcejz". Now it's done.

it's the same as "forcebw", but now it's useless. Ensuring compatibility with something that doesn't work or works very badly seems totally absurd to me... What's the point of free software? Are we a place for research? Should we ensure compatibility at all costs, even if it means doing stupid things?
I'll explain it further in a message.

File: rtgui/locallabtools2.cc (hunk 33 above)
Comment (Desmis) [reply rtgui/locallabtools2.cc]: OK but see my post on free software and compatibility

File: rtgui/locallabtools2.cc (hunk 34 above)
Comment (Desmis) [reply rtgui/locallabtools2.cc:8563]: OK but see my post on free software and compatibility

**Comment by Desmis** [comment]
@Lawrence37  @waynesutton50 
> I was trying to understand how the CAM16 and JzCzHz changed from 5.11 and found an issue applying 5.11 edits. The images come out much darker, almost completely black.

it seems more than obvious that this cannot work in any case and that ensuring compatibility seems to me a totally (or almost) impossible or absurd mission, and for what purpose?
I will, in a moment, express my point of view on this subject. Of course, one can totally disagree with me.

**Comment by Desmis** [comment]
@waynesutton50 @Lawrence37  and others.

What are we good for? What are the aims and objectives of free software? Do we have to ensure compatibility with previous versions at all costs? Do we or don't we contribute to some form of research, etc.?

Lawrence, your comments on the compatibility of this version with 5.11 are worth asking the questions mentioned above (which are not exhaustive).

In fact, all the Sigmoid (and Log encoding) functions that were either outside the SDA (Source Data Adjustments) loop, or inside the loop, have been completely rewritten or removed... which obviously leads to incompatibility. Previous versions for Sigmoid were based on a basic Sigmoid function (transformed from the Gaussian function), while the SDA version is now close to the Darktable (or ART) version. The one in the loop is different again, because of the use of brightness Q. What's more, I eliminated the call to “log encoding” from the Ciecam loop... I didn't try the call to TRC from the Ciecam loop (too complex for me).

The very principle of ensuring compatibility with something experimental (Jz is totally experimental – the researchers' original code doesn't work very well...this isn't a criticism but an observation-   and Ciecam, even the Cam16 version,  is still an unfinalized “project”), seems to me ubiquitous.

A few years ago, in connection with Wavelets and Retinex, I was told that RT was not a research laboratory... In the same demonstration, it was stated that my code was no good (it's true), and that I couldn't tell when a modification would be completed. This is totally true.... And I still don't know today.

As I said, developing new processes such as Ciecam, Wavelets, Retinex, White balance auto, Selective Editing, Capture sharpening, Colour propagation, etc. doesn't happen without effort, without more or less successful trials... with trial and error, but at some point you have to “close the suitcase”. That's what I did with Ciecam / Jz and Sigmoid and Tone-mapping some years ago. I re-opened these files. 

The intellectual challenge is great. There's nothing to copy anywhere (or not much), it's all innovation. So if we change something important, there's bound to be incompatibility. To want to simultaneously: a) improve an experimental system, and b) ensure compatibility with a previous buggy version, seems totally surreal to me. Of course this must be mentioned in the documentation, but it seems to me that the majority of users are sensible people and understand these evolutions if they are explained to them. I even think that's one of the added values of free software: it's free, but you're contributing to progress.

Is the aim of free software to make a poor copy of paid-for software (Lightroom, DxO, C1, etc.) or to simply copy each other? Of course, the form of “competition” that exists between Darktable, ART and Rawtherappee is a source of progress and is indispensable, but if nobody innovates, what happens? To take an example, aren't “we” (DT, ART, RT...) doomed by the arrival of artificial intelligence? What should we be doing? Of course, my 78th birthday is coming up, but challenges like this are particularly motivating.

And what is innovation? 
1) Is it a clearer, easier, simpler GUI interface, with an adapted vocabulary? (software for photographers or engineers, ART/RT comparison, etc.).
2) Is it new functionalities based on high-performance code writing : for example, I admire ART's CTLs, but am totally unable to reproduce them, or RT's ability to produce executables that can be used by anyone almost instantaneously, or innovation as Framing, etc.?
3) Is it new algorithms such as Ciecam, Wavelets, or the adaptation of existing innovations such as GHS.
4) ??

The answer is probably all three... But as much as 1) or 2) seem to be accepted and even desired - which is obvious - 3) is a source of controversy... and of course 3) by its very nature, is the greatest source of incompatibility. 3) has as its main ingredient research, not in the academic sense of the term, but in the sense of progress and innovation in free software.

So, to sum up, what are we good for? Why do we do these exchanges? What does the future hold?

And happy new year

Jacques

**Comment by Lawrence37** [comment]
As you know, the topics of compatibility and experimentation predate my contributions to RawTherapee. I am simply trying to preserve the established principles of RawTherapee because I do not believe I have the authority or justification to change the rules. Of course, that does not mean we will be forever constrained by them, but it's obvious that changing the rules require agreement between contributors and communication with users.

Preserving compatibility does not necessarily prevent us from innovating and improving. It is always possible to have the old features coexisting with new ones. Take darktable's filmic for example. I think you have followed its development enough to know of it's evolution. The current iteration is significantly different from, and in many ways incompatible, with the initial version. Yet, all edits are preserved with a simple and user-friendly trick: making it possible to select the filmic version. I use this as an example. It is not the only way to preserve compatibility.

The most important thing is for users to be aware of what's happening. Think of things from a user's perspective. If they use the selective editing color appearance tool, upgrade to a new version of RawTherapee, and find that their edits have changed, do you think the user will reason that the color appearance tool has changed, or will they think there is a bug? Most likely, they will think it is a bug, specifically, a regression. The only way the user could have anticipated the change was if they followed the development closely or read the manual from front to back. Most users will not do this. If we want to make a breaking change, it needs to be clearly communicated with users. One example is by changing the major version (e.g. from 5.x to 6.x) and explaining it on the release notes (even this has problems because some people won't see the release notes, like those who use their Linux distribution's package manager). Another example is adding a prominent warning in the tool itself saying that the tool is experimental and subject to change.

We are allowed to innovate and improve, but we must think of the end user if we want RawTherapee to thrive.

**Comment by Desmis** [comment]
@Lawrence37 @waynesutton50 

**I am perfectly aware of the problems you mention** and yes I know Filmic and its developments, but this development seems minimal to me compared to the one I am proposing. I am not talking about the quality of Filmic, nor about what I have done, but about the principle.

On the one hand, a **current version that does not work** (or badly) or that gives little contrast or none at all and a 'log encoding' function incorporated in the loop full of malfunctions (This is of course what I have observed, but also the (very) rare testers). And on the other hand **a system that works** (finally) even if it is perfectible. We can apply to this last one the principle such as Filmic5 and Filmic6

I maintain my point, it is a system under development and it is far from simple. I am not talking about code, but about algorithm: how to replace the 3 RGB dimensions usually used in Filmic, Sigmoid, Log encoding,... by only Q data that are eminently variable, depending on the conditions of the Scene (in the Ciecam sense of the term, a broader sense than what exists in DT).
Of course in a complex way by keeping all the sliders from before, the algorithm from before, all the concepts from before (which by the way had been poorly understood by users in the joint tests we did 2 to 3 years ago). I made this choice voluntarily, because the evolution that I propose is **something that works badly** (or very badly) **replaced by something that works** (at least that's what I think). The opinions of the rare testers of the old version were more than mixed certainly to be friendly with me... but I say it almost unusable - in particular "Log encoding" in the Ciecam loop, and Sigmoid was a poor sigmoid..

**I'm sure that waiting for a hypothetical 6.0 version would be a mistake**, because on the one hand when it will come... I'll probably be dead or unable to contribute, and on the other hand it will still be necessary to explain why it doesn't work like before.
**Portability by a double code (and therefore a double GUI) will in my point of view cause more problems than solve them.**
Of course we can say "it's incompatible, but it's 6.0", and then the user who was using the previous version (they must be very rare) will be faced with the same dilemma.
Offering the 2 choices, is - seen from the user's point of view - to say that the solution "1" of "before" and the "2" of "now" are both viable like Filmic 5 and Filmic 6. This is not the case.

So, from my point of view, and if necessary with great regret I would add sliders, checkboxes, comboboxes and (re)introduce the functions and variables that I just removed. But I think that would be a **huge mistake**, a worse solution than the one I propose.

The solution I propose is 
* to **write it in the documentation,** of course if we have it, but as you point out the user generally does not read it.
* to put **a tooltip for these 2 parts** which mainly concern Sigmoid, which explains the differences
* to **put a marker on the labels** for example a "*" to attract attention
* Give the **explanations on the forum** as I am doing here
* if a user is faced with a "bug" (it does not work as before), it is an **incredible opportunity for collective learning**. Explaining why, how not to one person, but to a collective. It is a feedback (Rex in French) which is not limited to the facts (the bug), but to the learning of new processes, new habits, new skills;

Cordially

Jacques

**Comment by Desmis** [comment]
@Lawrence37 @waynesutton50 
I just push a commit with small changes to labels and tooltips which concern calls to sigmoid (and log encoding)

I added 3 **"*"** to 3 frames, **to draw attention**:
1) Tone mapping operators *  - in Source Data Adjustments (SDA)
2) Sigmoid Q & Slope based * - in Cam16 Image Adjustments
3) Sigmoid Jz * - in JzCzHz - Scene Conditions

**Tooltips are always visible** even if you don't activate the option in Preference.

I added - in my bad English - at the end of the current tooltips - **a text to explain the incompatibility**:
* for 1) and 3)  "This new version of Sigmoid is incompatible with previous versions 5.11 and earlier"
* for 2) "This new version of Sigmoid is incompatible with previous versions 5.11 and earlier. Log encoding inside Ciecam is removed."

Of course you can (must) change this proposition. But it seems to me (at least to me) clear in principle.

Jacques

File: rtdata/languages/default (hunk 6 above)
Comment (Desmis) [reply rtdata/languages/default]: I will change , forgotten. Excuse me

File: rtdata/languages/default (hunk 7 above)
Comment (Desmis) [reply rtdata/languages/default]: I will change, this , forgotten

File: rtdata/languages/default (hunk 8 above)
Comment (Desmis) [reply rtdata/languages/default:3698]: No Display white point (cd/m2) is a reuse of 'blend' which was a roundabout way to make Tone-mappers work in the loop... but worked very poorly, hence the removal

File: rtdata/languages/default (hunk 9 above)
Comment (Desmis) [reply rtdata/languages/default]: ok

File: rtdata/languages/default (hunk 10 above)
Comment (Desmis) [reply rtdata/languages/default]: ok

File: rtdata/languages/default (hunk 11 above)
Comment (Desmis) [reply rtdata/languages/default]: OK

**Comment by Desmis** [comment]
@Lawrence37 @waynesutton50 
I'd like to add some arguments as to why I defend my “loss of compatibility” point of view.
It all has to do with the design (internal algorithm) devised by the researchers of both Ciecam and Jz.
I'm not going to go back over what Ciecam or Jz is (it's explained in Rawpedia - unavailable), but explain the profound differences:
* Ciecam takes into account 3 parameters (Scene reffered to speak in DT language, which paradoxically are little or not taken into account by DT or ART): Surround, Absolute luminance, but also Mean luminance.
** Surround, even when set to 'minimum', introduces a significant increase in shadows (hence the name Lighting). As luminance is not evaluated 'upstream', but in the Ciecam process itself, minimum Q values are initially more important than upstream RGB values.
** Mean Luminance - is not a value (middle_grey) , is not a fixed value, or entered with a slider, but a calculated value.
** Absolute luminance - is not a fixed - or unknown - value, but determined from the exifs of the shot. It takes into account, for example (as the camera corrects for it), the differences between morning and midday light.
** Of course, Ciecam also takes into account other parameters such as simultaneous contrast.
* Jz is a more than experimental system, the Zcam version - equivalent to ciecam (at least in the last tests I did) doesn't work. As for Jz, all you have to do is look at the opinions of those who have tried it to understand either that there are bugs, or that it's poorly explained. The data for “absolute luminance” and HDR PQ are not in the 0..1 range, but often 0 - 0.25 or less. This means that you have to 'trick' to get the curves, sliders and algorithms to work.

That said, if you want to call a function “Log encoding Q”, the downstreams transmitted will be - very different - especially for low light. The reconstruction after Ciecam, will compensate 'believing' that this is natural, which is not the case. After many attempts to 'compensate', I gave up.
For Sigmoid (the version I used, which was a transform of the Gaussian function), as Log encoding it was unable to render lowlights, since Ciecam already did this. The Darktable version, thanks to them, although based on the same principle, goes even further in recovering lowlights. Hence my decision to abandon the old Sigmoid.

The same applies to Jz.
I had tried to 'compensate' with the 'Blend' slider, which tried to blend the old image with the new one, but to no avail.

So I decided to break it off because it didn't work or didn't work well.

The new 'Sigmoid', currently in use, has some differences with ART/DT: on the one hand, it takes variable data into account (mean luminance, absolute luminance), and on the other, in the Ciecam loop, it works with Q (brightness), which doesn't have the same references for lowlights, nor the same light distribution, nor the same final translation into RGB.

Of course, I can change the comboboxes, checkboxes and sliders I've reused internally and recreate the old version... It's not difficult, just a bit of work (tedious to do at GUI level) and reintroduce the old Sigmoid. But I think this would be a mistake, because it would make people think that - to use your comparison - it's an evolution like that from Filmic5 to Filmic6. It's not. We're replacing something that can't work, with something that does work - but differently from ART/DT.

But if introducing a change that will complicate the GUI and introduce bad behavior, that will take a few days to write the 2 code, is desired, I would do it with regret.

Jacques

**Comment by Desmis** [comment]
@Lawrence37 @waynesutton50 
There has been at least one precedent of incompatibility. This concerns Shadows/highlight in April 2018

And I'm sure there were many more users of Shadows/highlight than the "hidden" Sigmoid feature housed in the Ciecam loop


https://discuss.pixls.us/t/shadows-highlights-tool/7408/6

Cordially

:)

Jaqcues

**Comment by Desmis** [comment]
@Lawrence37 @waynesutton50 

I think I have finished, from my point of view, adding the old algorithms to process Tone-mapping inside the Ciecam or Jz loop, which I remind you only use one variable (Q or J) instead of the 3 R, G, B. Furthermore these variables are not and do not have a linear response.

The choice, only for these old algorithms is at the start of Cam16 & JzCzHz. This choice is more guided to maintain historical traceability (Feedback), than to ensure software compatibility. But of course the user should find his 5.11 settings (I hope).

Of course we have to check that everything works as well as the Labels, tooltips, history - The syntax - in English - is not my strong point, on the one hand the language problem, as well as the writing conventions which are different between France and Anglo-Saxon countries.

Wayne is due to provide me with some information in the coming week :)

It should be noted, but it is obvious, that as the algorithms are totally incompatible (except their name - Sigmoid), this introduces an additional number of Widgets (Sliders, Frame, Checkbox, etc.), with consequences on the necessary resources.

I took advantage of this PR to correct the typo in paramsedited.cc issue #7283 . We're not going to open a PR just for that.

I can too, but here we must not do duplicate work, correct my oversight in "BlurNoise_Local", provided in the PR #7274, but I await your point of view on this last point
 if(lp.fullim == 3 ) {//disabled scope
                    reducdE = 1.f;
}

And everything was done with my grandson's computer, which was not very powerful (but at least it allowed compilation) and had a multitude of warnings...(fonts, etc.)

Jacques

**Comment by Lawrence37** [comment]
I applied the pp3s from [this comment](https://github.com/Beep6581/RawTherapee/pull/7111#issuecomment-2567187783), but not all the settings were transferred (the sigmoid checkboxes and the contrast in CAM16 mode, for example). It also stays on 5.12 mode instead of switching to 5.11.

File: rtdata/languages/default [hunk 36]
```diff
@@ -1540,9 +1541,9 @@ HISTORY_MSG_LOCAL_CIE_SATCIE;Local - CIECAM Saturation control
 HISTORY_MSG_LOCAL_CIE_SHIFTXL;Local - CIECAM Shift x
 HISTORY_MSG_LOCAL_CIE_SHIFTYL;Local - CIECAM Shift y
 HISTORY_MSG_LOCAL_CIE_SIG;Local - Sigmoid
-HISTORY_MSG_LOCAL_CIE_SIGADAP;Local - CIECAM Sigmoid adaptability
-HISTORY_MSG_LOCAL_CIE_SIGMET;Local - CIECAM Tone mapping Q 
-HISTORY_MSG_LOCAL_CIE_SLOP;Local - CIECAM Slope
+HISTORY_MSG_LOCAL_CIE_SIGADAP;Local - CIECAM  Sigmoid adaptability 5.11
+HISTORY_MSG_LOCAL_CIE_SIGMET;Local - CIECAM  Tone mapping Q 
+HISTORY_MSG_LOCAL_CIE_SLOP;Local - CIECAM  Slope
```
Comment (Lawrence37) [inline rtdata/languages/default]: Are the double spaces intentional?

File: rtdata/languages/default [hunk 37]
```diff
@@ -3552,6 +3567,10 @@ TP_LOCALLAB_PREVIEW;Preview ΔE
 TP_LOCALLAB_PREVSHOW;Show additional settings
 TP_LOCALLAB_PRIMILLFRAME;Primaries & Illuminant
 TP_LOCALLAB_PROXI;ΔE decay
+TP_LOCALLAB_QJMODE;Tone mapping operators Q(Cam16) & J(Jz)
```
Comment (Lawrence37) [inline rtdata/languages/default]: Not specific to this pull request, but in some places I see Cam16 while in other places, I see CAM16.

File: rtdata/languages/default [hunk 38]
```diff
@@ -3552,6 +3567,10 @@ TP_LOCALLAB_PREVIEW;Preview ΔE
 TP_LOCALLAB_PREVSHOW;Show additional settings
 TP_LOCALLAB_PRIMILLFRAME;Primaries & Illuminant
 TP_LOCALLAB_PROXI;ΔE decay
+TP_LOCALLAB_QJMODE;Tone mapping operators Q(Cam16) & J(Jz) 
+TP_LOCALLAB_QJMODE_511;5.11 deprecated
+TP_LOCALLAB_QJMODE_512;5.12
+TP_LOCALLAB_QJMODE_TOOLTIP;(provisional). Allows you to choose, for tone-mapping operators using Brightness data: Q for Cam16 - and J for Jz, between the current (recommended) version 5.12 and previous versions 5.11. This choice is more guided to maintain historical traceability (Feedback), than to ensure software compatibility.
```
Comment (Lawrence37) [inline rtdata/languages/default]: I'm not sure what the last sentence means. I'll wait for Wayne or you can provide a French version and I will try a few translators to see which one makes sense.

File: rtdata/languages/default [hunk 39]
```diff
@@ -3668,25 +3687,31 @@ TP_LOCALLAB_SHTRC_TOOLTIP;Based on 'working profile' (only those provided), modi
...
 TP_LOCALLAB_SIGMOIDBL;Display White point (cd/m2)
+TP_LOCALLAB_SIGMOIDBL11;Blend
 TP_LOCALLAB_SIGMOIDLAMBDA;Contrast
 TP_LOCALLAB_SIGMOIDLOGAUTO;Auto threshold
 TP_LOCALLAB_SIGMOIDLOGEV_TOOLTIP;If the combo box selection 'Black Ev and White Ev' is 'Sigmoid and Log Encoding' instead of 'Sigmoid only', the two algorithms 'Log Encoding' and 'Sigmoid' are used together.
 TP_LOCALLAB_SIGMOIDNORMCIE;Scale Yb Scene
+TP_LOCALLAB_SIGMOIDNORMCIE11;Normalize Luminance
 TP_LOCALLAB_SIGMOIDNORMCIEBLEND_TOOLTIP;Blend acts on the final aspect of the image, contrast and luminance. Ratio between original and output image.
 TP_LOCALLAB_SIGMOIDNORMCIE_TOOLTIP;Reconstruct luminance so that the mean and variance of the output image take into account those of the original.\nAll the adjustments acting on J or Q are taken into account, including those which are not relative to Sigmoid Q.
+TP_LOCALLAB_SIGMOIDNORMCIEDISP_TOOLTIP;(provisional). Adapts the white point to the output device to make it compatible with its peak luminance. This feature is not at the desired location in the pipeline, because it is too far from the final output process. So use with caution.
```
Comment (Lawrence37) [inline rtdata/languages/default]: "provisional" means that the feature is likely to change in the future. Is that what you intended to say?

**Comment by Desmis** [comment]
@Lawrence37 @waynesutton50 

Excuse my very bad english... I hope the translator does not bring any additional misunderstandings.

Lawrence, I think, I'm sure, that we have two totally different conceptions of innovation in the field of experimental software like Cam16 and Jz. I repeat; if you find something else that uses Jz like RT does, I will see to it immediately. I'm not saying you are wrong, and I am true; but I, as the (unique?) designer of these 2 products that are totally experimental and moreover filled with empirical variables to make them work, I maintain my point of view.

It is **illusory to believe** that applying a Cartesian solution (mathematical, computer science or all possible rational terms,...) to something that is "added" (for example Sigmoid), to something else Cam16 or Jz where subjectivity reigns, continual experimentation, the eye/brain couple (physiological: as Simultaneous contrast, Surround, etc.)  the adjustments (both by researchers and by myself), etc. **is something that must see the usual rules applied**.

In a normal case (for example taking the example of Shadows/highlight in 2018, or any other rational algorithm, which often differs by some settings or adjustments...), compatibility must be ensured (or desirable) the user is supposed to find the settings from before. This has been done since the creation of RT by pp3 and the ppversion.h file (even if it is not my strong point to do these updates, and you have already done it several times for me, thank you again for this good cooperation).

In the case of cam16 and Jz - for which I remind you I do not know any software that uses them completely - otherwise:
* an old patch for Photoshop (that I can no longer try on this old computer...no Photoshop), a possible partial use in LCMS2.
* some rare functions included in DT - for example the Cat16 chromatic adaptation (which is only a small part of Ciecam), or rare Jzazbz functions to which the user does not have access directly (at least that's what I saw more than 1 year ago... maybe it has evolved ?)
* ??? perhaps in Python or Javascript (I don't know) ???

The "complete" use of Cam16 and Jz with inverse process, the 6 dimensions Q, J, s, C, M, h , the curves, the symmetric or classical mode, the different chromatic adaptations for the direct and inverse processes, etc. For Jz , I'm not even talking about copying the code somewhere, it doesn't work. All this has led to a pragmatic approach of evolution according to my experiments, my state of health and the progress of other parallel knowledge - like that of Sigmoid or Freeman tone-mapper.

This evolution requires **a lot of humility, especially recognizing that the work I have done for 2 years is not good**, or just acceptable - I do not think that today there is "a solution" that works in 100% of cases. So I recognize my shortcomings (these are not errors or mistakes, but an evolution of my experiments) and I correct them.

In the present case we are talking about, I first strongly opposed maintaining compatibility (I don't like this term here, in this context) and **I voluntarily created a break**, because on the one hand few users use these advances and on the other hand, if they use them they will be able to understand the developments (especially if we have documentation to explain). **The new solution proposed is far from perfect** and in the long term the same problem will arise (if I am still able to do it)

The persistence of your request - that I nevertheless understand - and a concern to preserve the history of Ciecam and Jz led me to modulate my point of view. As I wrote, I made this "compatibility" with regret, because I think it is useless, but in order to keep a trace of what was done "before".

So to get to the practical stuff.
* The preferred **mode in all cases is 5.12** whether it is a new user or an old one who has used 5.11;
* the values ​​of the old 5.11 settings are kept in pp3 (there may be omissions or errors, it's possible... I just checked and it seems to work), except for the default value which remains 5.12. So to avoid the accumulation of functions in the code and end up with anything, I systematically deactivate the checkboxes which enable Sigmoid in 5.11. 

Which is to say (apart from possible code errors, if there are any) that **the behavior of the system corresponds exactly to my wish.**

**The user who has used 5.11 will be systematically offered 5.12. If he wants to try 5.11 out of curiosity, or to see the difference, it will be a voluntary act on his part - choosing 5.11 and activating the corresponding checkbox** - and not an automatic process that will make him ignore the new algorithm. As a reminder, the 2 algorithms are completely different, even if the labels seem identical (contrast), they are different concepts which act on different processes.

**Of course we can change all this, I am not at all in favor** of it, even if it needs to be explained - it would be good to have documentation (When will Rawpedia return?)

Thank you very much for this dialogue

I will check today that everything works correctly, the mixture of the 2 solutions is complex and led me to choices always favoring 5.12. I will make any necessary corrections, or if you find any (or other users..) report them to me - of course by the one I mention and wanted (5.12, checkbox).

I will also change the Tooltip (provisional) and complete it to explain this operation that I recognize as unusual. All this in my bad English...

Jacques

**Comment by Desmis** [comment]
I cleaned up and optimized some of the GUI code a bit.

I checked, rechecked the code and found a **bug in 5.11**, for Sigmoid Q contrast

**I forgot (at the time) a line** in Procparams.cc , for Sigmoid Contrast
                assignFromKeyfile(keyFile, "Locallab", "Sigmoidldacie_" + index_str, spot.sigmoidldacie, spotEdited.sigmoidldacie);

This absence, which no one has noticed for about 1 or 2 years, shows:
* that this part of Cam16- - sigmoid Q - has not been used or has been little used, or used with bug...
* may cause erratic behavior when importing a pp3 profile

Of course it is corrected in the PR

I also changed the Tooltip as previously stated

Jacques

**Comment by Lawrence37** [comment]
To be clear, when I talk about compatibility, my only concern is that when a 5.11 edit is opened in 5.12 **without additional adjustments**, the same result is produced. It doesn't matter to me if the old algorithm is good or bad. If a user likes the results from a bad algorithm, it would be wrong for us to purposely discard (partially or completely) their edit.

Again, the only thing I would like to see is that the 5.11 edits produce the same result on 5.12. You are free to prevent the use of the old algorithms on new edits. You are free to ask users to "upgrade" their 5.11 edits so that they use the new algorithms instead of the old ones. You are free to add even newer algorithms. I do not care if you do or do not do these things.

I will not ask you to hide the new algorithms when an old edit is opened. I will not ask you to make the old algorithms available in all cases. I will not ask you to stop innovating. All I ask is that we do not automatically change a user's edits.

**Comment by Desmis** [comment]
@Lawrence37 
To have "peace" between us, even if I am totally against it - in this case - (and the bug clearly shows that _a priori_ no one or almost no one has used it), I will see what I can do, even if you correct my code with ppversion. But for me, it makes no sense and even the opposite is harmful.

For example, during the "Challenge" in spring 2024, which focused on this Cam16 module, no one used these features  and no one saw that there were bugs,, and yet 6 users who cannot be described as "amateurs" tested Cam16 and SDA for more than 1 month...

Cordially.

Jacques

File: rtdata/languages/default (hunk 36 above)
Comment (Desmis) [reply rtdata/languages/default]: No, I will change

File: rtdata/languages/default (hunk 39 above)
Comment (Desmis) [reply rtdata/languages/default]: Yes... 
Provisional - first because Wayne offered to translate it well.

**Comment by Desmis** [comment]
@Lawrence37 @waynesutton50 

As agreed, and even if I think it's a mistake, I changed "procparams.cc" taking into account  "ppversion < 352"

Three groups of variables are concerned:
* logcieq - which allowed in 5.11 to have the Brightness Q version of Log encoding (in the loop Ciecam)
* sigq - which allowed in 5.11 - for Brightness Q (in the loop Ciecam), to use the old Sigmoid Q algorithm
* sigjz - which allowed in 5.11 - for Brightness J (in JzCzHz), to use the old Sigmoid J algorithm

I tested with the 2 pp3 files you attached "Cam16.pp3"  and "Jzazbz.pp3". It seems to work. But as these manipulations are not my strong point, you can check and modify if necessary.

I also changed the ModeQJ toolip which no longer has any reason to exist in its old form.

Cordially

Jacques

File: rtdata/languages/default (hunk 37 above)
Comment (Desmis) [reply rtdata/languages/default]: I replace CAM16 and CAM02 with Cam16 and Cam02

File: rtdata/languages/default (hunk 38 above)
Comment (Desmis) [reply rtdata/languages/default]: This question is no longer meaningful, since there is now compatibility with 5.11. Otherwise, it is better to choose 5.12.

**Comment by Lawrence37** [comment]
Thanks, I confirm the pp3s result in the same output between 5.11 and this PR.

I assure you that this is not a mistake. Here's why. There are two possible scenarios when someone opens an old edit. First, they are fine with what the old algorithm did. In this scenario, there is no point in forcing them to use a different algorithm because the results are already satisfactory. Second, they want to tweak the edit or start fresh. In this scenario, the processing parameters have changed. Backward compatibility is no longer relevant. You are free to prevent them from going back to the old algorithms. There is no disagreement between us because my only concern is the backward compatibility.

So really, only the first scenario restricts what you can do, and I doubt anyone can come up with a good argument why a user isn't actually satisfied with an edit whey they think they are satisfied.

**Comment by Desmis** [comment]
@Lawrence37 @waynesutton50 

OK, thank you, this confirms that I was not mistaken...

I am waiting, today or tomorrow, for comments on Laels and Tooltips from Wayne

Then I think you will agree to "merge" with dev?  (I hope)

Thank you

Jacques

**Comment by waynesutton50** [comment]
@Desmis Jacques, In the “Cam16” CAM model the tooltip TP_LOCALLAB_QJMODE_TOOLTIP __Vous permet de choisir, pour les opérateurs tone-mapping utilisant les données Brightness : Q pour Cam16 - et J pour Jz, entre la version courante (recommandée) 5.12 et les versions antérieures 5.11.__
implies that there are changes in the behaviour of the “Tone mapping operators *” further down in the menu (just under the TRC)  , however after playing around with the settings, I suspect that it refers in fact to the Sigmoid Q/ Sigmoid Q & Slope based menus just prior to Viewing Conditions. Is this the case?
A few other remarks not related to the tooltip.

- in the JzCzHz CAM model mode the tone mappers are in the Scene Conditions menu whereas in the “Cam 16” mode they are in Source Data Adjustments menu (which doesn’t exist in the JzCzHz mode). Should there be consistency between the Cam16 and JzCzHz menus? 
- if you check the Log Encoding Jz checkbox and switch between 5.11 and 5.12, the box stays checked which is not the case if you check the Sigmoid Jz checkbox and change between 5.11 and 5.12. 
- I’m not sure that it's necessary to differentiate the 5.11 and 5.12 Sigmoid Jz labels with an asterisk (same remark for "Tone mapping operators*".
- There are a few inconsistencies in the use of sentence case for some of the sliders. e.g. Hue Rotation should be “Hue rotation” and Threshold Chroma should be “Threshold chroma”. 
- You could maybe shorten the "Log Encoding Q - with CIECAM - Deprecated" label to "Log Encoding Q with CIECAM (deprecated)"

**Comment by Desmis** [comment]
@waynesutton50 
Thanks for these comments, I will answer you more precisely tomorrow.

It is obvious that this "addition" of 5.11 compatibility with different algorithms is not easy to explain in a tooltip.

 For **Cam16, for Sigmoid** this only concerns the **Sigmoid Q** part "in the Ciecam loop" -**Cam16 Image Adjustments** 
* with 5.11  => Sigmoid Q - deprecated
* with 5.12 ==> Sigmoid Q & Slope based

**The 2 Sigmoid algorithms are different**

The new part brought since 5.12 in SDA remains the same (5.11 or 5.12) with the menu "Tone mapping operators *" with choices : none, Ev based, Gamma based, Slope based, RGB channel slope, Sigmoid Based . **Sigmoid base has been added with 5.12** but is not affected by the tooltip

For **Cam16  and Log encoding in SDA** (Source Data Adjustments) version 5.11 is seen with one more choice: 
**Log encodind Q** - with Ciecam - Deprecated - **which was removed in 5.12, as unreliable**

For JzCzHz the difference is only Sigmoid Jz in "Scene conditions" - the algorithms and settings are **different**

I have taken note of your remarks and thank you for them and will continue tomorrow morning.

Jacques

**Comment by Lawrence37** [comment]
@Desmis There is one comment I made about using a unique pointer. Let me know when I can push the code to address the comment.

**Comment by Desmis** [comment]
@waynesutton50 
In french : la phrase du tooltip pourrait s'enrichir des commentaires suivants. Tu peux adapter - aussi bien le français, que évidemment l'anglais

====
Vous permet de choisir, pour les opérateurs tone-mapping utilisant les données Brightness : Q pour Cam16 - et J pour Jz, entre la version courante (recommandée) 5.12 et les versions antérieures 5.11 (obsolètes). Ces versions sont incompatibles entre elles.
* pour Cam16 les procédures concernées sont :
** dans Cam16 Image Adjustments, pour Sigmoid Q : Sigmoid Q & Slope based pour 5.12, et Sigmoid Q (deprecated) pour 5.11. 
** dans Source Data Adjustments, pour Log Encoding Q, une case à cocher Log encoding Q with CIECAM (deprecated), n'apparaît que pour 5.11

* pour JzCzHz , les procédures concernées sont dans Scene Conditions : Sigmoid Jz pour 5.12 et Sigmoid Jz (deprecated) pour 5.11

Les autres variables et fonctions dans Cam16, situées dans Source Data Adjustments : Log Encoding ou Tone mapping operators utilisent toutes les données RGB.


=====

> * if you check the Log Encoding Jz checkbox and switch between 5.11 and 5.12, the box stays checked which is not the case if you check the Sigmoid Jz checkbox and change between 5.11 and 5.12.

Log encoding Jz is not concerned by this change, only Sigmoid Jz

> * Should there be consistency between the Cam16 and JzCzHz menus?

I don't think so. Cam16 is a real CAM (Color Appearance Model), which JzCzHz is not.
I think we used the term "Source Data Adjustments" together to get the idea of ​​a process upstream of Cam16 Image adjustments, but which is not exactly "Scene conditions".
In the case of JzCzHz, we are well upstream of the main process and even if JzCzHz is not a CAM, I have assigned it CAM functions, like Scene conditions, and Surround.
So I think it is correct (or acceptable depending on what we perceive)


**I made the changes you suggested** and harmonized in the "deprecated" Labels by putting it in parentheses. (deprecated)

In French
Reste la traduction et/ou la compréhension du tooltip relatif à Display White point (cd/m2) 
TP_LOCALLAB_SIGMOIDNORMCIEDISP_TOOLTIP;(provisional).
“Adapte le point blanc à destination du périphérique de sortie pour le rendre compatible avec son pic de luminance. Cette fonctionnalité, n’est pas à l’endroit souhaité du pipe-line, car trop éloigné du processus output final. Donc à utiliser avec précautions”.

Ce slider ménage l'avenir, il suppose un moniteur HDR (ou très performant). Malheureusement actuellement, les profils de sortie vers les moniteurs  - au moins ceux présents dans RT - sont en Lab 8 bits, donc incapables d'utiliser pleinement ces données. On peut dire la même chose en grande partie pour le module JzCzHz


Thank you

Jacques

**Comment by waynesutton50** [comment]
@Desmis @Lawrence37 
Here are the suggested translations for the two tooltips. I'd recommend putting the additional comments and recommendations in the documentation to keep the tooltips relatively short. 

TP_LOCALLAB_QJMODE_TOOLTIP;The tone-mapping operators that use brightness data (Q for CAM 16 and J for Jz) have been modified in RawTherapee version 5.12. This allows you to select either the current or the deprecated version. 

TP_LOCALLAB_SIGMOIDNORMCIEDISP_TOOLTIP;Allows you to adapt the white point to the peak luminance of the display device. Its position in the processing pipeline is not optimal so use with caution.

**Comment by Desmis** [comment]
@waynesutton50 

Thank you, I will update this afternoon :)

Jacques

**Comment by Desmis** [comment]
@Lawrence37 

No problem, you can push your change about using a unique pointer.

:)

Jacques

**Comment by Lawrence37** [comment]
@Desmis I added the commit.

File: rtdata/languages/default [hunk 40]
```diff
@@ -3571,7 +3571,7 @@ TP_LOCALLAB_PROXI;ΔE decay
 TP_LOCALLAB_QJMODE;Tone mapping operators Q(Cam16) & J(Jz) 
 TP_LOCALLAB_QJMODE_511;5.11 deprecated
 TP_LOCALLAB_QJMODE_512;5.12
-TP_LOCALLAB_QJMODE_TOOLTIP;(provisional). Allows you to choose, for tone-mapping operators using Brightness data: Q for Cam16 - and J for Jz, between the current (recommended) version 5.12 and previous versions 5.11.
+TP_LOCALLAB_QJMODE_TOOLTIP;The tone-mapping operators that use brightness data (Q for CAM 16 and J for Jz) have been modified in RawTherapee version 5.12. This allows you to select either the current or the deprecated version.
```
Comment (Lawrence37) [inline rtdata/languages/default]:
```suggestion
TP_LOCALLAB_QJMODE_TOOLTIP;The tone-mapping operators that use brightness data (Q for Cam16 and J for Jz) have been modified in RawTherapee version 5.12. This allows you to select either the current or the deprecated version.
```
This should be Cam16, correct?

Comment (Desmis) [reply rtdata/languages/default]: I prefer to stay with Cam16, even if the habits (if there are any) should be CAM16.
On the one hand, Cam16 is more readable and more concise, and on the other hand, this difference reflects the important changes I made to Ciecam, to make it work.
So CAM16 may be an unofficial reference, and Cam16 becomes the Rawtherapee specific version.
Jacques

Comment (waynesutton50) [reply rtdata/languages/default]: The official CIE acronym is CAM16 (without the space - my error). https://cie.co.at/publications/cie-2016-colour-appearance-model-colour-management-systems-ciecam16

**Comment by Desmis** [comment]
@Lawrence37 
After thinking, I changed in RT all the terms Cam16 and Cam02 to CAM16 and CAM02, to respect the standards, even if the modifications made at the algorithm level mean that it is not CAM16

I also tried to better take into account the recommendations of Rawpedia (allways down) for respecting uppercase (U) and lowercase (L) in Frames, checkboxes, etc. I also tried in these modifications to update the tooltips with these same modifications. But nothing is perfect.

I don't think I have to make any more changes to this PR

My computer returned from repair after a power surge (motherboad burned) is working very poorly, I returned it to the manufacturer, and so I am still with my (very) old machine

Jacques

**Comment by Desmis** [comment]
I think, after this big review on Labels, tooltips, convention, etc. that I finished

**Review by Lawrence37 — APPROVED** [review]

**Comment by Desmis** [comment]
@Lawrence37 

OK thank you.

I will merge soon :)
