### PR TITLE
Adopt Exiv2 for metadata handling

### LINKED ISSUE #5361: Exif support for Xiaomi Redmi Note 7 DNG
Please add support for Xiaomi Redmi Note 7 in RawTherapee.
I uploaded to https://raw.pixls.us/ an unmodified DNG/raw photo (file: IMG_20190615_155524.dng) taken with latest OpenCamera on RN7. The phone firmware is unmodified (official global ROM, MIUI 10.3.4 based on Android 9). I can upload more raw files with corresponding JPGs if there is a need for them (OpenCamera takes JPG/DNG at once), just let me know.
Thank you very much.
Regards,

### LINKED ISSUE #6248: CR3 metadata decoding support
Continuation from #5319

### LINKED ISSUE #6291: Lenses not being picked up correctly when used with Nikon Z series bodies.
First of all: I'm not sure how much of this is a lensfun issue and as such cannot be dealt with by the RawTherapee team. Just putting this out here just in case there is a RT part that can/needs to be fixed.

**Short description**
RawTherapee reports/uses the wrong lens info when using F-mount lenses on a Nikon Z6 II body.

**Expected behaviour**
Lenses to be picked up correctly by the _Profiled Lens Correction_ section.

**Additional information**
I have 4 Nikkor lenses, all of them are in the lesnfun database and they are picked up correctly by RT when using my Nikon D750 and incorrectly when using them on the Nikon Z6 II. (1 shows the wrong info in the Quick Info pop-up only).

When looking at RT's Lens Profile section I notice that the _Camera_ field is empty when choosing auto select. Reason being: The Nikon Z6 II isn't yet part of lensfun (see lensfun's [PR #1371](https://github.com/lensfun/lensfun/issues/1371)). It is present in RT's camconst.json file.

I thought that that might have been the problem, but manually adding this Z6 II info to lensfun's mil-nikon.xml doesn't solve the problem:

* The camera is picked up correctly after the manual add and the field is no longer empty.
*  The lens info is still wrong though.

**Screenshots**

Correct lens info would be:
d75

When using the same lens on the Z6 II:
z62

---
Before adding a lot of lens specific info, RAW examples and maybe other needed info I need to know if this is a RT issue or not.

If it is, please tell me which info I need to provide.

### LINKED ISSUE #6666: Profiled Lens correction for Nikon AF-S 24-85mm Lenses: Lens not detected automatically
Hello,

I just picked up a "new" lens for my D610. 

It is this one: https://www.nikon.de/de_DE/product/nikkor-lenses/auto-focus-lenses/fx/zoom/af-s-nikkor-24-85mm-f-3-5-4-5g-ed-vr

Usually I was used to automatic lens correction in RT to be working, but not with this lens.

When I dug further I found profiles for two similar sounding lens names

- Nikon AF-S Nikkor 24-85 mm f/3.5-4.5G ED VR
- Nikon AF-S Zoom-Nikkor 24-85mm f/3.5-4.5G IF-ED

However in the EXIF data my lens is shown as: 
- Lens ID 	 AF-S Zoom-Nikkor 24-85mm f/3.5-4.5G IF-ED VR

Note that this is different to both entries, so obviously it matches none of the two above entries. I suspect both entries are intended for the same lens, but the lens corrections are different. Probably because one of the entries is much more detailed.

It would be cool if we could:
- figure out why there are 2 entries and if one of them is redundant and can be removed
- rename the entry so it gets detected correctly (maybe add aliases)

If needed I can provide example pictures in NEF and JPG format.

Edit:

As a workaround I copied the entry from Nikon AF-S Nikkor 24-85 mm f/3.5-4.5G ED VR and renamed it to AF-S Zoom-Nikkor 24-85mm f/3.5-4.5G IF-ED VR in the srl-nikon.xml and now the automatic detection correctly selects the lens correction profile.

### LINKED ISSUE #6733: Memory leak in rtexif (Canon CR2)
**Short description**
RawTherapee leak memory in rtexif processing Canon CR2

**Steps to reproduce**
1. Build RawTherapee with WITH_ASAN=address
2. Most Canon CR2 file will work. But https://raw.pixls.us/getfile.php/1682/nice/Canon%20-%20PowerShot%20G7%20X%20Mark%20II%20-%20RAW%20(3:2).CR2 is know to reproduce (Canon G7 X Mark II)
3. Run `./_build/rtgui/rawtherapee-cli -d -Y -c Canon\ -\ PowerShot\ G7\ X\ Mark\ II\ -\ RAW\ \(3:2\).CR2`
4. Libasan report memory leaks

The "Indirect Leak" are probably because of the self reference as there is no corresponding "Direct Leak"

**Expected behavior**
No leak

**Additional information**

Fedora 36

```
Version: 5.9-126-gca08a279d
Branch: dev
Commit: ca08a279d
Commit date: 2023-03-10
Compiler: cc 12.2.1
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.6
Lensfun: V0.3.3.0
Build type: Debug
Build flags:  -std=c++11 -ffp-contract=off  -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -fsanitize=address -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -g -ftree-vectorize
Link flags:   -fsanitize=address
OpenMP support: ON
MMAP support: ON
Build OS: Linux 6.2.7-200.fc37.x86_64 x86_64
Build date: Sat, 01 Apr 2023 04:24:41 +0000 UTC
Build epoch: 1680323081
Build UUID: 5b7d167b-658f-4e52-b790-82cc04261589
```

Here is the full output:

```
=================================================================
==784600==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 3752 byte(s) in 1 object(s) allocated from:
    #0 0x7f23668ba6af in __interceptor_malloc (/lib64/libasan.so.8+0xba6af)
    #1 0x7f2365eb019b in _cmsMallocZeroDefaultFn (/lib64/liblcms2.so.2+0x1419b)

Direct leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x7f23668b95b5 in __interceptor_realloc.part.0 (/lib64/libasan.so.8+0xb95b5)
    #1 0x7f2365f5c4cf in g_realloc (/lib64/libglib-2.0.so.0+0x5a4cf)

Indirect leak of 1492 byte(s) in 26 object(s) allocated from:
    #0 0x7f23668ba6af in __interceptor_malloc (/lib64/libasan.so.8+0xba6af)
    #1 0x7f2365eb019b in _cmsMallocZeroDefaultFn (/lib64/liblcms2.so.2+0x1419b)

Indirect leak of 180 byte(s) in 2 object(s) allocated from:
    #0 0x7f23668ba6af in __interceptor_malloc (/lib64/libasan.so.8+0xba6af)
    #1 0x7f2365ecc5a7 in cmsMLUdup (/lib64/liblcms2.so.2+0x305a7)

Indirect leak of 128 byte(s) in 2 object(s) allocated from:
    #0 0x7f23668bb1a8 in operator new(unsigned long) (/lib64/libasan.so.8+0xbb1a8)
    #1 0x1490c5e in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #2 0x149ed08 in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1243
    #3 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #4 0x14ae8b2 in rtexif::ExifManager::parse(bool, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:2836
    #5 0x14b191b in rtexif::ExifManager::parseJPEG(int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:3199
    #6 0x149b4c3 in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:988
    #7 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #8 0x14a003c in rtexif::Tag::parseMakerNote(_IO_FILE*, int, rtexif::ByteOrder) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1310
    #9 0x149b8de in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1007
    #10 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #11 0x149ed08 in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1243
    #12 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #13 0x14ae8b2 in rtexif::ExifManager::parse(bool, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:2836
    #14 0x14ae17e in rtexif::ExifManager::parseRaw(bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:2800
    #15 0xdceece in rtengine::FramesData::FramesData(Glib::ustring const&, std::unique_ptr<rtengine::RawMetaDataLocation, std::default_delete<rtengine::RawMetaDataLocation> >, bool) /var/home/hub/source/RawTherapee/rtengine/imagedata.cc:1395
    #16 0x87e9d6 in rtengine::RawImageSource::load(Glib::ustring const&, bool) /var/home/hub/source/RawTherapee/rtengine/rawimagesource.cc:1343
    #17 0x8edd57 in rtengine::RawImageSource::load(Glib::ustring const&) (/var/home/hub/source/RawTherapee/_build/rtgui/rawtherapee-cli+0x8edd57)
    #18 0x5cfcc4 in rtengine::InitialImage::load(Glib::ustring const&, bool, int*, rtengine::ProgressListener*) /var/home/hub/source/RawTherapee/rtengine/loadinitial.cc:39
    #19 0x4175e9 in processLineParams(int, char**) /var/home/hub/source/RawTherapee/rtgui/main-cli.cc:733
    #20 0x41156c in main /var/home/hub/source/RawTherapee/rtgui/main-cli.cc:221
    #21 0x7f2364a2950f in __libc_start_call_main (/lib64/libc.so.6+0x2950f)

Indirect leak of 72 byte(s) in 1 object(s) allocated from:
    #0 0x7f23668ba6af in __interceptor_malloc (/lib64/libasan.so.8+0xba6af)
    #1 0x7f2365eb01df in _cmsDupDefaultFn (/lib64/liblcms2.so.2+0x141df)
    #2 0xbc987fffffffffff  (<unknown module>)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f23668bb1a8 in operator new(unsigned long) (/lib64/libasan.so.8+0xbb1a8)
    #1 0x14b02df in rtexif::ExifManager::parse(bool, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:3069
    #2 0x14b191b in rtexif::ExifManager::parseJPEG(int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:3199
    #3 0x149b4c3 in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:988
    #4 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #5 0x14a003c in rtexif::Tag::parseMakerNote(_IO_FILE*, int, rtexif::ByteOrder) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1310
    #6 0x149b8de in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1007
    #7 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #8 0x149ed08 in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1243
    #9 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #10 0x14ae8b2 in rtexif::ExifManager::parse(bool, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:2836
    #11 0x14ae17e in rtexif::ExifManager::parseRaw(bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:2800
    #12 0xdceece in rtengine::FramesData::FramesData(Glib::ustring const&, std::unique_ptr<rtengine::RawMetaDataLocation, std::default_delete<rtengine::RawMetaDataLocation> >, bool) /var/home/hub/source/RawTherapee/rtengine/imagedata.cc:1395
    #13 0x87e9d6 in rtengine::RawImageSource::load(Glib::ustring const&, bool) /var/home/hub/source/RawTherapee/rtengine/rawimagesource.cc:1343
    #14 0x8edd57 in rtengine::RawImageSource::load(Glib::ustring const&) (/var/home/hub/source/RawTherapee/_build/rtgui/rawtherapee-cli+0x8edd57)
    #15 0x5cfcc4 in rtengine::InitialImage::load(Glib::ustring const&, bool, int*, rtengine::ProgressListener*) /var/home/hub/source/RawTherapee/rtengine/loadinitial.cc:39
    #16 0x4175e9 in processLineParams(int, char**) /var/home/hub/source/RawTherapee/rtgui/main-cli.cc:733
    #17 0x41156c in main /var/home/hub/source/RawTherapee/rtgui/main-cli.cc:221
    #18 0x7f2364a2950f in __libc_start_call_main (/lib64/libc.so.6+0x2950f)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f23668bb1a8 in operator new(unsigned long) (/lib64/libasan.so.8+0xbb1a8)
    #1 0x149ec0e in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1243
    #2 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #3 0x14ae8b2 in rtexif::ExifManager::parse(bool, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:2836
    #4 0x14b191b in rtexif::ExifManager::parseJPEG(int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:3199
    #5 0x149b4c3 in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:988
    #6 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #7 0x14a003c in rtexif::Tag::parseMakerNote(_IO_FILE*, int, rtexif::ByteOrder) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1310
    #8 0x149b8de in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1007
    #9 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #10 0x149ed08 in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1243
    #11 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #12 0x14ae8b2 in rtexif::ExifManager::parse(bool, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:2836
    #13 0x14ae17e in rtexif::ExifManager::parseRaw(bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:2800
    #14 0xdceece in rtengine::FramesData::FramesData(Glib::ustring const&, std::unique_ptr<rtengine::RawMetaDataLocation, std::default_delete<rtengine::RawMetaDataLocation> >, bool) /var/home/hub/source/RawTherapee/rtengine/imagedata.cc:1395
    #15 0x87e9d6 in rtengine::RawImageSource::load(Glib::ustring const&, bool) /var/home/hub/source/RawTherapee/rtengine/rawimagesource.cc:1343
    #16 0x8edd57 in rtengine::RawImageSource::load(Glib::ustring const&) (/var/home/hub/source/RawTherapee/_build/rtgui/rawtherapee-cli+0x8edd57)
    #17 0x5cfcc4 in rtengine::InitialImage::load(Glib::ustring const&, bool, int*, rtengine::ProgressListener*) /var/home/hub/source/RawTherapee/rtengine/loadinitial.cc:39
    #18 0x4175e9 in processLineParams(int, char**) /var/home/hub/source/RawTherapee/rtgui/main-cli.cc:733
    #19 0x41156c in main /var/home/hub/source/RawTherapee/rtgui/main-cli.cc:221
    #20 0x7f2364a2950f in __libc_start_call_main (/lib64/libc.so.6+0x2950f)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f23668bb1a8 in operator new(unsigned long) (/lib64/libasan.so.8+0xbb1a8)
    #1 0x1490c5e in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #2 0x14ae8b2 in rtexif::ExifManager::parse(bool, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:2836
    #3 0x14b191b in rtexif::ExifManager::parseJPEG(int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:3199
    #4 0x149b4c3 in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:988
    #5 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #6 0x14a003c in rtexif::Tag::parseMakerNote(_IO_FILE*, int, rtexif::ByteOrder) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1310
    #7 0x149b8de in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1007
    #8 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #9 0x149ed08 in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1243
    #10 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #11 0x14ae8b2 in rtexif::ExifManager::parse(bool, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:2836
    #12 0x14ae17e in rtexif::ExifManager::parseRaw(bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:2800
    #13 0xdceece in rtengine::FramesData::FramesData(Glib::ustring const&, std::unique_ptr<rtengine::RawMetaDataLocation, std::default_delete<rtengine::RawMetaDataLocation> >, bool) /var/home/hub/source/RawTherapee/rtengine/imagedata.cc:1395
    #14 0x87e9d6 in rtengine::RawImageSource::load(Glib::ustring const&, bool) /var/home/hub/source/RawTherapee/rtengine/rawimagesource.cc:1343
    #15 0x8edd57 in rtengine::RawImageSource::load(Glib::ustring const&) (/var/home/hub/source/RawTherapee/_build/rtgui/rawtherapee-cli+0x8edd57)
    #16 0x5cfcc4 in rtengine::InitialImage::load(Glib::ustring const&, bool, int*, rtengine::ProgressListener*) /var/home/hub/source/RawTherapee/rtengine/loadinitial.cc:39
    #17 0x4175e9 in processLineParams(int, char**) /var/home/hub/source/RawTherapee/rtgui/main-cli.cc:733
    #18 0x41156c in main /var/home/hub/source/RawTherapee/rtgui/main-cli.cc:221
    #19 0x7f2364a2950f in __libc_start_call_main (/lib64/libc.so.6+0x2950f)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f23668bb1a8 in operator new(unsigned long) (/lib64/libasan.so.8+0xbb1a8)
    #1 0x14ae79a in rtexif::ExifManager::parse(bool, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:2836
    #2 0x14b191b in rtexif::ExifManager::parseJPEG(int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:3199
    #3 0x149b4c3 in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:988
    #4 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #5 0x14a003c in rtexif::Tag::parseMakerNote(_IO_FILE*, int, rtexif::ByteOrder) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1310
    #6 0x149b8de in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1007
    #7 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #8 0x149ed08 in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1243
    #9 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #10 0x14ae8b2 in rtexif::ExifManager::parse(bool, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:2836
    #11 0x14ae17e in rtexif::ExifManager::parseRaw(bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:2800
    #12 0xdceece in rtengine::FramesData::FramesData(Glib::ustring const&, std::unique_ptr<rtengine::RawMetaDataLocation, std::default_delete<rtengine::RawMetaDataLocation> >, bool) /var/home/hub/source/RawTherapee/rtengine/imagedata.cc:1395
    #13 0x87e9d6 in rtengine::RawImageSource::load(Glib::ustring const&, bool) /var/home/hub/source/RawTherapee/rtengine/rawimagesource.cc:1343
    #14 0x8edd57 in rtengine::RawImageSource::load(Glib::ustring const&) (/var/home/hub/source/RawTherapee/_build/rtgui/rawtherapee-cli+0x8edd57)
    #15 0x5cfcc4 in rtengine::InitialImage::load(Glib::ustring const&, bool, int*, rtengine::ProgressListener*) /var/home/hub/source/RawTherapee/rtengine/loadinitial.cc:39
    #16 0x4175e9 in processLineParams(int, char**) /var/home/hub/source/RawTherapee/rtgui/main-cli.cc:733
    #17 0x41156c in main /var/home/hub/source/RawTherapee/rtgui/main-cli.cc:221
    #18 0x7f2364a2950f in __libc_start_call_main (/lib64/libc.so.6+0x2950f)

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x7f23668ba6af in __interceptor_malloc (/lib64/libasan.so.8+0xba6af)
    #1 0x7f2365eb022e in defMtxCreate.lto_priv.0 (/lib64/liblcms2.so.2+0x1422e)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7f23668ba6af in __interceptor_malloc (/lib64/libasan.so.8+0xba6af)
    #1 0x7f2365eb01df in _cmsDupDefaultFn (/lib64/liblcms2.so.2+0x141df)

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7f23668bb1a8 in operator new(unsigned long) (/lib64/libasan.so.8+0xbb1a8)
    #1 0x14befef in std::__new_allocator<rtexif::Tag*>::allocate(unsigned long, void const*) /usr/include/c++/12/bits/new_allocator.h:137
    #2 0x14bd6a3 in std::allocator_traits<std::allocator<rtexif::Tag*> >::allocate(std::allocator<rtexif::Tag*>&, unsigned long) /usr/include/c++/12/bits/alloc_traits.h:464
    #3 0x14bab03 in std::_Vector_base<rtexif::Tag*, std::allocator<rtexif::Tag*> >::_M_allocate(unsigned long) /usr/include/c++/12/bits/stl_vector.h:378
    #4 0x14b8926 in void std::vector<rtexif::Tag*, std::allocator<rtexif::Tag*> >::_M_realloc_insert<rtexif::Tag* const&>(__gnu_cxx::__normal_iterator<rtexif::Tag**, std::vector<rtexif::Tag*, std::allocator<rtexif::Tag*> > >, rtexif::Tag* const&) /usr/include/c++/12/bits/vector.tcc:453
    #5 0x14b6a26 in std::vector<rtexif::Tag*, std::allocator<rtexif::Tag*> >::push_back(rtexif::Tag* const&) /usr/include/c++/12/bits/stl_vector.h:1287
    #6 0x149567e in rtexif::TagDirectory::addTag(rtexif::Tag*&) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:376
    #7 0x14b03e8 in rtexif::ExifManager::parse(bool, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:3071
    #8 0x14b191b in rtexif::ExifManager::parseJPEG(int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:3199
    #9 0x149b4c3 in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:988
    #10 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #11 0x14a003c in rtexif::Tag::parseMakerNote(_IO_FILE*, int, rtexif::ByteOrder) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1310
    #12 0x149b8de in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1007
    #13 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #14 0x149ed08 in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1243
    #15 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #16 0x14ae8b2 in rtexif::ExifManager::parse(bool, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:2836
    #17 0x14ae17e in rtexif::ExifManager::parseRaw(bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:2800
    #18 0xdceece in rtengine::FramesData::FramesData(Glib::ustring const&, std::unique_ptr<rtengine::RawMetaDataLocation, std::default_delete<rtengine::RawMetaDataLocation> >, bool) /var/home/hub/source/RawTherapee/rtengine/imagedata.cc:1395
    #19 0x87e9d6 in rtengine::RawImageSource::load(Glib::ustring const&, bool) /var/home/hub/source/RawTherapee/rtengine/rawimagesource.cc:1343
    #20 0x8edd57 in rtengine::RawImageSource::load(Glib::ustring const&) (/var/home/hub/source/RawTherapee/_build/rtgui/rawtherapee-cli+0x8edd57)
    #21 0x5cfcc4 in rtengine::InitialImage::load(Glib::ustring const&, bool, int*, rtengine::ProgressListener*) /var/home/hub/source/RawTherapee/rtengine/loadinitial.cc:39
    #22 0x4175e9 in processLineParams(int, char**) /var/home/hub/source/RawTherapee/rtgui/main-cli.cc:733
    #23 0x41156c in main /var/home/hub/source/RawTherapee/rtgui/main-cli.cc:221
    #24 0x7f2364a2950f in __libc_start_call_main (/lib64/libc.so.6+0x2950f)

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7f23668bb308 in operator new[](unsigned long) (/lib64/libasan.so.8+0xbb308)
    #1 0x149eb57 in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1237
    #2 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #3 0x14ae8b2 in rtexif::ExifManager::parse(bool, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:2836
    #4 0x14b191b in rtexif::ExifManager::parseJPEG(int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:3199
    #5 0x149b4c3 in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:988
    #6 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #7 0x14a003c in rtexif::Tag::parseMakerNote(_IO_FILE*, int, rtexif::ByteOrder) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1310
    #8 0x149b8de in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1007
    #9 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #10 0x149ed08 in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1243
    #11 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #12 0x14ae8b2 in rtexif::ExifManager::parse(bool, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:2836
    #13 0x14ae17e in rtexif::ExifManager::parseRaw(bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:2800
    #14 0xdceece in rtengine::FramesData::FramesData(Glib::ustring const&, std::unique_ptr<rtengine::RawMetaDataLocation, std::default_delete<rtengine::RawMetaDataLocation> >, bool) /var/home/hub/source/RawTherapee/rtengine/imagedata.cc:1395
    #15 0x87e9d6 in rtengine::RawImageSource::load(Glib::ustring const&, bool) /var/home/hub/source/RawTherapee/rtengine/rawimagesource.cc:1343
    #16 0x8edd57 in rtengine::RawImageSource::load(Glib::ustring const&) (/var/home/hub/source/RawTherapee/_build/rtgui/rawtherapee-cli+0x8edd57)
    #17 0x5cfcc4 in rtengine::InitialImage::load(Glib::ustring const&, bool, int*, rtengine::ProgressListener*) /var/home/hub/source/RawTherapee/rtengine/loadinitial.cc:39
    #18 0x4175e9 in processLineParams(int, char**) /var/home/hub/source/RawTherapee/rtgui/main-cli.cc:733
    #19 0x41156c in main /var/home/hub/source/RawTherapee/rtgui/main-cli.cc:221
    #20 0x7f2364a2950f in __libc_start_call_main (/lib64/libc.so.6+0x2950f)

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7f23668bb1a8 in operator new(unsigned long) (/lib64/libasan.so.8+0xbb1a8)
    #1 0x14befef in std::__new_allocator<rtexif::Tag*>::allocate(unsigned long, void const*) /usr/include/c++/12/bits/new_allocator.h:137
    #2 0x14bd6a3 in std::allocator_traits<std::allocator<rtexif::Tag*> >::allocate(std::allocator<rtexif::Tag*>&, unsigned long) /usr/include/c++/12/bits/alloc_traits.h:464
    #3 0x14bab03 in std::_Vector_base<rtexif::Tag*, std::allocator<rtexif::Tag*> >::_M_allocate(unsigned long) /usr/include/c++/12/bits/stl_vector.h:378
    #4 0x14b8926 in void std::vector<rtexif::Tag*, std::allocator<rtexif::Tag*> >::_M_realloc_insert<rtexif::Tag* const&>(__gnu_cxx::__normal_iterator<rtexif::Tag**, std::vector<rtexif::Tag*, std::allocator<rtexif::Tag*> > >, rtexif::Tag* const&) /usr/include/c++/12/bits/vector.tcc:453
    #5 0x14b6a26 in std::vector<rtexif::Tag*, std::allocator<rtexif::Tag*> >::push_back(rtexif::Tag* const&) /usr/include/c++/12/bits/stl_vector.h:1287
    #6 0x149567e in rtexif::TagDirectory::addTag(rtexif::Tag*&) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:376
    #7 0x1490e99 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:97
    #8 0x149ed08 in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1243
    #9 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #10 0x14ae8b2 in rtexif::ExifManager::parse(bool, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:2836
    #11 0x14b191b in rtexif::ExifManager::parseJPEG(int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:3199
    #12 0x149b4c3 in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:988
    #13 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #14 0x14a003c in rtexif::Tag::parseMakerNote(_IO_FILE*, int, rtexif::ByteOrder) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1310
    #15 0x149b8de in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1007
    #16 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #17 0x149ed08 in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1243
    #18 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #19 0x14ae8b2 in rtexif::ExifManager::parse(bool, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:2836
    #20 0x14ae17e in rtexif::ExifManager::parseRaw(bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:2800
    #21 0xdceece in rtengine::FramesData::FramesData(Glib::ustring const&, std::unique_ptr<rtengine::RawMetaDataLocation, std::default_delete<rtengine::RawMetaDataLocation> >, bool) /var/home/hub/source/RawTherapee/rtengine/imagedata.cc:1395
    #22 0x87e9d6 in rtengine::RawImageSource::load(Glib::ustring const&, bool) /var/home/hub/source/RawTherapee/rtengine/rawimagesource.cc:1343
    #23 0x8edd57 in rtengine::RawImageSource::load(Glib::ustring const&) (/var/home/hub/source/RawTherapee/_build/rtgui/rawtherapee-cli+0x8edd57)
    #24 0x5cfcc4 in rtengine::InitialImage::load(Glib::ustring const&, bool, int*, rtengine::ProgressListener*) /var/home/hub/source/RawTherapee/rtengine/loadinitial.cc:39
    #25 0x4175e9 in processLineParams(int, char**) /var/home/hub/source/RawTherapee/rtgui/main-cli.cc:733
    #26 0x41156c in main /var/home/hub/source/RawTherapee/rtgui/main-cli.cc:221
    #27 0x7f2364a2950f in __libc_start_call_main (/lib64/libc.so.6+0x2950f)

Indirect leak of 6 byte(s) in 2 object(s) allocated from:
    #0 0x7f23668bb308 in operator new[](unsigned long) (/lib64/libasan.so.8+0xbb308)
    #1 0x149e7cc in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1213
    #2 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #3 0x149ed08 in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1243
    #4 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #5 0x14ae8b2 in rtexif::ExifManager::parse(bool, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:2836
    #6 0x14b191b in rtexif::ExifManager::parseJPEG(int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:3199
    #7 0x149b4c3 in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:988
    #8 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #9 0x14a003c in rtexif::Tag::parseMakerNote(_IO_FILE*, int, rtexif::ByteOrder) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1310
    #10 0x149b8de in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1007
    #11 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #12 0x149ed08 in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1243
    #13 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #14 0x14ae8b2 in rtexif::ExifManager::parse(bool, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:2836
    #15 0x14ae17e in rtexif::ExifManager::parseRaw(bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:2800
    #16 0xdceece in rtengine::FramesData::FramesData(Glib::ustring const&, std::unique_ptr<rtengine::RawMetaDataLocation, std::default_delete<rtengine::RawMetaDataLocation> >, bool) /var/home/hub/source/RawTherapee/rtengine/imagedata.cc:1395
    #17 0x87e9d6 in rtengine::RawImageSource::load(Glib::ustring const&, bool) /var/home/hub/source/RawTherapee/rtengine/rawimagesource.cc:1343
    #18 0x8edd57 in rtengine::RawImageSource::load(Glib::ustring const&) (/var/home/hub/source/RawTherapee/_build/rtgui/rawtherapee-cli+0x8edd57)
    #19 0x5cfcc4 in rtengine::InitialImage::load(Glib::ustring const&, bool, int*, rtengine::ProgressListener*) /var/home/hub/source/RawTherapee/rtengine/loadinitial.cc:39
    #20 0x4175e9 in processLineParams(int, char**) /var/home/hub/source/RawTherapee/rtgui/main-cli.cc:733
    #21 0x41156c in main /var/home/hub/source/RawTherapee/rtgui/main-cli.cc:221
    #22 0x7f2364a2950f in __libc_start_call_main (/lib64/libc.so.6+0x2950f)

Indirect leak of 4 byte(s) in 1 object(s) allocated from:
    #0 0x7f23668bb308 in operator new[](unsigned long) (/lib64/libasan.so.8+0xbb308)
    #1 0x14a7949 in rtexif::Tag::initInt(int, rtexif::TagType, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1990
    #2 0x14b03ab in rtexif::ExifManager::parse(bool, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:3070
    #3 0x14b191b in rtexif::ExifManager::parseJPEG(int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:3199
    #4 0x149b4c3 in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:988
    #5 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #6 0x14a003c in rtexif::Tag::parseMakerNote(_IO_FILE*, int, rtexif::ByteOrder) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1310
    #7 0x149b8de in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1007
    #8 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #9 0x149ed08 in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1243
    #10 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #11 0x14ae8b2 in rtexif::ExifManager::parse(bool, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:2836
    #12 0x14ae17e in rtexif::ExifManager::parseRaw(bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:2800
    #13 0xdceece in rtengine::FramesData::FramesData(Glib::ustring const&, std::unique_ptr<rtengine::RawMetaDataLocation, std::default_delete<rtengine::RawMetaDataLocation> >, bool) /var/home/hub/source/RawTherapee/rtengine/imagedata.cc:1395
    #14 0x87e9d6 in rtengine::RawImageSource::load(Glib::ustring const&, bool) /var/home/hub/source/RawTherapee/rtengine/rawimagesource.cc:1343
    #15 0x8edd57 in rtengine::RawImageSource::load(Glib::ustring const&) (/var/home/hub/source/RawTherapee/_build/rtgui/rawtherapee-cli+0x8edd57)
    #16 0x5cfcc4 in rtengine::InitialImage::load(Glib::ustring const&, bool, int*, rtengine::ProgressListener*) /var/home/hub/source/RawTherapee/rtengine/loadinitial.cc:39
    #17 0x4175e9 in processLineParams(int, char**) /var/home/hub/source/RawTherapee/rtgui/main-cli.cc:733
    #18 0x41156c in main /var/home/hub/source/RawTherapee/rtgui/main-cli.cc:221
    #19 0x7f2364a2950f in __libc_start_call_main (/lib64/libc.so.6+0x2950f)

Indirect leak of 4 byte(s) in 1 object(s) allocated from:
    #0 0x7f23668bb308 in operator new[](unsigned long) (/lib64/libasan.so.8+0xbb308)
    #1 0x149e94f in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1224
    #2 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #3 0x14ae8b2 in rtexif::ExifManager::parse(bool, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:2836
    #4 0x14b191b in rtexif::ExifManager::parseJPEG(int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:3199
    #5 0x149b4c3 in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:988
    #6 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #7 0x14a003c in rtexif::Tag::parseMakerNote(_IO_FILE*, int, rtexif::ByteOrder) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1310
    #8 0x149b8de in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1007
    #9 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #10 0x149ed08 in rtexif::Tag::Tag(rtexif::TagDirectory*, _IO_FILE*, int) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:1243
    #11 0x1490c86 in rtexif::TagDirectory::TagDirectory(rtexif::TagDirectory*, _IO_FILE*, int, rtexif::TagAttrib const*, rtexif::ByteOrder, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:76
    #12 0x14ae8b2 in rtexif::ExifManager::parse(bool, bool, bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:2836
    #13 0x14ae17e in rtexif::ExifManager::parseRaw(bool) /var/home/hub/source/RawTherapee/rtexif/rtexif.cc:2800
    #14 0xdceece in rtengine::FramesData::FramesData(Glib::ustring const&, std::unique_ptr<rtengine::RawMetaDataLocation, std::default_delete<rtengine::RawMetaDataLocation> >, bool) /var/home/hub/source/RawTherapee/rtengine/imagedata.cc:1395
    #15 0x87e9d6 in rtengine::RawImageSource::load(Glib::ustring const&, bool) /var/home/hub/source/RawTherapee/rtengine/rawimagesource.cc:1343
    #16 0x8edd57 in rtengine::RawImageSource::load(Glib::ustring const&) (/var/home/hub/source/RawTherapee/_build/rtgui/rawtherapee-cli+0x8edd57)
    #17 0x5cfcc4 in rtengine::InitialImage::load(Glib::ustring const&, bool, int*, rtengine::ProgressListener*) /var/home/hub/source/RawTherapee/rtengine/loadinitial.cc:39
    #18 0x4175e9 in processLineParams(int, char**) /var/home/hub/source/RawTherapee/rtgui/main-cli.cc:733
    #19 0x41156c in main /var/home/hub/source/RawTherapee/rtgui/main-cli.cc:221
    #20 0x7f2364a2950f in __libc_start_call_main (/lib64/libc.so.6+0x2950f)
```

### PR DESCRIPTION
**Pull request by Beep6581**
Solves #3801 and many metadata-related issues.

### CODE REVIEW

**Comment by Thanatomanic** [comment]
How would one go about to resolve these merge changes? As in, technically speaking, git-wise?

**Comment by Beep6581** [comment]
@Thanatomanic I would merge `dev` into `metadata-exiv2` from the command line, which will result in merge conflicts which can then be fixed the standard way.
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-using-the-command-line

**Comment by Thanatomanic** [comment]
I think I have managed to resolve all merge conflicts decently. I needed to borrow some code from ART to fix a few issues, but the branch builds properly again. I have no idea yet whether everything works as intended, so please test!

Btw, I very much dislike that the commit log for this branch is spammed with irrelevant commits. Is there a way to clean that up, or maybe start fresh from this point onwards?

In any case, exiv2 support is a big step closer!

**Comment by Thanatomanic** [comment]
Also, the macOS build is broken due to lack of exiv2. I keep forgetting, but who can fix that?

File: rtengine/dcp.cc [hunk 1]
```diff
@@ -505,304 +525,221 @@ class DCPMetadata
...
+            auto &t = it->second;
+            if (t.type == ASCII) {
+                std::ostringstream buf;
+                unsigned char *value = &(t.value[0]);
+                buf << value;
+                return buf.str();
             }
         }
-        return {};
+        return "";
```
Comment (Floessie) [inline rtengine/dcp.cc]: Hm, there are some cleanups that got reverted... :neutral_face:

File: rtengine/imagesource.h [hunk 2]
```diff
@@ -42,7 +42,7 @@ namespace rtengine
 
 class ColorTemp;
 class DCPProfile;
-class DCPProfileApplyState;
+class DCPProfile::ApplyState;
```
Comment (Floessie) [inline rtengine/imagesource.h]: You can't forward declare an inner class. That was the reason to separate it as `DCPProfileApplyState`. Now you've got to include `dcp.h` in `imagesource.h` which is included in ...

File: rtgui/thumbnail.h [hunk 3]
```diff
@@ -26,6 +26,7 @@
 #include "cacheimagedata.h"
 #include "threadutils.h"
 #include "thumbnaillistener.h"
+#include "../rtengine/procparams.h"
```
Comment (Floessie) [inline rtgui/thumbnail.h]: And again burnt some megawatts. :wink:

**Comment by Thanatomanic** [comment]
@Floessie I see you're doing review, thank you. I must admit that for some modifications I leaned heavily on how I saw Alberto has made it work in ART. That may have resulted in some regressions. Apologies in advance for more review work, but this was my first big conflict resolution and I am not a pro in writing best practice C++ yet 😄

**Comment by Floessie** [comment]
@Thanatomanic Thanks for your work! You reintroduced some legacy code which needs to be cleaned up again.

**Comment by Floessie** [comment]
@Thanatomanic Ah no, that was neither a review -- I was just skimming through your commits -- nor did I want to make your feel uncomfortable. Sorry for that. I just saw some work I put into some aspects of the code reverted. Nothing that can't be mended. :wink:

Thanks for pushing this PR forward!

**Comment by Lawrence37** [comment]
What's the status of this? Does it need testing? Is Exiv2 ready? Should this be in 5.9?

**Comment by Beep6581** [comment]
Hey @Lawrence37 

From memory, the reason this wasn't been merged was because it would have been detrimental to a few corner cases, e.g. regarding some multi-frame raw formats, there is currently code allowing RawTherapee to read each frame's metadata, while with this merge the metadata would have been read for only one frame and copied to the others.

In my opinion, the pros heavily outweigh the cons.

**Comment by Beep6581** [comment]
The status is that there are merge conflicts. Since it was based on ART's implementation (IIRC), it would probably be best if someone compared to ART's current code, to benefit from whatever changes were implemented since this PR was opened.

**Comment by heckflosse** [comment]
We should also think about, why ART has an option to use exiftool instead if exiv2. Or ask Alberto about that... In my experience he did that for a reason...

**Comment by Thanatomanic** [comment]
I think I managed to make the necessary fixes to make things compile again (we'll see how the checks pan out). This should also include most - hopefully all - changes that @Floessie made earlier and got lost with the previous set of merges and fixes.

File: rtengine/dcp.cc [hunk 4]
```diff
@@ -526,215 +526,283 @@ class DCPMetadata
...
+                            : static_cast<double>(numerator) / static_cast<double>(denominator);
+                }
+                return 0.0;
+            }
+            case FLOAT: {
+                union IntFloat {
+                    std::uint32_t i;
+                    float f;
+                } conv;
+                conv.i = sget4(tag->second.value.data() + offset);
```
Comment (Floessie) [inline rtengine/dcp.cc]: Don't we need to check `offset` here, too?

File: rtengine/dcp.cc [hunk 5]
```diff
@@ -772,22 +840,22 @@ DCPProfile::DCPProfile(const Glib::ustring& filename) :
...
-        CALIBRATION_ILLUMINANT_1 = 50778,
-        CALIBRATION_ILLUMINANT_2 = 50779,
-        FORWARD_MATRIX_1 = 50964,
-        FORWARD_MATRIX_2 = 50965,
-        PROFILE_LOOK_TABLE_DIMS = 50981, // ProfileLookup is the low quality variant
-        PROFILE_LOOK_TABLE_DATA = 50982,
-        PROFILE_HUE_SAT_MAP_ENCODING = 51107,
-        PROFILE_LOOK_TABLE_ENCODING = 51108,
-        BASELINE_EXPOSURE_OFFSET = 51109
+        TAG_KEY_COLOR_MATRIX_1 = 50721,
```
Comment (Floessie) [inline rtengine/dcp.cc:849]: Better turn that into an `enum class` and compare with `if (TagKey(some_data) == TagKey::COLOR_MATRIX_1))`.

File: rtengine/dcp.cc [hunk 6]
```diff
@@ -1059,46 +1127,46 @@ DCPProfile::DCPProfile(const Glib::ustring& filename) :
...
-        md.toShort(CALIBRATION_ILLUMINANT_2) :
-        -1;
+        md.find(TAG_KEY_CALIBRATION_ILLUMINANT_2)
+            ? md.toShort(TAG_KEY_CALIBRATION_ILLUMINANT_2)
+            : -1;
     temperature_1 = calibrationIlluminantToTemperature(light_source_1);
     temperature_2 = calibrationIlluminantToTemperature(light_source_2);
 
-    const bool has_second_hue_sat = md.find(PROFILE_HUE_SAT_MAP_DATA_2); // Some profiles have two matrices, but just one huesat
+    const bool has_second_hue_sat = md.find(TAG_KEY_PROFILE_HUE_SAT_MAP_DATA_2); // Some profiles have two matrices, but just one huesat
```
Comment (Floessie) [inline rtengine/dcp.cc:1151]: Ah, now I see, why `TagKey` isn't an `enum class`. But this was fixedin [C++14](http://www.open-std.org/jtc1/sc22/wg21/docs/lwg-defects.html#2148). If sticking with C++11, you could use a comparator functor like [here](https://stackoverflow.com/questions/18837857/cant-use-enum-class-as-unordered-map-key).

**Review by Floessie — COMMENTED** [review]
@Thanatomanic Thanks for mending this again!

**Comment by Beep6581** [comment]
I'd love to get this merged, but we must leave it out of 5.9 and merge it for 5.10/6.0.

**Comment by Thanatomanic** [comment]
@Beep6581 Yes, I don't mind to delay the merge. We do need to update our `rtexif` mappings though as I mention in the referenced issue. I hope you can do that.

Edit: I see you replied there already :-)

**Comment by gaaned92** [comment]
@heckflosse 
Alberto used exiftool as a fallback when exiv2 failed in reading CR3 metadata.
Now CR3 metatada reading by last version of exiv2 is enabled in ART, so I no longer ship exiftool in the Windows bundled builds.

The first version of exiv2 able to decode CR3 metadata is identified by the tag `v0.27.4-RC2`. It is not included in MSYS2

Edit : exiv2 0.27.4 available in MSYS2

File: rtengine/imagedata.h [hunk 7]
```diff
@@ -64,85 +52,35 @@ class FrameData final
...
-    float getFocusDist () const;
-    double getShutterSpeed () const;
-    double getExpComp  () const;
-    std::string getMake () const;
-    std::string getModel () const;
-    std::string getLens () const;
-    std::string getSerialNumber () const;
-    std::string getOrientation () const;
-    int getRating () const;
+    FramesData(const Glib::ustring& fname);
```
Comment (Lawrence37) [inline rtengine/imagedata.h]:
```suggestion
    explicit FramesData(const Glib::ustring& fname);
```
https://github.com/Beep6581/RawTherapee/blob/33a4737c89d9b7450532908d5ef6477d47a5f08e/rtengine/imagedata.h#L114

File: rtgui/thumbnail.cc [hunk 8]
```diff
@@ -258,52 +318,35 @@ rtengine::procparams::ProcParams* Thumbnail::createProcParamsForUpdate(bool retu
...
-                // Should we ask all frame's MetaData ?
-                imageMetaData = rtengine::FramesMetaData::fromFile (fname, nullptr, true);
-            }
-            PartialProfile *pp = ProfileStore::getInstance()->loadDynamicProfile(imageMetaData);
-            delete imageMetaData;
-            int err = pp->pparams->save(outFName);
-            pp->deleteInstance();
-            delete pp;
-            if (!err) {
+            const auto pp_deleter =
```
Comment (Lawrence37) [inline rtgui/thumbnail.cc:332]: From a few lines above:
```c++
    const bool run_cpb = !options.CPBPath.empty() && !defaultPparamsPath.empty() && cfs && cfs->exifValid && create;
```
This was different before merge commit 28f0bc14da41102606ebf007e120b34f55f9ed82:
https://github.com/Beep6581/RawTherapee/blob/21a97980b6cf946f505e83dc8fff17ea13cab771/rtgui/thumbnail.cc#L309

File: rtengine/imagedata.cc [hunk 9]
```diff
@@ -19,55 +19,45 @@
...
-
 #include <glib/gstdio.h>
-
 #include <glibmm/convert.h>
+#include <exiv2/exiv2.hpp>
 
 #include "imagedata.h"
 #include "imagesource.h"
-#include "iptcpairs.h"
 #include "procparams.h"
```
Comment (Lawrence37) [inline rtengine/imagedata.cc]:
```suggestion
```
May not be necessary.

File: rtengine/imagedata.cc [hunk 10]
```diff
@@ -228,1024 +202,409 @@ FrameData::FrameData(rtexif::TagDirectory* frameRootDir_, rtexif::TagDirectory*
...
-    );
+    return fname_;
 }
 
 //------inherited functions--------------//
 
 std::string FramesMetaData::apertureToString(double aperture)
 {
-
+	// TODO: Replace sprintf()
```
Comment (Lawrence37) [inline rtengine/imagedata.cc:815]: Already replaced?

File: rtengine/imagedata.cc [hunk 11]
```diff
@@ -1285,176 +644,21 @@ std::string FramesMetaData::expcompToString(double expcomp, bool maskZeroexpcomp
 
 double FramesMetaData::shutterFromString(std::string s)
 {
-
-    size_t i = s.find_first_of('/');
+    const std::string::size_type i = s.find_first_of ('/');
```
Comment (Lawrence37) [inline rtengine/imagedata.cc]:
```suggestion
    const std::string::size_type i = s.find_first_of('/');
```

File: rtengine/imagedata.h [hunk 12]
```diff
@@ -21,36 +21,24 @@
...
-
-}
-
-namespace rtexif
-{
-
-class TagDirectory;
-}
+#include "rawimage.h"
+#include "rtengine.h"
```
Comment (Lawrence37) [inline rtengine/imagedata.h]: Some cleanup got reverted here. This could become
```c++
#include <vector>

#include <exiv2/exiv2.hpp>

#include "imageio.h"

namespace Glib
{

class ustring;

}
```

File: rtengine/imagedata.h [hunk 13]
```diff
@@ -21,36 +21,24 @@
...
-class FrameData final
-{
-
-protected:
-    rtexif::TagDirectory* frameRootDir;
-    IptcData* iptc;
+Exiv2::Image::AutoPtr open_exiv2(const Glib::ustring &fname); // TODO: Global function?
 
+class FramesData :
+    public FramesMetaData
```
Comment (Lawrence37) [inline rtengine/imagedata.h]:
```suggestion
class FramesData final :
    public FramesMetaData
```
https://github.com/Beep6581/RawTherapee/blob/33a4737c89d9b7450532908d5ef6477d47a5f08e/rtengine/imagedata.h#L104

File: rtengine/improcfun.cc [hunk 14]
```diff
@@ -5584,18 +5584,18 @@ void ImProcFunctions::getAutoExp(const LUTu &histogram, int histcompr, double cl
...
 {
     if (!fname.empty()) {
-        rtengine::RawMetaDataLocation ri;
+    	// TODO: std::unique_ptr<> to the rescue
         int w_raw = -1, h_raw = thumb_size;
         int w_thumb = -1, h_thumb = thumb_size;
 
         eSensorType sensorType = rtengine::ST_NONE;
-        Thumbnail* thumb = rtengine::Thumbnail::loadQuickFromRaw(fname, ri, sensorType, w_thumb, h_thumb, 1, FALSE);
+        Thumbnail* thumb = rtengine::Thumbnail::loadQuickFromRaw (fname, sensorType, w_thumb, h_thumb, 1, FALSE);
```
Comment (Lawrence37) [inline rtengine/improcfun.cc]:
```suggestion
        Thumbnail* thumb = rtengine::Thumbnail::loadQuickFromRaw(fname, sensorType, w_thumb, h_thumb, 1, FALSE);
```

File: rtengine/simpleprocess.cc [hunk 15]
```diff
@@ -1737,21 +1730,24 @@ class ImageProcessor
...
+            // and may contain subframe depending on initial raw's hierarchy
+            // readyImg->setMetadata (ii->getMetaData()->getRootExifData ());
+            readyImg->setMetadata(std::move(info));
+            break;
+        case MetaDataParams::EDIT:
+            info.setExif(params.exif);
+            info.setIptc(params.iptc);
+            readyImg->setMetadata(std::move(info));
+            // ask for the correct frame number, but may contain subframe depending on initial raw's hierarchy
+            // readyImg->setMetadata (ii->getMetaData()->getBestExifData(imgsrc, &params.raw), params.exif, params.iptc);
```
Comment (Lawrence37) [inline rtengine/simpleprocess.cc]: Remove the commented code or update the variable name.
```suggestion
            // Sending back the whole first root, which won't necessarily be the selected frame number
            // and may contain subframe depending on initial raw's hierarchy
            // readyImg->setMetadata (initialImage->getMetaData()->getRootExifData ());
            readyImg->setMetadata(std::move(info));
            break;
        case MetaDataParams::EDIT:
            info.setExif(params.exif);
            info.setIptc(params.iptc);
            readyImg->setMetadata(std::move(info));
            // ask for the correct frame number, but may contain subframe depending on initial raw's hierarchy
            // readyImg->setMetadata (initialImage->getMetaData()->getBestExifData(imgsrc, &params.raw), params.exif, params.iptc);
```

File: rtgui/thumbnail.cc [hunk 16]
```diff
@@ -35,14 +35,76 @@
...
-#include "../rtexif/rtexif.h"
 #include "guiutils.h"
 #include "batchqueue.h"
 #include "extprog.h"
 #include "md5helper.h"
 #include "pathutils.h"
 #include "paramsedited.h"
+#include "ppversion.h"
 #include "procparamchangers.h"
+#include "profilestorecombobox.h"
```
Comment (Lawrence37) [inline rtgui/thumbnail.cc]:
```suggestion
```
May not be necessary (e682b364b51febfbe7e53f67658d65987b62acdd).

File: rtengine/imagedata.cc [hunk 17]
```diff
@@ -19,55 +19,45 @@
...
-        return function(*frames[frame]);
-    }
-    if (!frames.empty()) {
-        return function(*frames[0]);
-    }
-    return {};
-}
+} // namespace rtengine
 
 const std::string& validateUft8(const std::string& str, const std::string& on_error = "???")
```
Comment (Lawrence37) [inline rtengine/imagedata.cc:44]: Put this back into an anonymous namespace.

File: rtengine/ashift_dt.c [hunk 18]
```diff
@@ -103,6 +103,9 @@ using namespace std;
 
 //-----------------------------------------------------------------------------
 // RT: BEGIN COMMENT
+#ifdef near
+#  undef near
+#endif
```
Comment (Lawrence37) [inline rtengine/ashift_dt.c:108]: Is this still necessary?

File: rtengine/imageio.cc [hunk 19]
```diff
@@ -31,7 +31,6 @@
 #include "utils.h"
```
Comment (Lawrence37) [inline rtengine/imageio.cc]:
```c++
#include <libiptcdata/iptc-jpeg.h>
```
Accidentally re-introduced this a few lines above.

File: rtgui/editwidgets.h [hunk 20]
```diff
@@ -307,14 +307,14 @@ class Polyline : public Geometry
     void drawToMOChannel (Cairo::RefPtr<Cairo::Context> &cr, unsigned short id, ObjectMOBuffer *objectBuffer, EditCoordSystem &coordSystem) override;
 };
 
-class Rectangle : public Geometry
+class EditRectangle : public Geometry // New class name to avoid conflict elsewhere (exiv2), would be nicer to put in namespace?
```
Comment (Lawrence37) [inline rtgui/editwidgets.h:316]: Was `Rectangle` in an older exiv2? It works fine for me with just `Rectangle` and I can't find any references to it in the exiv2 repository.

File: rtgui/thumbnail.h (hunk 3 above)
Comment (Lawrence37) [reply rtgui/thumbnail.h]: I think it can be safely removed.

File: rtengine/dcp.h [hunk 21]
```diff
@@ -171,10 +170,10 @@ class DCPStore final :
     std::vector<Glib::ustring> profileDir;
 
     // these contain standard profiles from RT. keys are all in uppercase, file path is value
-    std::map<std::string, Glib::ustring> file_std_profiles;
+    std::map<Glib::ustring, Glib::ustring> file_std_profiles;
 
     // Maps file name to profile as cache
-    mutable std::map<std::string, DCPProfile*> profile_cache;
+    mutable std::map<Glib::ustring, DCPProfile*> profile_cache;
```
Comment (Lawrence37) [inline rtengine/dcp.h]: These were changed to `std::string` for speed in 7257aee2351a71e768ab3cb4b94f75952ec181f5

File: rtengine/imagedata.cc [hunk 22]
```diff
@@ -228,1024 +202,409 @@ FrameData::FrameData(rtexif::TagDirectory* frameRootDir_, rtexif::TagDirectory*
...
-        tag = exif->findTag("SerialNumber");
-
-        if (!tag) {
-            tag = exif->findTag("InternalSerialNumber");
+        if (find_tag(Exiv2::orientation)) {
+            orientation = validateUft8(pos->print(&exif)); // validateUft8 (#5923) still needed?
         }
 
-        if (tag) {
-            serial = validateUft8(tag->valueToString());
```
Comment (Lawrence37) [inline rtengine/imagedata.cc:334]: This seems to be missing from the exiv2 implementation.

File: rtgui/exifpanel.cc [hunk 23]
```diff
@@ -100,24 +106,6 @@ ExifPanel::ExifPanel() :
...
-    buttons2->set_row_homogeneous (true);
-    buttons2->set_column_homogeneous (true);
-    setExpandAlignProperties (buttons2, true, false, Gtk::ALIGN_FILL, Gtk::ALIGN_CENTER);
-
-    remove = Gtk::manage (new Gtk::Button ()); // M("EXIFPANEL_REMOVE")
-    remove->set_image (*Gtk::manage (new RTImage(delicon)));
-    remove->set_tooltip_text (M ("EXIFPANEL_REMOVEHINT"));
-    remove->get_style_context()->add_class ("Left");
-    setExpandAlignProperties (remove, true, true, Gtk::ALIGN_FILL, Gtk::ALIGN_FILL);
-    buttons1->attach_next_to (*remove, Gtk::POS_LEFT, 1, 1);
```
Comment (Lawrence37) [inline rtgui/exifpanel.cc:113]: Now it is not possible to remove editable EXIF fields.

File: rtengine/imagedata.cc [hunk 24]
```diff
@@ -228,1024 +202,409 @@ FrameData::FrameData(rtexif::TagDirectory* frameRootDir_, rtexif::TagDirectory*
...
+        if (
+            !make.compare(0, 6, "PENTAX")
+            || (
+                !make.compare(0, 5, "RICOH")
+                && !model.compare (0, 6, "PENTAX")
+            )
+        ) {
+            if (find_exif_tag("Exif.Pentax.DriveMode")) {
+                std::string buf = pos->toString(3);
+                buf[3] = 0;
```
Comment (Lawrence37) [inline rtengine/imagedata.cc]:
```suggestion
```
Otherwise this will cause a crash.

**Review by Lawrence37 — COMMENTED** [review]
Because there were many commits since the initial exiv2 implementation, I independently merged with `dev` and compared the results to this branch. My merge was not perfect, but I was able to find the differences and left a few comments. I did not fully review `rtengine/dcp.*`.

To my knowledge, these are the remaining tasks:
- Fix #5787 again
- Re-implement ratings with exiv2 (see #5325)
- Check if the suppressed fix for #5923 needs to be re-applied
- Fix for color profile not added to exported photos (https://discuss.pixls.us/t/cr3-metadata-decoding-test-of-feature-branch-on-linux/31181/10)
- Pull additional metadata related updates from ART
- Enable exiv2 BMFF support for CR3 metadata

File: rtgui/thumbnail.cc (hunk 8 above)
Comment (Lawrence37) [reply rtgui/thumbnail.cc:332]: Seems like this is ok (https://bitbucket.org/agriggio/art/commits/d088e29d1b0cfd80489071e768a3ba3abee85364)

File: rtengine/imagedata.h (hunk 7 above)
Comment (Lawrence37) [reply rtengine/imagedata.h]: Done in #6631

File: rtengine/imagedata.cc (hunk 9 above)
Comment (Lawrence37) [reply rtengine/imagedata.cc]: Done in #6631

File: rtengine/imagedata.cc (hunk 11 above)
Comment (Lawrence37) [reply rtengine/imagedata.cc]: Done in #6631

File: rtengine/imagedata.h (hunk 12 above)
Comment (Lawrence37) [reply rtengine/imagedata.h]: Done in #6631

File: rtengine/imagedata.h (hunk 13 above)
Comment (Lawrence37) [reply rtengine/imagedata.h]: Done in #6631

File: rtengine/improcfun.cc (hunk 14 above)
Comment (Lawrence37) [reply rtengine/improcfun.cc]: Done in #6631

File: rtengine/simpleprocess.cc (hunk 15 above)
Comment (Lawrence37) [reply rtengine/simpleprocess.cc]: Done in #6631

File: rtgui/thumbnail.cc (hunk 16 above)
Comment (Lawrence37) [reply rtgui/thumbnail.cc]: Done in #6631

File: rtengine/imagedata.cc (hunk 17 above)
Comment (Lawrence37) [reply rtengine/imagedata.cc:44]: Done in #6631

File: rtengine/imageio.cc (hunk 19 above)
Comment (Lawrence37) [reply rtengine/imageio.cc]: Done in #6631

File: rtgui/thumbnail.h (hunk 3 above)
Comment (Lawrence37) [reply rtgui/thumbnail.h]: Done in #6631

File: rtengine/dcp.h (hunk 21 above)
Comment (Lawrence37) [reply rtengine/dcp.h]: Done in #6631

File: rtgui/exifpanel.cc (hunk 23 above)
Comment (Lawrence37) [reply rtgui/exifpanel.cc:113]: Done in #6631

File: rtengine/imagedata.cc (hunk 24 above)
Comment (Lawrence37) [reply rtengine/imagedata.cc]: Done in #6631

File: rtengine/imagedata.cc (hunk 22 above)
Comment (Lawrence37) [reply rtengine/imagedata.cc:334]: Done in #6631.

File: rtengine/dcp.cc (hunk 6 above)
Comment (Lawrence37) [reply rtengine/dcp.cc:1151]: Tag IDs are read from the file. Is it safe to cast them into enums and use them as map keys? From my research it seems ok, but I'm not completely sure.

**Comment by Lawrence37** [comment]
This is now ready for review.

**Comment by Thanatomanic** [comment]
This is great Lawrence! Will try to test soon.

**Comment by Beep6581** [comment]
@Lawrence37 fantastic! I will help with testing.

**Comment by rs-gh-asdf** [comment]
I am not a software developer but I have a vested interest in this branch being merged, even if it only makes it into the dev branch and not into an appimage. I have compiled the metadata-exiv2 branch of RawTherapee and have tested its ability to load metadata from various different files. I have found that it is successful every time.

RT5 9-exiv2 CANON EOS REBEL T3i cr2-pathredacted
RT5 9-exiv2 CANON EOS REBEL T3i-pathredacted
RT5 9-exiv2 CANON EOS REBEL T5i-pathredacted
RT5 9-exiv2 CANON EOS RP-pathredacted
RT5 9-exiv2 EPSON PERFECTIONV550-pathredacted
RT5 9-exiv2 NIKON D700-pathredacted
RT5 9-exiv2 NIKON D800-pathredacted
RT5 9-exiv2 RICOH PENTAX-pathredacted

Paths redacted for privacy. The Epson is a high-resolution scanner so it has no other useful metadata. I have sourced these files from various friends and I will track down and test metadata-reading for as many different camera and file types as it takes to get this merged.

**Comment by Lawrence37** [comment]
@rs-gh-asdf Thank you so much for testing! It's great to see that this works with all those cameras. This branch also uses Exiv2 to write metadata, so you might want to check the output images too.

**Comment by Beep6581** [comment]
I am happy to report that while `5.9-97-g`23408bfcb shows the shutter count for [`amsterdam.pef`](http://rawtherapee.com/shared/test_images/amsterdam.pef) completely incorrectly as `242, 5, 179, 228`, this `metadata-exiv2` branch shows the value correctly as `28682`, and the relevant tag is much easier to find. Great work!

**Comment by Benitoite** [comment]
CR3 (cf. https://github.com/Beep6581/RawTherapee/issues/6248) is read and applied to the lens correction automatically.
Screen Shot 2023-03-10 at 11 01 13 PM
🆒

**Comment by Benitoite** [comment]
A counter-example with a Canon R7 that is recognized but not yet in lensfun, so no detection. Also, an unusual or new spelling for a Sigma lens was a variation of a lens in lensfun. Not sure if that was an alternate name or a new type of Sigma.
Screenshot 2023-03-13 at 6 21 26 AM 1

macOS build avail (for testing) @ https://kd6kxr.github.io/meta/

**Comment by Lawrence37** [comment]
I see @Benitoite has made macOS builds available for testing. Should we create a general call for testing on Pixls?

**Comment by Floessie** [comment]
I'd say yes. This needs to move forward...

**Comment by Benitoite** [comment]
Testing the docker build on Debian bullseye, both rtengine/imageio.cc and imagedata.cc needed the `#include <iostream>`

Example:
`#12 11.94 /root/programs/code-rawtherapee/rtengine/imagedata.cc:34:1: note: ‘std::cerr’ is defined in header ‘<iostream>’; did you forget to ‘#include <iostream>’?`


I applied this fix and it builds ok:

```
RUN perl -l -i -p -e 'print "#include <iostream>" if $. == 25' ~/programs/code-rawtherapee/rtengine/imageio.cc
RUN perl -l -i -p -e 'print "#include <iostream>" if $. == 25' ~/programs/code-rawtherapee/rtengine/imagedata.cc
```

**Review by Benitoite — APPROVED** [review]
Good build on debian:bullseye, thank you!
https://github.com/Benitoite/RawTherapee/pkgs/container/rawtherapee_docker-image

**Comment by Lawrence37** [comment]
After #6723 is merged, I will make a post on Pixls to ask people to test.

**Comment by ghost** [comment]
As requested by @Lawrence37 on pixls I gave this one a try and ran immediately into an issue. This issue includes a previous bug-report (https://github.com/Beep6581/RawTherapee/issues/6291). Turns out that this is not limited to F-Mount lenses as I expected in that specific bug report.

Long story short:

> RawTherapee does no handle Nikon Z series mirror-less cameras correctly when determining the lens that is used and it is not limited to F or Z mount lenses.

I initially tested using my own Z 6ii and the 6 lenses I have (2 Z mounts and 4 F mounts). Non are reported correctly. And, although I presume that Nikon's internal handling of the metadata is the same for all Z types, I decided to also test this with the following Z-series types (that's all of them?):

* Nikon Z fc
* Nikon Z 5 
* Nikon Z 6
* Nikon Z 7
* Nikon Z 7ii 
* Nikon Z 9
* Nikon Z 30
* Nikon Z 50

RawTherapee either doesn't find the lens at all or reports the wrong lens. I made sure to check in the lensfun database to make sure if the lens used with the tested Z types are actually present. The lens info shown (*show exif info*) also shows the wrong information, (I'm sure those are linked). Have not been able to detect any other meta-data issues, at least not the most important ones.

I also checked all the RAWs I tested against XnViewMP as well and it does find/reports the correct lenses (it uses exiftool, though).

---

If I test with my Nikon D750 all works nicely with exiv2 at RT's base.

---

**EDIT**

Also did some tests with RAWs from my old cameras:

* Panasonic DC-LX100M2: **OK**
* Nikon D700: **OK**
* Nikon D200: **OK**
* Nikon Coolpix P6000: **OK**

**Comment by kmilos** [comment]
Yep, lens information in Nikon Z bodies moved compared to the D ones and extra logic is required (suggestion added to #6291). Also, note that exiv2 0.27.6 is needed to access Z 9 lens information.

**Comment by Lawrence37** [comment]
@jade-nl When you say it is not limited to F-mount lenses, is that for `dev` too or just this branch?

**Comment by ghost** [comment]
@Lawrence37 

> is not limited to F-mount lenses, is that for dev too or just this branch?

This issues has been around ever since Nikon introduced their mirror-less (Z series) cameras. First time I noticed was using _RT 5.8 dev_ and I also see this in _5.9 stable_, _5.9 dev_ and this _exiv2 branch_.

At the time I thought it was specific to F-mount lenses. I wanted to make sure you knew this is *not* limited to F-mount lenses, that is why I mentioned it here.

To summarize:

* this is a Nikon Z series related issue (lens info meta-data has changed for these cameras),
* this is independent of the lens type used,
* this is *not* specific to this exiv2 branch.

**Comment by kmilos** [comment]
> this is a Nikon Z series related issue

It also affects the D780 and D6 as the most up to date Nikon bodies that have more modern firmware similar to the Z series.

**Comment by Muskateer10** [comment]
Screenshot (3)

Worked on Canon R6 Mark 2.  Both JPG and TIF 16 bit output files showed Meta Data. 
good job.

**Comment by ghost** [comment]
@Lawrence37 

Just merged the latest changes you made and a quick **Nikon Z series** test tells me that this issue seems to be **fixed** now.

Only did a quick test using my Nikon Z6ii and the handful of F-mount Nikkor lenses I have, which are now picked up and shown correctly.

I'll do a broader test when time permits.

Anyway: Thanks for the time and effort you've been putting into this PR thus far!

**Comment by ghost** [comment]
@Lawrence37 

Just noticed you pushed another Nikon related change, not sure what that one entails, but I merged it and did some further testing. This not limited to F-mount lenses on my own Z series Z6ii camera.

- No regression for DSLR Nikons. D200, D700, D750 and D800: All still good,
- Z series with F-mount lenses: (FX) Z6, Z6ii, Z7ii: All good.Somewhat limited testing due to not able to find many Z-series+F-mount combos. Test with my Z6ii included 50mm, 85mm, 105mm and 70-200mm F-mounts, though.
- Z series with Z-mount lenses. (FX) Z5, Z6ii, Z7, Z9 and (DX) Zfc, Z50, Z30 : All good.

@kmilos mentioned the D780 and D6 also having this issue: I do not have these 2 in my collection, so cannot specifically test those.

**Comment by kmilos** [comment]
@jade-nl You have both D780 and D6 samples available on https://raw.pixls.us/ of course.

File: rtengine/imagedata.cc [hunk 25]
```diff
@@ -320,7 +320,9 @@ FramesData::FramesData(const Glib::ustring &fname, time_t ts) :
             //orientation = pos->print(&exif);
         }
 
-        if (find_exif_tag("Exif.NikonLd4.LensIDNumber") || find_exif_tag("Exif.Sony2.LensID")) {
+        if ((find_exif_tag("Exif.NikonLd4.LensID") && pos->toLong()) ||
```
Comment (kmilos) [inline rtengine/imagedata.cc]: I don't think you want to prioritize `Exif.NikonLd4.LensID` translation by exiv2 ahead of (in the case of Nikon Z) already sane ASCII string in `Exif.Photo.LensModel` provided by `Exiv2::lensName`. As mentioned, the exiv2 internal lens tables will become out of date very quickly, and there is no guarantee when the next update will happen...

Comment (Lawrence37) [reply rtengine/imagedata.cc]: The reason I placed LensID first is because the correct lens name was not read when I placed it after.

Comment (kmilos) [reply rtengine/imagedata.cc]: That's a bit strange... Mind sharing an example? What version of exiv2?

**Comment by cosenmarco** [comment]
Hello, I compiled today this branch from source on arch Linux because I wanted to have support for exif metadata on my Canon EOS RP and on the compiled instance I get pink pictures as opposed to the official appimage

image

I used
```
cmake -DCACHE_NAME_SUFFIX="" -DPROC_TARGET_NUMBER="2" -DWITH_LTO="ON" -DBUNDLE_BASE_INSTALL_DIR="$PWD/build" -DCMAKE_BUILD_TYPE="release"
```

**Comment by Lawrence37** [comment]
@cosenmarco It could be the same as #6720 which is fixed in `dev`. Do you mind sharing a sample raw file, or checking if an older version of `dev` shows the same problem but is ok in the latest `dev`?
Older `dev`: https://github.com/Beep6581/RawTherapee/suites/11809069121/artifacts/616450428
Latest `dev`: https://github.com/Beep6581/RawTherapee/suites/12062890572/artifacts/634585091

**Comment by cosenmarco** [comment]
@Lawrence37 sure I can share the RAW: https://drive.google.com/file/d/1vDPpK-iJkChZ0iKhomW2lXGBVPiyRbw1/view?usp=sharing

With the "Old" dev you linked the image loads fine as well as with the "Latest" dev.

File: rtengine/imagedata.cc (hunk 25 above)
Comment (Lawrence37) [reply rtengine/imagedata.cc]: With Exiv2 0.27.5, the Z 6_2 image provided by @jade-nl in https://github.com/Beep6581/RawTherapee/issues/6291#issuecomment-869113552 shows up as "VR 105mm f/2.8G" (from Exif.Photo.LensModel) and Exif.Photo.LensMake is blank. Though Lensfun automatic detection works, the name is not precise an may cause issues in the future. The ExifTool-based rtexif is using LensModel and LensMake only if the lens name is not found elsewhere (for example, the LensID as interpreted by ExifTool).

Based on the above observations, I feel the best approach is to first check if Exiv2 has an interpretation of the LensID (i.e. the printed string of LensID is not equal to the LensID integer as a (base10?) string), then falling back to LensModel. You seem to have more knowledge of Exiv2, so what do you think of this approach?

Comment (kmilos) [reply rtengine/imagedata.cc]: Ah, but that was because it was an older F-mount lens w/ FTZ adapter. [Please read the logic I proposed again](https://github.com/Beep6581/RawTherapee/issues/6291#issuecomment-1484060720) - prioritize translated NikonLd4.LensIDNumber (iff LensID is 0), otherwise (new Z lens on Z body) Photo.LensModel is usable.

Comment (Lawrence37) [reply rtengine/imagedata.cc]: Ok, I did not notice that comment, but how do we know LensModel is correct for Z lenses? What about older F-mount cameras? Do they not use LensModel and therefore it's safe to use Exif2::lensName, or must we use Exif.NikonLd3.LensIDNumber and others?

Comment (Lawrence37) [reply rtengine/imagedata.cc]: In the meantime, I changed the logic to use use Exiv2::lensName if Exiv2 cannot interpret LensID or LensIDNumber.

**Comment by Lawrence37** [comment]
@cosenmarco Looks like the AppImages are not prone to the issue I mentioned. Looking at how RawTherapee handles your file, however, it does appear to be the same issue. I updated this Exiv2 branch with the fix and the magenta color no longer exists for the image you provided.

File: rtengine/imagedata.cc (hunk 25 above)
Comment (kmilos) [reply rtengine/imagedata.cc]: I guess that could work as well.

**Comment by jasperchua99** [comment]
hi can i ask what is the status of adopting exiv2 atm? any etc that it may be included in the dev build soon?

**Comment by Lawrence37** [comment]
It is in the beta testing stage. There is one outstanding issue reported in https://discuss.pixls.us/t/call-for-testing-rawtherapee-metadata-handling-with-exiv2-includes-cr3-support/36240/84

As for when it will be ready for dev, I'm not sure. Exiv2 is critical for CR3 metadata, but it is a huge change that may only be safe for 6.0. It will come down to the results of extensive testing.

**Comment by Jens1122** [comment]
Changed rate is not reflected in RT
I have pictures, which I rate 3 in Digikam (jpg including metadata, orf with xmp sitecar).
Started RT. The rate is reflected correctly in RT for both pictures. Closed RT.
Changed rate in digikam. Started RT. The new rate is not reflected in RT, the old rate is shown (for both pictures). Enforced writing a pp3 file, this also contains the wrong (old) rate.

**Comment by Lawrence37** [comment]
Hi @Jens1122. That's happening because RawTherapee caches the rating. Now that RawTherapee can read XMP sidecars, it makes sense to read the sidecar instead of relying on the cache. I will see if I can update the logic. For now, you can right click -> cache -> clear, then reload the folder. Note that ratings are also stored in the pp3 so this won't work on edited images. Synchronizing pp3 and XMP ratings may be desirable, but I'm not sure if this is always a good idea.

**Comment by Lawrence37** [comment]
Ratings are now correctly read from the XMP sidecars after being updated. Ratings in pp3s still take precedence and are not synced with XMPs modified by other programs.

**Comment by Jens1122** [comment]
Hi @Lawrence37,
just checked the last AppImage. Lens Model Reading works fine for my ILCE stuff.
The rating works as described above, I hope this change will not cause any performance issues for entering a folder with a large amount of images.
I'm not happy with the precedence of rating always from pp3. With that the rating changes are not reflected as soon as images were edited in RT.
I see several options:
- inverting the preference in case of "Metadata Synchronization with XMP Sidecars" is set in the configuration.
-  not writing the rating into the pp3 in case this option is set (I could convert my exiting "legacy" pp3s with a small script) for consistency.
- enforce re-reading the metadata from sidecar with right-click->disk-cache or right-click-profile-operation extension. 

Thanks for your work.

**Comment by Lawrence37** [comment]
Thanks for confirming the lens model and ratings are working as expected. The XMP and pp3 rating synchronization issue is complex because of the many combinations of if those sidecar files exist and how they are created, modified, and deleted. I will think about it to see if there is a good automatic synchronization procedure. Due to the many possible scenarios, I doubt there is and the best option would be to have manual options to read and write the pp3 ratings to and from the XMPs.

**Comment by Jens1122** [comment]
Hi @Lawrence37,
for a good strategy, I think that 3 things need to be taken into account:
- What is the final state? Are the exif data exclusively stored in the image / xmp metadata and the pp3 contains only RT editing operation?
- What is the transition scenario? How to migrate, how to have legacy and new world living concurrently?
- What is the release scenario? I thing, big changes need to be released in small but useful steps to get early user feedback and have the benefits early available.

**Comment by Lawrence37** [comment]
After some thought, I came to the conclusion that the ratings should not be automatically synchronized between the pp3 and XMP. There are three reasons:
1. If the rating in the pp3 is changed outside of RawTherapee (e.g. by pasting a new pp3 in the directory), this is the rating that is desired. Therefore, the XMP should be updated. However, if we were to update the XMP with another program, this is the rating that is desired and the pp3 should be updated. All these operations take place outside of RawTherapee, so there is no way to determine which rating needs updating. The best we can do is try to check the modified time of the files and keep the most recent one.
2. RawTherapee can only update the pp3s and XMPs it can see. It will only touch the ones corresponding to the images you edit or browse in the file browser. If the pp3s and XMPs are automatically updated, it would be confusing because it would only happen for some images.
3. Automatic behavior can catch users off-guard especially if there is no visual indication of what's happening.

Two menu options or buttons to sync from pp3 to XMP and sync from XMP to pp3 seems like the best solution.

**Comment by Jens1122** [comment]
Hi @Lawrence37 ,
thanks for still working on this feature.
The sync buttons are ok, but for me personally this bears the problem that I forget to sync usually.
What's about having the configuration choice "Metadata from pp3" or "Metadata from exif". The first choice represents the current behavior, the second one ignores the pp3 (and probably leaves these entries empty) and uses image-exif or xmp data.
I also would not stick to rating only, as soon as this works, questions will come up for Color Label, Pick Label, ... Even if RT is not able to show some of them, what's about copying the metadata into the resulting developed images.
I don't want to open an endless list of enhancements, but for the first Rating step, this might need to be taken into account.

**Comment by Lawrence37** [comment]
Not an option to select where to read the metadata, as that changes the pp3 behavior, but an option to choose to write the metadata to pp3, XMP, or both. This and the manual syncing would be my recommendation.

**Comment by Jens1122** [comment]
Hi @Lawrence37,
I'm fine with your proposal as it solves my issues and obsoletes my shell scripts I'm using for syncing pp3 and xmp.
Nevertheless in the long run it might be worth to rethink the holy grail of pp3 contents, as it is not a good idea to have the same information (exif data) stored at 2 different places and kept in sync.
Thanks, Jens

**Comment by Lawrence37** [comment]
It will always be up to the user to choose the correct settings if they don't want metadata in the pp3. Suppose XMP sidecar write is disabled. Ratings have to be stored somewhere and the pp3 is the only place to do it. Thus, the user must select bidirectional for XMP, and XMP for metadata storage preference.

**Comment by Lawrence37** [comment]
What's the sentiment on including this for 5.10 vs. 6.0? On one hand, this will finally bring metadata support for cr3s. On the other hand, it's a big change with a high probability of bugs and incompatibilities despite testing by the wonderful participants from Pixls.

**Comment by ghost** [comment]
> What's the sentiment on including this for 5.10 vs. 6.0?

As a user I don't see why this would not be suitable to be part of the 5.10 release. As mentioned, this will bring better and fixed/overdue metadata support.

This PR having possible bugs and incompatibilities is a non reason to not include this in 5.10 in my opinion; These possible issues will, most likely, also be there when we wait till 6.0. Version 6.0 is going to be a rather big one, so maybe it would even be wiser to not add it to the commotion that 6.0 will bring about.

Another point would be the time this would take before it is implemented. Both 5.10 and 6.0 do not, as of yet, have a due date attached to them ([milestones](https://github.com/Beep6581/RawTherapee/milestones)). I don't have any idea if we are talking weeks, months or, like 5.8->5.9, years..... Earlier is better.

Just my 2c.

**Comment by Lawrence37** [comment]
I wish to see this in 5.10. Cr3 support is very important to the health of the RawTherapee community. The reason I bring 6.0 up is because there are valid concerns about releasing this too early.

You are right that we'll have to deal with bugs sooner or later. The benefit of postponment is that we can merge to dev immediately after the 5.10 release, thus giving the Exiv2 integration maximum exposure to dev users. One of the reasons why I asked people on Pixls to try this branch is because it is somewhat of a substitute for dev testing.

From an observer's point of view, this looks ready to merge. That's what I thought before getting into the testing and development. The implementation wasn't complete, hence the need to cherry-pick all those commits from ART. Now it is in a much better state. From my first-hand experience, I can tell you that Exiv2 handles metadata differently from ExifTool and Exiv2 is significantly less mature than ExifTool. I seriously doubted if Exiv2 was the right choice at one point. This pull request has the potential to break many things for users. 6.0 gives us some freedom to do that.

All things considered, however, I still believe the best choice is to have this in 5.10. I ask others for their opinions due to the significant implications.

**Comment by Jens1122** [comment]
Looking to the Bug Finding activities on the exif branch, I don't see any new testers or reported issues. So more time for the exif branch will not improve quality. -> 5.10
Merging dev branch features into the exif branch might introduce new issues over time, since (my assumption) the dev test coverage on the exif branch will be less than on the dev branch itself. -> 5.10
The exif branch is a a major improvement, so it is valuable to spend a major release number. This also will boost the acknowledgement of this great improvement. -> 6.0. But this would require to have 6.0 available soon, which is not realistic.
I personally am using the exif AppImage without problems. I would be very happy to have the exif feature available via the regular packet manager asap, which requires to have the exif feature in a regular release.
Given that, 5.10 would be the right release.

**Comment by Lawrence37** [comment]
Thanks for the input @Jens1122.

To clarify, I claim merging this after 5.10 does improve the odds of users finding bugs before a release because there are dev users who may not have tested this branch, or have only briefly done so. Delaying it for 6.0/5.11 gives these people more time to use it in their workflows.

Also note that a major version bump is not required for major new features. See local adjustments in 5.9 for example.

**Comment by Benitoite** [comment]
at this point, imho, all dev users should be testing this pr now.  perhaps you can release current dev as a minor point version, merge right away, and commence with broader testing for your planned 5.10 or 6.0.

**Comment by Lawrence37** [comment]
Due to all the new features in `dev`, the next release can be properly called 5.10.

Now that I think about it, 2-3 months in `dev` is more than enough time for bug-finding. Worst-case scenario is having too many bugs to fix. I can just revert the merge and save it for the next release. Now I'm only concerned about breaking compatibility due to things like lens name differences between ExifTool and Exiv2.

**Comment by Benitoite** [comment]
@Lawrence37 @Beep6581 @jade-nl @Jens1122 
At this point in time it seems 5.10 will not include this code.  Hopefully we can get past the 5.10 release as soon as possible.  6.0 also seems it would be a bit too far in the future.  Is it possible to add a signpost for 5.11 to include this PR?

**Comment by Hombre57** [comment]
@Lawrence37 Looking at the beahaviour and code now. The section's header displayed in the Exif panel seems a bit ambiguous, but probably issue from Exiv2 ?

**Comment by Hombre57** [comment]
I've tested the CR3 files from [this playraw](https://discuss.pixls.us/t/what-do-people-use-to-get-the-most-detail-out-of-the-shadows-in-images-with-large-differences-between-highlights-and-shadows/37465) and the result was better in dev than in the exiv2 branch. Below is the comparison with exiv2 on the left, dev on the right. There's a black border and colors are not the same in the exiv2 branch (I developped it initially on dev, and I think the colors are what I expect them to be).

exiv2-vs-dev

[AboutThisBuild - exiv2.txt](https://github.com/Beep6581/RawTherapee/files/12268034/AboutThisBuild.-.exiv2.txt)
[AboutThisBuild - dev.txt](https://github.com/Beep6581/RawTherapee/files/12268037/AboutThisBuild.-.dev.txt)
+ exiv2 v0.27.6

Still testing this branch, but the CR3 support doesn't seem better now. Both version doesn't show Exifs in the Metadata panel.

So I'd follow @Lawrence37 on this one : merge it right after 5.10. Bugfix of 5.10 should be applied in dev + in a 5.10.1 branch, for a bugfix release (i.e. w/o exiv2). We can also produce a 5.12 version with exiv2 without waiting for v6.0, for the reasons @Lawrence37 explained. Does that makes sens ?

What worries me the most is :

> From my first-hand experience, I can tell you that Exiv2 handles metadata differently from ExifTool and Exiv2 is significantly less mature than ExifTool. I seriously doubted if Exiv2 was the right choice at one point.

At least, exiv2 is a dependancy, we don't have to maintain our own database from exiftool. So overall it's the right move to stay up to date. This maintenance concern can, in itself, justify our choice and explain to the users why it might have some drawback.

**Comment by Lawrence37** [comment]
Are you testing this branch with dev merged in? There might have been a raw crop and color matrix added for that camera in dev since the last merge.

**Comment by Hombre57** [comment]
I'm testing the `metadata-exiv2` branch as is, which is the one that pixls.us tester uses, I guess.

**Comment by Lawrence37** [comment]
After merging with dev, I get this.
image

With the auto-matched tone curve profile:
image

**Comment by Lawrence37** [comment]
> The section's header displayed in the Exif panel seems a bit ambiguous, but probably issue from Exiv2 ?

Yes, the headers are directly from Exiv2.

> Both version doesn't show Exifs in the Metadata panel.

Does your Exiv2 read metadata for CR3s? It needs to be compiled with the `-DEXIV2_ENABLE_BMFF=ON` option (and it only works on v0.27.4 or newer, which you have).

**Comment by Hombre57** [comment]
Thanks, I'll give it a try tomorrow (monday).

For Exiv2, it's the one provided by Fedora. I don't know if this option has been enabled.

**Comment by kmilos** [comment]
> For Exiv2, it's the one provided by Fedora. I don't know if this option has been enabled.

It is not enabled on Fedora for 0.27.x. (`exiv2 -vV | grep bmff`)

**Comment by Benitoite** [comment]
Bugzilla for missing fedora exiv2 flag: https://bugzilla.redhat.com/show_bug.cgi?id=1979565

Flag is enabled in Homebrew: https://github.com/Homebrew/homebrew-core/blob/41719426547246c012048f6c97f0e66355146f01/Formula/exiv2.rb#L45

**Comment by Hombre57** [comment]
Isn't Exiv2 [enabling BMFF by default](https://github.com/Exiv2/exiv2/blob/e1c94a13d682ce938e65df13d7cfd221a18d0768/CMakeLists.txt#L40) ? The switch off is intentional for the reasons explained in the Redhat bugzilla issue, I guess.

**Comment by Benitoite** [comment]
@Hombre57 Correct. Here the flag is set to OFF: https://src.fedoraproject.org/rpms/exiv2/blob/main/f/exiv2.spec#_80

**Comment by Lawrence37** [comment]
@Hombre57, do you want some time to test this before I merge?

Just in case you're not aware, the automated AppImage builds include a version of Exiv2 that supports CR3 metadata. The latest build is accessible from the [Checks tab](https://github.com/Beep6581/RawTherapee/pull/5889/checks).

**Comment by Hombre57** [comment]
@Lawrence37 I'll finish today. Thanks for your patience :pray: .

**Comment by Hombre57** [comment]
@Lawrence37 I've test what I was interested into, and found nothing that could hold the merge, despite the regression introduced by Exiv2. Here is the comparison of output (stripped down info, for better understanding) from a Pentax PixelShift image :

**Exiftool**
```
< --- Frame #1 --->
+ [IFD0 directory with 39 entries]             < Thumbnail of frame #1 >
| 0)  SubfileType = 1
| 1)  ImageWidth = 160
| 2)  ImageHeight = 120
| 3)  BitsPerSample = 8 8 8
| + [SubIFD directory with 26 entries]               < Raw image of frame #1 >
| | 0)  SubfileType = 0
| | 1)  ImageWidth = 7392
| | 2)  ImageHeight = 4950
| | 3)  BitsPerSample = 14
| + [SubIFD1 directory with 20 entries]              < Full size preview of the PixelShift image >
| | 0)  SubfileType = 1
| | 1)  ImageWidth = 7360
| | 2)  ImageHeight = 4912
| | 3)  BitsPerSample = 8 8 8
| + [ExifIFD directory with 22 entries]
| + [GPS directory with 1 entries]
| + [MakerNotes directory with 122 entries]

< --- Frame #2 --->
+ [IFD1 directory with 38 entries]             < Thumbnail of frame #2 >
| 0)  SubfileType = 1
| 1)  ImageWidth = 160
| 2)  ImageHeight = 120
| 3)  BitsPerSample = 8 8 8
| + [SubIFD directory with 26 entries]               < Raw image of frame #2 >
| | 0)  SubfileType = 0
| | 1)  ImageWidth = 7392
| | 2)  ImageHeight = 4950
| | 3)  BitsPerSample = 14
| + [ExifIFD directory with 22 entries]
| + [MakerNotes directory with 121 entries]

< --- Frame #3 --->
+ [IFD2 directory with 38 entries]             < Thumbnail of frame #3 >
| 0)  SubfileType = 1
| 1)  ImageWidth = 160
| 2)  ImageHeight = 120
| 3)  BitsPerSample = 8 8 8
| + [SubIFD directory with 26 entries]               < Raw image of frame #3 >
| | 0)  SubfileType = 0
| | 1)  ImageWidth = 7392
| | 2)  ImageHeight = 4950
| | 3)  BitsPerSample = 14
| + [ExifIFD directory with 22 entries]
| + [MakerNotes directory with 121 entries]

< --- Frame #4 --->
+ [IFD3 directory with 38 entries]             < Thumbnail of frame #4 >
| 0)  SubfileType = 1
| 1)  ImageWidth = 160
| 2)  ImageHeight = 120
| 3)  BitsPerSample = 8 8 8
| + [SubIFD directory with 26 entries]               < Raw image of frame #2 >
| | 0)  SubfileType = 0
| | 1)  ImageWidth = 7392
| | 2)  ImageHeight = 4950
| | 3)  BitsPerSample = 14
| + [ExifIFD directory with 22 entries]
| + [MakerNotes directory with 121 entries]
```

and **Exiv2**

```
< Frame #1 OK>
Exif.Image.NewSubfileType                    Long        1  Thumbnail/Preview image
Exif.Image.ImageWidth                        Long        1  160
Exif.Image.ImageLength                       Long        1  120
Exif.Image.BitsPerSample                     Short       3  8 8 8
Exif.SubImage1.NewSubfileType                Long        1  Primary image
Exif.SubImage1.ImageWidth                    Long        1  7392
Exif.SubImage1.ImageLength                   Long        1  4950
Exif.SubImage1.BitsPerSample                 Short       1  14
Exif.SubImage2.NewSubfileType                Long        1  Thumbnail/Preview image
Exif.SubImage2.ImageWidth                    Long        1  7360
Exif.SubImage2.ImageLength                   Long        1  4912
Exif.SubImage2.BitsPerSample                 Short       3  8 8 8

< Frame #2 : Why Thumbnail and not Image here ? >
Exif.Thumbnail.NewSubfileType                Long        1  Thumbnail/Preview image
Exif.Thumbnail.ImageWidth                    Long        1  160
Exif.Thumbnail.ImageLength                   Long        1  120
Exif.Thumbnail.BitsPerSample                 Short       3  8 8 8
Exif.SubThumb1.NewSubfileType                Long        1  Primary image
Exif.SubThumb1.ImageWidth                    Long        1  7392
Exif.SubThumb1.ImageLength                   Long        1  4950
Exif.SubThumb1.BitsPerSample                 Short       1  14

< Frame #3 : only read the main section >
Exif.Image2.NewSubfileType                   Long        1  Thumbnail/Preview image
Exif.Image2.ImageWidth                       Long        1  160
Exif.Image2.ImageLength                      Long        1  120
Exif.Image2.BitsPerSample                    Short       3  8 8 8

< Frame #4 : only read the main section >
Exif.Image3.NewSubfileType                   Long        1  Thumbnail/Preview image
Exif.Image3.ImageWidth                       Long        1  160
Exif.Image3.ImageLength                      Long        1  120
Exif.Image3.BitsPerSample                    Short       3  8 8 8
```

The Exiftool panel will then be misleading in those special cases, however the main use of that panel is edting the essential metadata, so I guess we can let go as is.

**Comment by Lawrence37** [comment]
Thanks @Hombre57. It's one of the tradeoffs I hope will be worth it in the long run.

Now, for the long-awaited merge... :crossed_fingers:
