### PR TITLE
Fix TileOffsets for DNGs containing one tile

### LINKED ISSUE #6575: Single tiled deflate compressed DNGs not decoded properly
**Short description**

I just tried opening a DNG using deflate compression with only one tile. If fails miserably since `tile_length` is set to INT_MAX before reaching this if statement:
https://github.com/Beep6581/RawTherapee/blob/2ce5b827c5fa39b2b5425303f79f28b78f3df4f4/rtengine/dcraw.cc#L10906

**Steps to reproduce**
1. Open the [attached DNG](https://github.com/Beep6581/RawTherapee/files/9490364/float32deflate.zip) (with the latest commit on dev)
3. Notice how you only get an image containing zeros since (since `tile_offset`, `tile_length`, and `tile_width` are messed up)

This is were things get messed up:
https://github.com/Beep6581/RawTherapee/blob/2ce5b827c5fa39b2b5425303f79f28b78f3df4f4/rtengine/dcraw.cc#L6551-L6554

Followed by:
https://github.com/Beep6581/RawTherapee/blob/2ce5b827c5fa39b2b5425303f79f28b78f3df4f4/rtengine/dcraw.cc#L7065-L7066

**Expected behavior**

The [attached image](https://github.com/Beep6581/RawTherapee/files/9490364/float32deflate.zip) should be decoded properly.

**Additional information**
Version: 5.8-3139-g2ce5b827c
Branch: dev
Commit: 2ce5b827c
Commit date: 2022-08-30
Compiler: cc 10.2.1
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: V3.24.2
Lensfun: V0.3.2.0
Build type: release
Build flags:  -std=c++11 -march=native -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON
Build OS: Linux 5.10.0-16-amd64 x86_64
Build date: Mon, 05 Sep 2022 09:39:15 +0000 UTC
Build epoch: 1662370755
Build UUID:

### PR DESCRIPTION
**Pull request by SimonSegerblomRex**
The old code looks messed up.

Fixes #6575

### CODE REVIEW

**Comment by SimonSegerblomRex** [comment]
Hmm, I got this working, but probably forgot to include some change here...

File: rtengine/dcraw.cc [hunk 1]
```diff
@@ -6549,9 +6549,7 @@ int CLASS parse_tiff_ifd (int base)
 	tiff_ifd[ifd].tile_length = getint(type);
 	break;
       case 324:				/* TileOffsets */
-	tiff_ifd[ifd].offset = len > 1 ? ftell(ifp) : get4();
-	if (len == 1)
-	  tiff_ifd[ifd].tile_width = tiff_ifd[ifd].tile_length = 0;
+	tiff_ifd[ifd].offset = len > 1 ? ftell(ifp) : getint(type);
```
Comment (SimonSegerblomRex) [inline rtengine/dcraw.cc]: Seems like this needs to be changed to:
```suggestion
	tiff_ifd[ifd].offset = ftell(ifp);
```
I'll need to read the TIFF specification again...

Comment (SimonSegerblomRex) [reply rtengine/dcraw.cc]: ...no, this is wrong...

**Comment by SimonSegerblomRex** [comment]
At least this fixes the issues with decoding the file that I uploaded, but I'm not 100 % sure about what's happening... Let me know if you have any image files for regression testing.

File: rtengine/dcraw.cc [hunk 2]
```diff
@@ -6550,8 +6550,6 @@ int CLASS parse_tiff_ifd (int base)
 	break;
       case 324:				/* TileOffsets */
 	tiff_ifd[ifd].offset = len > 1 ? ftell(ifp) : get4();
-	if (len == 1)
-	  tiff_ifd[ifd].tile_width = tiff_ifd[ifd].tile_length = 0;
```
Comment (SimonSegerblomRex) [inline rtengine/dcraw.cc:6554]: Removing this will affect the logic here:
https://github.com/Beep6581/RawTherapee/blob/2ce5b827c5fa39b2b5425303f79f28b78f3df4f4/rtengine/dcraw.cc#L7065-L7066
...but I'm not sure why you would like to set `tile_width`/`tile_length` to 0 or INT_MAX...

Comment (SimonSegerblomRex) [reply rtengine/dcraw.cc:6554]: Seems like this breaks lossless JPEG decoding for some reason...

Comment (SimonSegerblomRex) [reply rtengine/dcraw.cc:6554]: Removing
https://github.com/Beep6581/RawTherapee/blob/2ce5b827c5fa39b2b5425303f79f28b78f3df4f4/rtengine/dcraw.cc#L1136-L1137
seems to solve the problem for lossless JPEG encoded single tiled DNGs, but will at the same break things for some multi-tiled images...

It might also be worth looking into the logic deciding between the two functions `lossless_jpeg_load_raw` and `lossless_dng_load_raw`.

**Comment by SimonSegerblomRex** [comment]
At least [this image](https://raw.pixls.us/getfile.php/970/nice/Blackmagic%20-%20URSA%204K%20-%2012bit%20(16:9).dng) works again with the latest patch set.

EDIT: [This image](https://raw.pixls.us/getfile.php/1024/nice/Adobe%20DNG%20Converter%20-%20Canon%20EOS%205D%20Mark%20III%20-%2016bit%20Lossless%20JPEG%20compression%20(3:2).DNG) is also fine.

**Comment by Thanatomanic** [comment]
I must say, you're a brave man trying to disect and change `dcraw.cc` code! I will need some time to do proper checking here, especially since this code is embedded deep in the bowels of the beast, so to speak...

**Comment by SimonSegerblomRex** [comment]
> I must say, you're a brave man trying to disect and change `dcraw.cc` code! I will need some time to do proper checking here, especially since this code is embedded deep in the bowels of the beast, so to speak...

Yes, we need to be really careful... I'm not even sure if this problem is related to the singled tiled nature of the image I uploaded or something else. At least I think this change will only affect images were `tile_length` was set to INT_MAX (after first being set to 0...). There is one more occurrence of `tile_length < INT_MAX` that we might need to update.

**Comment by ValZapod** [comment]
> EDIT: [This image](https://raw.pixls.us/getfile.php/1024/nice/Adobe%20DNG%20Converter%20-%20Canon%20EOS%205D%20Mark%20III%20-%2016bit%20Lossless%20JPEG%20compression%20(3:2).DNG) is also fine.

On this image ffplay warns:  https://github.com/FFmpeg/FFmpeg/blob/73fada029c527fda6c248785a948c61249fd4b2d/libavcodec/tiff.c#L1894

Tiled TIFF is not allowed to strip

**Comment by ZaquL** [comment]
> At least [this image](https://raw.pixls.us/getfile.php/970/nice/Blackmagic%20-%20URSA%204K%20-%2012bit%20(16:9).dng) works again with the latest patch set.

That one does work if you rename it .dng

**Comment by Beep6581** [comment]
Tagging this for 6.0 as it touches radioactive elements. Let's merge as soon as 5.10 is out to allow as much time for testing as possible.

**Comment by Beep6581** [comment]
@SimonSegerblomRex can you provide a list of affected cameras?

**Comment by SimonSegerblomRex** [comment]
> @SimonSegerblomRex can you provide a list of affected cameras?

I actually don't know of any cameras affected by the bug that I tried to fix here, but a lot of cameras could potentially be affected by this change, so I would be really careful merging this without thorough regression testing. Maybe it's better to convert this pull request to draft.

**Comment by Lawrence37** [comment]
5.10 has just been released. Now is a good time to merge if this is ready for broader testing.

**Comment by Lawrence37** [comment]
@SimonSegerblomRex There is plenty of time until the next release and LibRaw is the default decoder. Are you comfortable with merging this to `dev`?

**Comment by SimonSegerblomRex** [comment]
> @SimonSegerblomRex There is plenty of time until the next release and LibRaw is the default decoder. Are you comfortable with merging this to `dev`?

Yes, I think it's ok to merge this to dev. I have tested this patch with quite a few files without finding any regressions.

**Comment by SimonSegerblomRex** [comment]
I spent some more time today verifying that this patch actually fixes this use-case not only for images compressed using my own TIFF encoder, but also for images compressed using [tifffile](https://github.com/cgohlke/tifffile) (with the options:
```python3
with tifffile.TiffWriter("test.dng") as tif:
    tif.write(
        (image,),
        compression=8,
        shape=(height, width),
        tile=(height, width),
        compression=8,
        dtype="float32",
        bitspersample=32,
        predictor=34894,
        ...
```
)
