### PR TITLE
Fix linking with jpeg-turbo

### LINKED ISSUE #7074: Build fails with libjpeg-turbo 3.0.3: Undefined symbols for architecture x86_64: "_jpeg_std_message_table"
Looks that `libjpeg-turgo` changed API in 3.0.3, and this code now does not work:
https://github.com/Beep6581/RawTherapee/blob/5a25619bd50d42059abe9818420f639b6d10e3bf/rtengine/jdatasrc.cc#L251-L262

Windows build has this issue years ago: https://github.com/Beep6581/RawTherapee/issues/4713
Now identical linking failure on macOS: https://build.macports.org/builders/ports-14_x86_64-builder/builds/39199/steps/install-port/logs/stdio

This compiles though:
```
const char * const jpeg_std_message_table[] = {
#include "jerror.h"
  NULL
};
```
(Functionality not tested.)

### PR DESCRIPTION
**Pull request by Benitoite**
Fixes https://github.com/Beep6581/RawTherapee/issues/7074
This patch via Termux PR
https://github.com/termux-user-repository/tur/pull/1027

### CODE REVIEW

File: rtengine/jdatasrc.cc [hunk 1]
```diff
@@ -409,24 +395,14 @@ reset_error_mgr (j_common_ptr cinfo)
...
 my_jpeg_std_error (struct jpeg_error_mgr * err)
 {
+    err = jpeg_std_error(err);
 
+    /* override these functions */
     err->error_exit = my_error_exit;
     err->emit_message = emit_message;
     err->output_message = output_message;
     err->format_message = format_message;
     err->reset_error_mgr = reset_error_mgr;
```
Comment (Lawrence37) [inline rtengine/jdatasrc.cc]: It seems to me `my_error_exit` is the only customized function. The other ones are exact copies of the ones in libjpeg-turbo and are already added to the `err` struct by `jpeg_std_error()`. Thus, the only thing this function (`my_jpeg_std_error`) needs to do is call `jpeg_std_error()` then override the `error_exit` function. The copied functions can be removed from this file.

```suggestion
    err = jpeg_std_error(err);

    /* override these functions */
    err->error_exit = my_error_exit;
```

**Comment by Lawrence37** [comment]
Thank you @Benitoite.
