### PR TITLE
Fix static initialization order fiasco crashes

### LINKED ISSUE #7052: [32-bit ppc/i386] Advice needed to fix GUI binary, which crashes on launch with `KERN_INVALID_ADDRESS at 0x00000000fffffffc` (CLI binary works)
Could someone help me a bit? I got 5.10 built on macOS PowerPC and CLI converter seems working (I was able to throw a PEF at it and get a jpeg), but GUI crashes on launch:
```
Process:         rawtherapee [52993]
Path:            /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_graphics_rawtherapee/rawtherapee/work/destroot/opt/local/bin/rawtherapee
Identifier:      rawtherapee
Version:         ??? (???)
Code Type:       PPC (Native)
Parent Process:  zsh [18477]

Date/Time:       2024-04-22 08:44:22.756 +0800
OS Version:      Mac OS X 10.6 (10A190)
Report Version:  6

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x00000000fffffffc
Crashed Thread:  0

Thread 0 Crashed:
0   libstdc++.6.dylib             	0x044c9aa8 std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Rep::_M_is_leaked() const + 0
1   libglibmm-2.4.1.dylib         	0x02766c88 __ZNSsC4ERKSs.isra.0 + 28
2   rawtherapee                   	0x00017584 rtengine::procparams::ColorManagementParams::ColorManagementParams() + 356
3   rawtherapee                   	0x00b1f5c4 _GLOBAL__sub_I_histogrampanel.cc + 84 (histogrampanel.cc:42)
4   dyld                          	0x8fe15d5c ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&) + 388
5   dyld                          	0x8fe0f708 ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int) + 368
6   dyld                          	0x8fe0f800 ImageLoader::runInitializers(ImageLoader::LinkContext const&) + 60
7   dyld                          	0x8fe02704 dyld::initializeMainExecutable() + 132
8   dyld                          	0x8fe0868c dyld::_main(mach_header const*, unsigned long, int, char const**, char const**, char const**) + 3428
9   dyld                          	0x8fe017c8 dyldbootstrap::start(mach_header const*, int, char const**, long) + 952
10  dyld                          	0x8fe01060 _dyld_start + 56

Thread 0 crashed with PPC Thread State 32:
  srr0: 0x044c9aa8  srr1: 0x0200f030   dar: 0xfffffffc dsisr: 0x40000000
    r0: 0x02766c8c    r1: 0xbfffd170    r2: 0x0000018b    r3: 0xfffffff4
    r4: 0x00000000    r5: 0x00b17438    r6: 0x00b17438    r7: 0x00000001
    r8: 0x00be7438    r9: 0x00b17438   r10: 0xbfe6b0dd   r11: 0x42000408
   r12: 0x044c9aa8   r13: 0x8fe37930   r14: 0x8fe336bc   r15: 0x8fe37930
   r16: 0x0001dca0   r17: 0x8fe34d60   r18: 0x8fe2b954   r19: 0x00000037
   r20: 0x8fe36a24   r21: 0x00000002   r22: 0x0000158c   r23: 0x000012f0
   r24: 0x8fe33ca0   r25: 0x000000b9   r26: 0x00be501c   r27: 0x8fe33c48
   r28: 0x0000136c   r29: 0x00da4400   r30: 0xfffffff4   r31: 0x00017438
    cr: 0x42000402   xer: 0x00000000    lr: 0x02766c8c   ctr: 0x044c9aa8
vrsave: 0x00000000

Binary Images:
    0x1000 -   0xbe4feb +rawtherapee ??? (???) <3f62f5f4f11852828822223dbb404ce5> /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_graphics_rawtherapee/rawtherapee/work/destroot/opt/local/bin/rawtherapee
 0x1172000 -  0x117afff +libcanberra-gtk3.0.dylib ??? (???) <43e855b5d0d7746cd0b6b16dcd8c19f2> /opt/local/lib/libcanberra-gtk3.0.dylib
 0x117d000 -  0x127bffc +libX11.6.dylib ??? (???) <8208a1cefe7d0ac2c54309a6017211ae> /opt/local/lib/libX11.6.dylib
 0x1295000 -  0x12a0fff +libcanberra.0.dylib ??? (???) <7aaa7de13fd96f5438193e535315ae5c> /opt/local/lib/libcanberra.0.dylib
 0x12a5000 -  0x1930ffb +libgtk-3.0.dylib ??? (???) <13d299bfe60dc3e83e18fce0a7f42258> /opt/local/lib/libgtk-3.0.dylib
 0x1bd3000 -  0x1c5effb +libgdk-3.0.dylib ??? (???) <a75d346dd63eadad11e487074fbcd6e3> /opt/local/lib/libgdk-3.0.dylib
 0x1ca3000 -  0x1cafffb +libpangocairo-1.0.0.dylib ??? (???) <2a305d48622594d12c23eb2413e9daaf> /opt/local/lib/libpangocairo-1.0.0.dylib
 0x1cb8000 -  0x1d01ffb +libpango-1.0.0.dylib ??? (???) <a25f404245ce49548d1cb6c2f895e77c> /opt/local/lib/libpango-1.0.0.dylib
 0x1d2c000 -  0x1de9ffb +libharfbuzz.0.dylib ??? (???) <8d27014f96f8b21c1addc1764b91e46a> /opt/local/lib/libharfbuzz.0.dylib
 0x1e26000 -  0x1e43fff +libatk-1.0.0.dylib ??? (???) <8b77ff2e9c46138fce98cc93803dd711> /opt/local/lib/libatk-1.0.0.dylib
 0x1e5b000 -  0x1e63ffc +libcairo-gobject.2.dylib ??? (???) <538c11107798851db239410f56e654a7> /opt/local/lib/libcairo-gobject.2.dylib
 0x1e67000 -  0x1f4cfff +libcairo.2.dylib ??? (???) <3864121d34b80c3bf592f1b1eb94c32e> /opt/local/lib/libcairo.2.dylib
 0x1f78000 -  0x1f9afff +libgdk_pixbuf-2.0.0.dylib ??? (???) <f8a17793b54aa4668f2a45f18bbb61d3> /opt/local/lib/libgdk_pixbuf-2.0.0.dylib
 0x1fad000 -  0x210effb +libgio-2.0.0.dylib ??? (???) <58338fb7c3961d60ba1d92c6d548e01f> /opt/local/lib/libgio-2.0.0.dylib
 0x2215000 -  0x2251fff +libgobject-2.0.0.dylib ??? (???) <c4a3bd56376b1d29c8ca07b996688a97> /opt/local/lib/libgobject-2.0.0.dylib
 0x227d000 -  0x2375ff7 +libglib-2.0.0.dylib ??? (???) <15c2b47be68f26ada6ffddadb0b454bb> /opt/local/lib/libglib-2.0.0.dylib
 0x23d6000 -  0x23effff +libintl.8.dylib ??? (???) <e614775697f80c705e9a5000be1a088a> /opt/local/lib/libintl.8.dylib
 0x23f5000 -  0x2420fff +libexpat.1.dylib ??? (???) <0281bd0cefe7d466bcad7a1747954d9a> /opt/local/lib/libexpat.1.dylib
 0x2427000 -  0x2576ff7 +libfftw3f.3.dylib ??? (???) <3487b92750db790001e1d1d089667d3c> /opt/local/lib/libfftw3f.3.dylib
 0x2594000 -  0x2598fff +libfftw3f_omp.3.dylib ??? (???) <ee9392164a8154172ee329846d4ee283> /opt/local/lib/libfftw3f_omp.3.dylib
 0x259c000 -  0x268afff +libgiomm-2.4.1.dylib ??? (???) <9ee9daca88a9d22bc2a7d85d979fd961> /opt/local/lib/libgiomm-2.4.1.dylib
 0x2742000 -  0x2789fff +libglibmm-2.4.1.dylib ??? (???) <09e6228784691a3e4fab32a4cb058453> /opt/local/lib/libglibmm-2.4.1.dylib
 0x27bc000 -  0x27bffff +libsigc-2.0.0.dylib ??? (???) <ef2816a369325b89e2c1d29ba4546eeb> /opt/local/lib/libsigc-2.0.0.dylib
 0x27c6000 -  0x27c7ffd +libgthread-2.0.0.dylib ??? (???) <7838c918a136d87514d931c916122796> /opt/local/lib/libgthread-2.0.0.dylib
 0x27ca000 -  0x29d5fff +libgtkmm-3.0.1.dylib ??? (???) <604ffced2968950b38427c49896c9290> /opt/local/lib/libgtkmm-3.0.1.dylib
 0x2d90000 -  0x2dbdfff +libatkmm-1.6.1.dylib ??? (???) <1fad2a93f12900f5207883738b126395> /opt/local/lib/libatkmm-1.6.1.dylib
 0x2dda000 -  0x2e0afff +libgdkmm-3.0.1.dylib ??? (???) <1a894ff936865e04e7be9233a2eae779> /opt/local/lib/libgdkmm-3.0.1.dylib
 0x2e51000 -  0x2e69fff +libpangomm-1.4.1.dylib ??? (???) <a3c23a496a5e479c207200bc7861e932> /opt/local/lib/libpangomm-1.4.1.dylib
 0x2e7e000 -  0x2e95fff +libcairomm-1.0.1.dylib ??? (???) <4d80c7304fae3196daf11d38d1e8409b> /opt/local/lib/libcairomm-1.0.1.dylib
 0x2ea7000 -  0x2eadffe +libiptcdata.0.dylib ??? (???) <de0ff93e165376050891f949f47c0814> /opt/local/lib/libiptcdata.0.dylib
 0x2eb3000 -  0x2f25fff +libjpeg.8.dylib ??? (???) <db769f8503fbe0a86ddd4f496558f6ff> /opt/local/lib/libjpeg.8.dylib
 0x2f2f000 -  0x2f75fff +liblcms2.2.dylib ??? (???) <a91197d01783f2dba6b465b1227eddc4> /opt/local/lib/liblcms2.2.dylib
 0x2f85000 -  0x2fabffb +libpng16.16.dylib ??? (???) <a2f7c02d2c79ca1ce7e0d7bc13c14d1c> /opt/local/lib/libpng16.16.dylib
 0x2fb2000 -  0x2fc5ffc +libz.1.dylib ??? (???) <b137603b6672e715558e6403b48f02ad> /opt/local/lib/libz.1.dylib
 0x2fc9000 -  0x3037ffb +libtiff.6.dylib ??? (???) <1b19caa843c9cdbd24b3291bc7ecc2e0> /opt/local/lib/libtiff.6.dylib
 0x3046000 -  0x305fff3 +liblensfun.1.dylib ??? (???) <476f9310b51c8c4fd808fbd2f25c1b98> /opt/local/lib/liblensfun.1.dylib
 0x3067000 -  0x3096ffa +librsvg-2.2.dylib ??? (???) <cea7924fe37bcb74c3524e4ccb153aea> /opt/local/lib/librsvg-2.2.dylib
 0x30a1000 -  0x3273ffb +libexiv2.27.dylib ??? (???) <db4e74618c1f91ae255641d911f93397> /opt/local/lib/libexiv2.27.dylib
 0x3353000 -  0x337dffb +libgomp.1.dylib ??? (???) <10cf78145ebd4566e69e263bc405d6c0> /opt/local/lib/libgcc/libgomp.1.dylib
 0x3384000 -  0x34e7ff7 +libstdc++.6.dylib ??? (???) <193a69f840df6803b931da7a8d644c57> /opt/local/lib/libgcc/libstdc++.6.dylib
 0x3565000 -  0x37bdfff  com.apple.Foundation 6.6 (711.1) <42ee053ddba592040925af9eb9542462> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
 0x3907000 -  0x390cff7 +libgcc_s.1.1.dylib ??? (???) <7f950a0be1f0ed57669bf0564e2534be> /opt/local/lib/libgcc/libgcc_s.1.1.dylib
 0x390f000 -  0x391afff  libgcc_s.1.dylib ??? (???) <1eb48ae6b07dcb096bda0433409722c1> /usr/lib/libgcc_s.1.dylib
 0x391f000 -  0x3ae9fe7  libSystem.B.dylib ??? (???) <420b38fe0fa0944f6f5bc4840bf29a4e> /usr/lib/libSystem.B.dylib
 0x3b71000 -  0x3cc9ff7  com.apple.CoreFoundation 6.6 (511.1) <b82d52070a5949f92c5001e06d67044b> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 0x3dd3000 -  0x3dd9fff +libvorbisfile.3.dylib ??? (???) <6dc1d59c326e991ca41ef8e9a299f7de> /opt/local/lib/libvorbisfile.3.dylib
 0x3ddd000 -  0x3de3ffd +libltdl.7.dylib ??? (???) <f4feb81f25254641c2ddf1138d4c85ec> /opt/local/lib/libltdl.7.dylib
 0x3de7000 -  0x3de8ff8  com.apple.ApplicationServices 36 (36) <8d5530987cce48c3375a350c7f134b9c> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
 0x3dfe000 -  0x3e01ffe +libgmodule-2.0.0.dylib ??? (???) <81f264a23f6e5a8f0068e45deb1b0bd3> /opt/local/lib/libgmodule-2.0.0.dylib
 0x3e05000 -  0x3e16fff +libpangoft2-1.0.0.dylib ??? (???) <5f0c242fc78e7ca3a8d56c4b20b20af4> /opt/local/lib/libpangoft2-1.0.0.dylib
 0x3e26000 -  0x3e5ffff +libfontconfig.1.dylib ??? (???) <11e37ced4af26fd3aafb0a4d1c4cfbbc> /opt/local/lib/libfontconfig.1.dylib
 0x3e69000 -  0x3e83fff +libfribidi.0.dylib ??? (???) <e8e72c4a679647cc021c37d950f52d89> /opt/local/lib/libfribidi.0.dylib
 0x3e86000 -  0x3f1cfff +libepoxy.0.dylib ??? (???) <ae79219b0112f886c5901584e8e060bd> /opt/local/lib/libepoxy.0.dylib
 0x401a000 -  0x4027fff +libXi.6.dylib ??? (???) <46f489e7551553ad6c06b9614d1cc89b> /opt/local/lib/libXi.6.dylib
 0x402b000 -  0x404efff +libatk-bridge-2.0.0.dylib ??? (???) <99a4d17266d6984303182af173bdbcc5> /opt/local/lib/libatk-bridge-2.0.0.dylib
 0x4066000 -  0x406afff +libXfixes.3.dylib ??? (???) <506fbea86a7fb28e5d287c52ba21a95a> /opt/local/lib/libXfixes.3.dylib
 0x406d000 -  0x407afff +libXext.6.dylib ??? (???) <61bd4715fd902b83b34a7461159cabad> /opt/local/lib/libXext.6.dylib
 0x407f000 -  0x4086fff +libXcursor.1.dylib ??? (???) <9d5686a8e320e3376a270371b7f4ec35> /opt/local/lib/libXcursor.1.dylib
 0x408a000 -  0x408cffe +libXdamage.1.dylib ??? (???) <9925bbf068d405dfc9359a9d57b225da> /opt/local/lib/libXdamage.1.dylib
 0x408f000 -  0x4091ffd +libXcomposite.1.dylib ??? (???) <fbadbb5f96a07858725e4a625aa1dcd4> /opt/local/lib/libXcomposite.1.dylib
 0x4094000 -  0x409cfff +libXrandr.2.dylib ??? (???) <d11127c3ab6a16d12f65d2d1cef0d203> /opt/local/lib/libXrandr.2.dylib
 0x409f000 -  0x40a1ffc +libXinerama.1.dylib ??? (???) <ac1ee030eb34d1a5a06e982dc516fbfe> /opt/local/lib/libXinerama.1.dylib
 0x40a4000 -  0x41a9fff +libiconv.2.dylib ??? (???) <71dfab8f77eb71baebdb38550a0ed408> /opt/local/lib/libiconv.2.dylib
 0x41b8000 -  0x41b8ffa  com.apple.CoreServices 41 (41) <97bf3903384c706ba0f7d19577f0ef8c> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
 0x41ce000 -  0x41d3ff6  libmathCommon.A.dylib ??? (???) <e166c8e59a80a82b4504b1dd43d1f50a> /usr/lib/system/libmathCommon.A.dylib
 0x41d7000 -  0x420aff1  libauto.dylib ??? (???) <2848423526fb9c0f381c6ceacc4f2c27> /usr/lib/libauto.dylib
 0x4216000 -  0x439ffff  libicucore.A.dylib ??? (???) <28f339176d9e26b663f19c1cad91784e> /usr/lib/libicucore.A.dylib
 0x43ef000 -  0x4470fe7  libobjc.A.dylib ??? (???) <bb09ce82013fa9c4a4010c58fe6c1e10> /usr/lib/libobjc.A.dylib
 0x4482000 -  0x4490fff  libz.1.dylib ??? (???) <c296d00fd65aa7271f3d5592c25c0f96> /usr/lib/libz.1.dylib
 0x4495000 -  0x44ffffb  libstdc++.6.dylib ??? (???) <5824de0c43054a01c556e9ef288f33c7> /usr/lib/libstdc++.6.dylib
 0x4549000 -  0x486fff7  com.apple.CoreServices.CarbonCore 818 (818) <3e631022aef7f9d15373e1f56e74ff00> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore
 0x48f8000 -  0x49b8ffb  com.apple.CFNetwork 417.1 (417.1) <911e0fa87591b77e8bb8ec4759941216> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
 0x4a20000 -  0x4a60fff  com.apple.Metadata 10.6.0 (429.1) <d8b50a8ca605800f8f36caf448daed42> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata
 0x4a79000 -  0x4b51fff  com.apple.CoreServices.OSServices 310 (310) <633ea4081155a516c80bf948f004d235> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices
 0x4bbc000 -  0x4c39ffb  com.apple.SearchKit 1.3.0 (1.3.0) <4c7ffa79c1cd48d28eb165768fbfc2f4> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SearchKit.framework/Versions/A/SearchKit
 0x4c78000 -  0x4cb0fff  com.apple.AE 464 (464) <492b7cdb81e64fca5af300b0c231ebec> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE
 0x4cc8000 -  0x4d5fff7  com.apple.LaunchServices 318.1 (318.1) <5ee43f629f636d1863e73dc312c736c2> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices
 0x4da5000 -  0x4dc8fff  com.apple.DictionaryServices 1.0.0 (1.0.0) <f2f1f85469f3036ec9890bfa888edbe2> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/DictionaryServices
 0x4dde000 -  0x4e34ff3  com.apple.framework.IOKit 1.5.1 (???) <21f9b751b7578a33306804af2c6ded8d> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
 0x4e4d000 -  0x4e56fff  com.apple.DiskArbitration 2.2.1 (2.2.1) <daa422fc5a934366c8f0a12204b46cb1> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
 0x4e5f000 -  0x4e71fff  libbsm.0.dylib ??? (???) <c43c47af4211639e8828d3e8ff93a019> /usr/lib/libbsm.0.dylib
 0x4e77000 -  0x4e84ffe  NetFS ??? (???) <5125b2c825637b243afa1ea942ba8220> /System/Library/Frameworks/NetFS.framework/Versions/A/NetFS
 0x4e8b000 -  0x4e94ffc  libkxld.dylib ??? (???) <725cd6e644549962b0110493f4bb7c08> /usr/lib/system/libkxld.dylib
 0x4e98000 -  0x50c6ff7  com.apple.security 6.0 (34772) <df4f0710dfee6e04e7fdba557064977b> /System/Library/Frameworks/Security.framework/Versions/A/Security
 0x51dd000 -  0x528eff7  libsqlite3.0.dylib ??? (???) <cc6135a5433e43988bf825e149e47483> /usr/lib/libsqlite3.0.dylib
 0x529a000 -  0x52d5fff  com.apple.SystemConfiguration 1.10 (1.10) <2daf422a1a7ca90ba32720000e56b3aa> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
 0x52f1000 -  0x531dfff  libxslt.1.dylib ??? (???) <da4552da93bf856897f6b399bb10806d> /usr/lib/libxslt.1.dylib
 0x5326000 -  0x5441fff  libxml2.2.dylib ??? (???) <2bdb2ca8d4aabba550ba9f2111ebf46a> /usr/lib/libxml2.2.dylib
 0x5464000 -  0x546afff +libMacportsLegacySupport.dylib ??? (???) <95200f933bfbcb561128ab18dd2db51b> /opt/local/lib/libMacportsLegacySupport.dylib
 0x546e000 -  0x54f1ffe +libpcre2-8.0.dylib ??? (???) <d3c6858763646927f568cbe4e06e99f4> /opt/local/lib/libpcre2-8.0.dylib
 0x54f6000 -  0x54fcff7 +libffi.8.dylib ??? (???) <add3c4427db4e056068e049a433ab42b> /opt/local/lib/libffi.8.dylib
 0x54ff000 -  0x551ffff  libresolv.9.dylib ??? (???) <2b57f734cfd1eb7ebf2eb9a4bbbc5a23> /usr/lib/libresolv.9.dylib
 0x5528000 -  0x5584ff3 +libpixman-1.0.dylib ??? (???) <fdcc607fe277d8904f0bcce37d2fb323> /opt/local/lib/libpixman-1.0.dylib
 0x55a9000 -  0x563fffc +libfreetype.6.dylib ??? (???) <fb0d4dd6d5834105c5513e3752ba29c9> /opt/local/lib/libfreetype.6.dylib
 0x5657000 -  0x5657fff +libX11-xcb.1.dylib ??? (???) <a3d49e554a3b1696f7d393af4b8192bb> /opt/local/lib/libX11-xcb.1.dylib
 0x565a000 -  0x566fffe +libxcb.1.dylib ??? (???) <c9cfffe71e61cc106c75aaddb18a6327> /opt/local/lib/libxcb.1.dylib
 0x567b000 -  0x5681ffe +libxcb-render.0.dylib ??? (???) <98f2e99de82b98e43ef3d9854ce55825> /opt/local/lib/libxcb-render.0.dylib
 0x5687000 -  0x568efff +libXrender.1.dylib ??? (???) <b1ebb3eedaa4f8f3dc17e4193460555d> /opt/local/lib/libXrender.1.dylib
 0x5691000 -  0x569fff5 +libbz2.1.0.dylib ??? (???) <561eabf373907c3899487650867150dc> /opt/local/lib/libbz2.1.0.dylib
 0x56a3000 -  0x56adffd +libbrotlidec.1.dylib ??? (???) <3b0762d3ef2c19b08f78da5664895226> /opt/local/lib/libbrotlidec.1.dylib
 0x56b0000 -  0x56d0ffc +libbrotlicommon.1.dylib ??? (???) <813aa6ca2e727bab74f2ca8ac1bad64d> /opt/local/lib/libbrotlicommon.1.dylib
 0x56d3000 -  0x56d4ffc +libXau.6.dylib ??? (???) <e68c7e2d4490bcf51a71d84e19814e24> /opt/local/lib/libXau.6.dylib
 0x56d7000 -  0x56dafff +libXdmcp.6.dylib ??? (???) <6a871e87ffc66f5dabe23e43c35d6325> /opt/local/lib/libXdmcp.6.dylib
 0x56dd000 -  0x5778fff  com.apple.ApplicationServices.ATS 4.0 (???) <4210dabffcc1cafdf05b6a22996a4eb6> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/ATS
 0x579f000 -  0x5873ff7  com.apple.ColorSync 4.6.0 (4.6.0) <c4746bb1c5e21b1ff1ee9e23150dae91> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ColorSync.framework/Versions/A/ColorSync
 0x58b2000 -  0x5f19ff7  com.apple.CoreGraphics 1.507.2 (???) <dc83caa82d24f470958a99ca6e198a2f> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
 0x5fe0000 -  0x6043fff  com.apple.CoreText 3.0.0 (???) <367767da30e7fda6ac4302fc54116f29> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/CoreText.framework/Versions/A/CoreText
 0x607c000 -  0x60d5fff  com.apple.HIServices 1.7.0 (???) <4e20ca5a0f021908e274610eab85af23> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/A/HIServices
 0x6101000 -  0x62acffb  com.apple.ImageIO.framework 3.0.0 (3.0.0) <840a13dc20c1c1a1ed50edef6d706239> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ImageIO.framework/Versions/A/ImageIO
 0x6319000 -  0x632cfff  com.apple.LangAnalysis 1.6.5 (1.6.5) <e7713c1bde76548000a0a0e7b9f27324> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/LangAnalysis.framework/Versions/A/LangAnalysis
 0x6339000 -  0x63e9ffb  com.apple.QD 3.18 (???) <f6b3db0d330e0268a24dc5e3fdb820a5> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/QD.framework/Versions/A/QD
 0x6418000 -  0x642bffb  com.apple.speech.synthesis.framework 3.10.1 (3.10.1) <67907b42aecf8e5cef273ce5085f19b5> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/SpeechSynthesis.framework/Versions/A/SpeechSynthesis
 0x643a000 -  0x6471fff  libFontParser.dylib ??? (???) <e83c633b4e6ac7de6acfa5edbe925f7a> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontParser.dylib
 0x649f000 -  0x6582ff3  libcrypto.0.9.8.dylib ??? (???) <90068ab1dc24a941bdd01726024c515d> /usr/lib/libcrypto.0.9.8.dylib
 0x65d3000 -  0x65d3fff  com.apple.Accelerate 1.4.2 (Accelerate 1.4.2) <e8c929e9ed651c210e5238b66b947e6e> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
 0x65d7000 -  0x65f6fff  com.apple.vecLib 3.4.2 (vecLib 3.4.2) <9e27768a4224789f73942ddb2e03e729> /System/Library/Frameworks/vecLib.framework/Versions/A/vecLib
 0x6653000 -  0x6773ffa  com.apple.vImage 4.0 (4.0) <40c9ff1a236e54afc0af0dbe01d59ae0> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/vImage
 0x6782000 -  0x67a1fff  com.apple.Accelerate.vecLib 3.4.2 (vecLib 3.4.2) <c56e0d707296e54bceac01b6944e99e3> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib
 0x67fe000 -  0x6878fff  libvMisc.dylib ??? (???) <2607b58a270aca106281054e078194d1> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvMisc.dylib
 0x6882000 -  0x691ffe3  libvDSP.dylib ??? (???) <18d61ac588914626b88c2c2babb2ac25> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvDSP.dylib
 0x6939000 -  0x6fa6ff7  libBLAS.dylib ??? (???) <b09754bb15f771807655be04f5200efd> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
 0x6fe4000 -  0x737cff7  libLAPACK.dylib ??? (???) <7f1ccd1f986607cb24ada410c3548482> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib
 0x74f5000 -  0x7539ff3  libTIFF.dylib ??? (???) <7b0f8b579d3fd66175f0e695370c2232> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ImageIO.framework/Versions/A/Resources/libTIFF.dylib
 0x7544000 -  0x7548ffc  libGIF.dylib ??? (???) <ebdc74ca8b923dc8281d8644db5bf855> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ImageIO.framework/Versions/A/Resources/libGIF.dylib
 0x754d000 -  0x7568fff  libPng.dylib ??? (???) <ce17de27142c8af8406c282b45de241a> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ImageIO.framework/Versions/A/Resources/libPng.dylib
 0x756f000 -  0x7571fff  libRadiance.dylib ??? (???) <8c97d9ae80dd2661573bb62db798e710> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ImageIO.framework/Versions/A/Resources/libRadiance.dylib
 0x7575000 -  0x7597ff2  libJPEG.dylib ??? (???) <df09b8c643d8325deae52adf5818b338> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ImageIO.framework/Versions/A/Resources/libJPEG.dylib
 0x759e000 -  0x75ccfff  libcups.2.dylib ??? (???) <dfcb272c0281e5d2ec0f89f1f75f6d88> /usr/lib/libcups.2.dylib
 0x75d7000 -  0x75ecffe +libgraphite2.3.dylib ??? (???) <f50d8f8421e2c2482a832278e2253aa7> /opt/local/lib/libgraphite2.3.dylib
 0x75f5000 -  0x762dfff +libdbus-1.3.dylib ??? (???) <ea6bceac04ce6fdc86a44bf84a34d228> /opt/local/lib/libdbus-1.3.dylib
 0x763d000 -  0x765cfff +libatspi.0.dylib ??? (???) <b7355b187897fe2afc0342285323ef41> /opt/local/lib/libatspi.0.dylib
 0x7679000 -  0x769eff8 +libvorbis.0.dylib ??? (???) <ca879fc23aca93e86cff452f5d990253> /opt/local/lib/libvorbis.0.dylib
 0x76a6000 -  0x76abfff +libogg.0.dylib ??? (???) <333ad130bd17d2523596f3dbf6ad6c1e> /opt/local/lib/libogg.0.dylib
 0x76ae000 -  0x773dffb +libzstd.1.dylib ??? (???) <bb932d99a956d55e10b1189f300229d6> /opt/local/lib/libzstd.1.dylib
 0x7749000 -  0x776fffc +liblzma.5.dylib ??? (???) <03bc800fb47b9ef63899316e0156af75> /opt/local/lib/liblzma.5.dylib
 0x7775000 -  0x779fffb +libLerc.4.dylib ??? (???) <f223c9561fbccc5efad3e57d9b1f7075> /opt/local/lib/libLerc.4.dylib
 0x77ab000 -  0x77b5fff +libdeflate.0.dylib ??? (???) <a29d5ec592fb3cb6e64ccce96b170f3d> /opt/local/lib/libdeflate.0.dylib
 0x77b8000 -  0x77e1fff +libcroco-0.6.3.dylib ??? (???) <47151eba44a4abf133692fbdd606ad99> /opt/local/lib/libcroco-0.6.3.dylib
 0x77ef000 -  0x78fffff +libxml2.2.dylib ??? (???) <e64bc22d5d469ab1a3649e1a72591249> /opt/local/lib/libxml2.2.dylib
 0x7926000 -  0x7ae4ffb +libicui18n.74.dylib ??? (???) <cb340e3dec04d832ed5e4fb8d09b3fa7> /opt/local/lib/libicui18n.74.dylib
 0x7bd8000 -  0x7d28fff +libicuuc.74.dylib ??? (???) <13fd9d08463db337089d7c3b8b4fdd36> /opt/local/lib/libicuuc.74.dylib
 0x7d93000 -  0x9aeffff +libicudata.74.dylib ??? (???) <a11a64364b5f0f9fcaf3c4e3b2e68d73> /opt/local/lib/libicudata.74.dylib
0x20000000 - 0x2009efff  edu.mit.Kerberos 6.5.3 (6.5.3) <af8fd279b2ec6f91e99e82352f2541c9> /System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos
0x8fe00000 - 0x8fe31143  dyld 113.0 (???) <ee555e655e1cf66cac80728801add419> /usr/lib/dyld
0xfa100000 - 0xfa189ffb  com.apple.print.framework.PrintCore 6.0 (276) <049c93926212fa9408e9e56186970e4b> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/PrintCore.framework/Versions/A/PrintCore
0xffff8000 - 0xffff9703  libSystem.B.dylib ??? (???) /usr/lib/libSystem.B.dylib
```
It is likely this is NOT a bug in RawTherapee, but rather a consequence of using an unsupported presently Unix-like build on macOS. That is, I had to patch out Cocoa-specific chunks in a couple of source files (which uses `gtkosxapplication`).

It would be great though if this issue is not just closed as wontfix, since while Cocoa stuff is pretty broken on older macOS, GTK3 as such and X11 work fine and are well-tested in real applications. Also RawTherapee as such also works (conversion functionality at least).
So it could be a matter of a few minor tweaks, and we get the app working. People will be happy to have a modern RAW converter on PowerPC :)

Any suggestions are greatly appreciated. I realize that the hardware may not be available for testing, but making an educated guess can be nevertheless helpful. I can try any potential fixes on my end and provide logs and GDB output.

### LINKED ISSUE #7443: Segfault since gtkmm stack upgrade
**Short description**
Since gtkmm stack upgrade, rawtherapee segfault at startup. Not sure about the package that triggered the upgrade. But please see the stack trace below: I thing that there is an issue with default parameters. Patch proposal will follow.

**Steps to reproduce**
1. Update to gtkmm-3.24.10/pangomm-2.46.4/cairomm-1.14.5/atkmm-2.28.4/glibmm-2.66.8/libsigc++-2.12.1
2. Start rawtherapee, it’s segfault

**Expected behavior**
No segfault.

**Additional information**
Version: 5.12-8-g9f9b6ede8
Branch: dev
Commit: 9f9b6ede8
Commit date: 2025-06-15
Compiler: x86_64-pc-linux-gnu-gcc 15.1.0
Processor: 12th\ Gen\ Intel(R)\ Core(TM)\ i5-12500
System: Linux
Bit depth: 64 bits
Gtkmm: 3.24.10
Lensfun: 0.3.4.0
libjxl: Disabled
Build type: RelWithDebInfo
Build flags: -march=native -O3 -mtune=native -pipe -std=c++11 -ffp-contract=off  -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -flto -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas  -ftree-vectorize
Link flags: -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -Wl,--sort-common  -flto
OpenMP support: yes
MMAP support: ON
Build OS: Linux 6.15.4-gentoo x86_64
Build date: Fri, 27 Jun 2025 19:03:13 +0000 UTC
Build epoch: 1751050993
Build UUID: 3284c1d5-6afc-46bb-ad79-90bbf656ccbd

Other useful information:
```

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6fd6c20 in Glib::ustring::ustring(Glib::ustring const&) () from /usr/lib64/libglibmm-2.4.so.1
(gdb) bt
#0  0x00007ffff6fd6c20 in Glib::ustring::ustring(Glib::ustring const&) () at /usr/lib64/libglibmm-2.4.so.1
#1  0x00005555560ff9c2 in rtengine::procparams::ColorManagementParams::ColorManagementParams (this=0x55555669bdb0 <rtengine::params+4400>, this=<optimized out>) at /var/tmp/portage/media-gfx/rawtherapee-9999/work/rawtherapee-9999/rtengine/procparams.cc:2716
#2  0x0000555556114679 in rtengine::procparams::ProcParams::ProcParams (this=0x55555669ac80 <rtengine::params>, this=<optimized out>) at /var/tmp/portage/media-gfx/rawtherapee-9999/work/rawtherapee-9999/rtengine/procparams.cc:6617
#3  0x0000555555858955 in _sub_I_65535_0.0 ()
#4  0x00007ffff52515ef in __libc_start_main () at /usr/lib64/libc.so.6
#5  0x000055555585a4a5 in _start ()
```

```
(gdb) p options.rtSettings
$1 = {iccDirectory = {static npos = 18446744073709551615, string_ = ""}, viewingdevice = 0, viewingdevicegrey = 0, viewinggreySc = 0, leveldnv = 0, leveldnti = 0, leveldnaut = 0, leveldnliss = 0, leveldnautsimpl = 0, printerProfile = {static npos = 18446744073709551615, string_ = ""}, printerIntent = 0, 
  printerBPC = false, monitorProfile = {static npos = 18446744073709551615, string_ = ""}, monitorIntent = 0, monitorBPC = false, autoMonitorProfile = false, autocielab = false, rgbcurveslumamode_gamut = false, verbose = false, darkFramesPath = {static npos = 18446744073709551615, string_ = ""}, flatFieldsPath = {
    static npos = 18446744073709551615, string_ = ""}, cameraProfilesPath = {static npos = 18446744073709551615, string_ = ""}, lensProfilesPath = {static npos = 18446744073709551615, string_ = ""}, enableLibRaw = false, adobe = {static npos = 18446744073709551615, string_ = ""}, prophoto = {
    static npos = 18446744073709551615, string_ = ""}, widegamut = {static npos = 18446744073709551615, string_ = ""}, beta = {static npos = 18446744073709551615, string_ = ""}, best = {static npos = 18446744073709551615, string_ = ""}, bruce = {static npos = 18446744073709551615, string_ = ""}, srgb = {
    static npos = 18446744073709551615, string_ = ""}, rec2020 = {static npos = 18446744073709551615, string_ = ""}, ACESp0 = {static npos = 18446744073709551615, string_ = ""}, JDCmax = {static npos = 18446744073709551615, string_ = ""}, ACESp1 = {static npos = 18446744073709551615, string_ = ""}, DCIP3 = {
    static npos = 18446744073709551615, string_ = ""}, gamutICC = false, gamutLch = false, HistogramWorking = false, amchroma = 0, amchromajz = 0, protectred = 0, protectredh = 0, nrauto = 0, nrautomax = 0, nrhigh = 0, nrwavlevel = 0, daubech = false, ciebadpixgauss = false, CRI_color = 0, denoiselabgamma = 0, 
  level0_cbdl = 0, level123_cbdl = 0, lensfunDbDirectory = {static npos = 18446744073709551615, string_ = ""}, lensfunDbBundleDirectory = {static npos = 18446744073709551615, string_ = ""}, cropsleep = 0, reduchigh = 0, reduclow = 0, detectshape = false, fftwsigma = false, previewselection = 0, cbdlsensi = 0, 
  itcwb_enable = false, itcwb_deltaspec = 0, itcwb_powponder = 0, basecorlog = 0, edghi = 0, edglo = 0, limrad = 0, thumbnail_inspector_mode = rtengine::Settings::ThumbnailInspectorMode::JPEG, xmp_sidecar_style = rtengine::Settings::XmpSidecarStyle::STD, metadata_xmp_sync = rtengine::Settings::MetadataXmpSync::NONE}
(gdb) p options.rtSettings.srgb
$2 = {static npos = 18446744073709551615, string_ = ""}
```

### PR DESCRIPTION
**Pull request by digitalcarp**
Moves several extern variables behind a `App::get()` singleton. The singleton is implemented as a Meyer's singleton for thread safety and defined initialization order.

The most "noisy" change is changing `options` extern global to `App::get().options()`. For places where `options` is changed, `mut_options()` is called instead.

Fixes #7443

Edit: Also fixes #7052 hopefully

### CODE REVIEW

File: rtgui/filecatalog.cc [hunk 1]
```diff
@@ -48,6 +48,83 @@
 
 using namespace std;
 
+namespace {
+
+void getFilesRecursively(
```
Comment (digitalcarp) [inline rtgui/filecatalog.cc:53]: This was moved from a lambda later in the file. The lambda was difficult to read due to C++11 not having elegant recursive lambdas. It also got in the way of the `options` change.

File: rtgui/filepanel.cc [hunk 2]
```diff
@@ -206,17 +208,18 @@ void FilePanel::init ()
     dirBrowser->fillDirTree ();
     placesBrowser->refreshPlacesList ();
 
-    if (!argv1.empty() && Glib::file_test (argv1, Glib::FILE_TEST_EXISTS)) {
-        Glib::ustring d(argv1);
+    if (!App::get().argv0().empty() && Glib::file_test (App::get().argv1(), Glib::FILE_TEST_EXISTS)) {
```
Comment (Lawrence37) [inline rtgui/filepanel.cc]: This was `argv1`.

```suggestion
    if (!App::get().argv1().empty() && Glib::file_test (App::get().argv1(), Glib::FILE_TEST_EXISTS)) {
```

File: rtgui/main.cc [hunk 3]
```diff
@@ -134,18 +128,18 @@ int processLineParams ( int argc, char **argv )
...
 #endif
 
                 case 'g':
                     if (currParam == "-gimp") {
-                        gimpPlugin = true;
-                        simpleEditor = true;
-                        remote = false;
+                        app.setIsGimpPlugin(true);
+                        app.setIsSimpleEditor(true);
+                        app.setIsRemote(true);
```
Comment (Lawrence37) [inline rtgui/main.cc]: Remote was `false`.
```suggestion
                        app.setIsRemote(false);
```

File: rtgui/filepanel.cc (hunk 2 above)
Comment (digitalcarp) [reply rtgui/filepanel.cc]: Oof good catch. Fixed

File: rtgui/main.cc (hunk 3 above)
Comment (digitalcarp) [reply rtgui/main.cc]: Fixed

**Review by Lawrence37 — APPROVED** [review]
