### PR TITLE
Fix a couple of warnings

### LINKED ISSUE #6886: ColorManagementParams previously declared as a struct
When building release-5.10 with PR#6853:
Compilation with AppleClang 13, where ColorManagementParams is used as both a class and a struct, which doesnt seem to affect things on mac, but might not work on windows if using microsoft. I can see how this usage works, but the MS linker may be stricter in this regard, due to the tag mismatch as indicated below.

````
In file included from /Users/rb/repo-rt/rtgui/filepanel.cc:23:
In file included from /Users/rb/repo-rt/rtgui/editorpanel.h:25:
In file included from /Users/rb/repo-rt/rtgui/histogrampanel.h:32:
/Users/rb/repo-rt/rtgui/pointermotionlistener.h:31:1: warning: class 'ColorManagementParams' was previously declared as a struct; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Wmismatched-tags]
class ColorManagementParams;
^
/Users/rb/repo-rt/rtgui/../rtengine/procparams.h:1905:8: note: previous use is here
struct ColorManagementParams {
       ^
/Users/rb/repo-rt/rtgui/pointermotionlistener.h:31:1: note: did you mean struct here?
class ColorManagementParams;
^~~~~
struct
In file included from /Users/rb/repo-rt/rtgui/filepanel.cc:23:
In file included from /Users/rb/repo-rt/rtgui/editorpanel.h:27:
In file included from /Users/rb/repo-rt/rtgui/imageareapanel.h:21:
In file included from /Users/rb/repo-rt/rtgui/imagearea.h:24:
In file included from /Users/rb/repo-rt/rtgui/cropwindow.h:26:
In file included from /Users/rb/repo-rt/rtgui/crophandler.h:27:
/Users/rb/repo-rt/rtgui/lockablecolorpicker.h:33:1: warning: class 'ColorManagementParams' was previously declared as a class; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Wmismatched-tags]
class ColorManagementParams;
^
/Users/rb/repo-rt/rtgui/../rtengine/procparams.h:1905:8: note: previous use is here
struct ColorManagementParams {
       ^
/Users/rb/repo-rt/rtgui/lockablecolorpicker.h:33:1: note: did you mean struct here?
class ColorManagementParams;
^~~~~
struct
````

### PR DESCRIPTION
**Pull request by 0v3rt1r3d**
I've built rt in my environment and noticed a bunch of warnings. Some of them are easy to fix, and one of them seem to be important

### CODE REVIEW

File: rtengine/rawimagesource.cc [hunk 1]
```diff
@@ -5307,8 +5307,8 @@ void RawImageSource::ItcWB(bool extra, double &tempref, double &greenref, double
         Glib::ustring profuse;
         profuse = "JDCmax";
 
-        int limx = 0.05f;
-        int limy = 0.04f;
+        float limx = 0.05f;
```
Comment (0v3rt1r3d) [inline rtengine/rawimagesource.cc:5310]: It seems like the one of the algorithms introduced in #6643 didn't work well because of this convertion to 0 all the time

File: rtengine/iplocallab.cc [hunk 2]
```diff
@@ -13080,7 +13080,7 @@ void ImProcFunctions::Lab_Local(
 
     //avoidcolshi(lp, sp, transformed, reserved,  cy, cx, sk);
 
-    const float radius = lp.rad / (sk * 1.4); //0 to 70 ==> see skip
+    const double radius = lp.rad / (sk * 1.4); //0 to 70 ==> see skip
```
Comment (Lawrence37) [inline rtengine/iplocallab.cc]: `radius` is cast into a `double` in several places. Those casts can be removed. There's also a few places where `radius` is used where a `float` is expected. There should be casts there.

File: rtengine/rawimagesource.cc (hunk 1 above)
Comment (Lawrence37) [reply rtengine/rawimagesource.cc:5310]: @Desmis Does this behave well after the fix?

**Comment by Lawrence37** [comment]
Thanks for fixing these @0v3rt1r3d

**Comment by Desmis** [comment]
@Lawrence37 @0v3rt1r3d 
Thank you for this careful review. In Rawimagesource it's a big mistake on my part.

You must also change **'limy'** to float.

Just an explanation. These 2 'limx' and 'limy' controls aim to control the gamut in the extreme blues for the CIExy diagram. It's a bit redundant, but it's better this way.

jacques

File: rtengine/rawimagesource.cc (hunk 1 above)
Comment (0v3rt1r3d) [reply rtengine/rawimagesource.cc:5310]: solved ([comment](https://github.com/Beep6581/RawTherapee/pull/6873#issuecomment-1784014146))

File: rtengine/iplocallab.cc (hunk 2 above)
Comment (0v3rt1r3d) [reply rtengine/iplocallab.cc]: I spent some time trying to make correct convertion in all the places to make all the warnings disappear, but it's too complicated for now. These convertrtions double to float and vice versa happen so often and are mixed for most variables.

As for my taste, I would replace all the floats to double (or created a typealias and use it everywhere to have ability to choose float/double if it's needed)

I decided to revert my changes for this particular file for now

**Comment by 0v3rt1r3d** [comment]
Hi @Lawrence37, I guess this PR is ready to be reviewed again :)

**Review by Lawrence37 — APPROVED** [review]

**Comment by Lawrence37** [comment]
Merged! Thanks for your contribution @0v3rt1r3d.
