### PR TITLE
Selective Editing - compatibility 5.10 - Feather - Log encoding

### LINKED ISSUE #7113: Selective Editing feather gradient from 5.10 not applied
**Short description**
First noted here: https://github.com/Beep6581/RawTherapee/issues/7079#issuecomment-2170945774

When applying a pp3 from 5.10, the gradient feather does not get applied. Instead, the default value of 25 is used.

**Steps to reproduce**
1. Apply the attached pp3, or generate one with 5.10 by adding a new Local Adjustments spot with the feather gradient changed (to 77 for example), Color & Light tool added, and gradient strength set to a non-zero number.
2. Observe the feather gradient value in the Color & Light tool. It is 25, which is wrong.

[feather.pp3.txt](https://github.com/user-attachments/files/15948456/feather.pp3.txt)

### LINKED ISSUE #7114: Deadlock when applying a pp3 from 5.10 with Log Encoding in Basic complexity
**Short description**
There is a deadlock when applying a profile generated in version 5.10 with a Selective Editing spot with the Log Encoding tool set to the Basic complexity.

**Steps to reproduce**
1. Open an image in 5.10 with the Neutral profile.
2. Enable Local Adjustments and add a new spot.
3. Add the Log Encoding tool and set the tool complexity to Basic.
4. Save the processing profile.
5. Open an image in dev.
6. Load the processing profile from step 4. The program will deadlock after pressing the Open button.

**Backtrace**
```
#0  0x00007ffff4eac83c in  () at /usr/lib/libc.so.6
#1  0x00007ffff4e5c668 in raise () at /usr/lib/libc.so.6
#2  0x0000555555ef0193 in MyMutex::checkLock(bool) (this=0x555563de7b10, noError=false) at /RawTherapee/rtgui/threadutils.cc:44
#3  0x000055555578b0fb in MyMutex::lock() (this=0x555563de7b10) at /RawTherapee/rtengine/../rtgui/threadutils.h:167
#4  0x0000555556626a48 in rtengine::ImProcCoordinator::beginUpdateParams() (this=0x555563de5630)
    at /RawTherapee/rtengine/improccoordinator.cc:3263
#5  0x0000555555f4e4b1 in ToolPanelCoordinator::panelChanged(rtengine::ProcEvent const&, Glib::ustring const&) (this=0x55555d6f64e0, event=..., descr=...)
    at /RawTherapee/rtgui/toolpanelcoord.cc:1069
#6  0x0000555555c906a0 in LocallabLog::ciecamChanged() (this=0x55555ee32190) at /RawTherapee/rtgui/locallabtools2.cc:6866
#7  0x0000555555d108b0 in sigc::bound_mem_functor0<void, LocallabLog>::operator()() const (this=0x555560d8ab68) at /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h:1991
#8  0x0000555555d10234 in sigc::adaptor_functor<sigc::bound_mem_functor0<void, LocallabLog> >::operator()() const (this=0x555560d8ab60)
    at /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h:256
#9  0x0000555555d0f5ee in sigc::internal::slot_call0<sigc::bound_mem_functor0<void, LocallabLog>, void>::call_it(sigc::internal::slot_rep*) (rep=0x555560d8ab30)
    at /usr/include/sigc++-2.0/sigc++/functors/slot.h:136
#10 0x00007ffff69fc89d in Glib::SignalProxyNormal::slot0_void_callback(_GObject*, void*) () at /usr/lib/libglibmm-2.4.so.1
#11 0x00007ffff6fde6c0 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#12 0x00007ffff700cdbb in  () at /usr/lib/libgobject-2.0.so.0
#13 0x00007ffff6ffda42 in  () at /usr/lib/libgobject-2.0.so.0
#14 0x00007ffff6ffdc77 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#15 0x00007ffff6ffdd34 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#16 0x00007ffff78ec957 in  () at /usr/lib/libgtk-3.so.0
#17 0x00007ffff6ffdb73 in  () at /usr/lib/libgobject-2.0.so.0
#18 0x00007ffff6ffdc77 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#19 0x00007ffff6ffdd34 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#20 0x00007ffff78ec351 in gtk_toggle_button_set_active () at /usr/lib/libgtk-3.so.0
#21 0x0000555555c896c9 in LocallabLog::updateGUIToMode(LocallabTool::modeType) (this=0x55555ee32190, new_type=LocallabTool::Simple)
    at /RawTherapee/rtgui/locallabtools2.cc:6264
#22 0x0000555555c887bc in LocallabLog::read(rtengine::procparams::ProcParams const*, ParamsEdited const*) (this=0x55555ee32190, pp=0x5555642b4cc0, pedited=0x0)
    at /RawTherapee/rtgui/locallabtools2.cc:6140
#23 0x0000555555b2b6a7 in Locallab::read(rtengine::procparams::ProcParams const*, ParamsEdited const*) (this=0x55555ee2eff0, pp=0x5555642b4cc0, pedited=0x0)
    at /RawTherapee/rtgui/locallab.cc:388
#24 0x0000555555f4f379 in ToolPanelCoordinator::profileChange(rtengine::procparams::PartialProfile const*, rtengine::ProcEvent const&, Glib::ustring const&, ParamsEdited const*, bool) (this=0x55555d6f64e0, nparams=0x5555632b7af0, event=..., descr=..., paramsEdited=0x0, fromLastSave=false)
    at /RawTherapee/rtgui/toolpanelcoord.cc:1233
#25 0x0000555555e6f65e in ProfilePanel::changeTo(rtengine::procparams::PartialProfile const*, Glib::ustring) (this=0x555562933570, newpp=0x5555632b7af0, profname=...)
    at /RawTherapee/rtgui/profilepanel.cc:738
#26 0x0000555555e6e2c4 in ProfilePanel::load_clicked(_GdkEventButton*) (this=0x555562933570, event=0x555565553840)
    at /RawTherapee/rtgui/profilepanel.cc:570
#27 0x0000555555e71618 in sigc::bound_mem_functor1<void, ProfilePanel, _GdkEventButton*>::operator()(_GdkEventButton* const&) const
    (this=0x555562b05f48, _A_a1=@0x7fffffffd638: 0x555565553840) at /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h:2066
#28 0x0000555555e7149f in sigc::adaptor_functor<sigc::bound_mem_functor1<void, ProfilePanel, _GdkEventButton*> >::operator()<_GdkEventButton* const&>(_GdkEventButton* const&) const (this=0x555562b05f40, _A_arg1=@0x7fffffffd638: 0x555565553840) at /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h:89
#29 0x0000555555e71191 in sigc::internal::slot_call1<sigc::bound_mem_functor1<void, ProfilePanel, _GdkEventButton*>, void, _GdkEventButton*>::call_it(sigc::internal::slot_rep*, _GdkEventButton* const&) (rep=0x555562b05f10, a_1=@0x7fffffffd638: 0x555565553840) at /usr/include/sigc++-2.0/sigc++/functors/slot.h:170
#30 0x00007ffff67040be in  () at /usr/lib/libgtkmm-3.0.so.1
#31 0x00007ffff768c34d in  () at /usr/lib/libgtk-3.so.0
#32 0x00007ffff6fde6c0 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#33 0x00007ffff700ca36 in  () at /usr/lib/libgobject-2.0.so.0
#34 0x00007ffff6ffd335 in  () at /usr/lib/libgobject-2.0.so.0
#35 0x00007ffff6ffdc77 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#36 0x00007ffff6ffdd34 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#37 0x00007ffff79546e5 in  () at /usr/lib/libgtk-3.so.0
#38 0x00007ffff77ee91b in  () at /usr/lib/libgtk-3.so.0
#39 0x00007ffff77ef447 in gtk_main_do_event () at /usr/lib/libgtk-3.so.0
#40 0x00007ffff753ab87 in  () at /usr/lib/libgdk-3.so.0
#41 0x00007ffff7592d38 in  () at /usr/lib/libgdk-3.so.0
#42 0x00007ffff6ed7f69 in  () at /usr/lib/libglib-2.0.so.0
#43 0x00007ffff6f36327 in  () at /usr/lib/libglib-2.0.so.0
#44 0x00007ffff6ed8b97 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#45 0x00007ffff77ecf6f in gtk_main () at /usr/lib/libgtk-3.so.0
#46 0x0000555555d18c4d in main(int, char**) (argc=1, argv=0x7fffffffe328) at /RawTherapee/rtgui/main.cc:541
```

**PP3**
[log-encoding.pp3.txt](https://github.com/user-attachments/files/15948483/log-encoding.pp3.txt)

### PR DESCRIPTION
**Pull request by Desmis**
#7113 
#7114

### CODE REVIEW

File: rtengine/procparams.cc [hunk 1]
```diff
@@ -9741,6 +9779,15 @@ int ProcParams::load(const Glib::ustring& fname, ParamsEdited* pedited)
                 assignFromKeyfile(keyFile, "Locallab", "Fullimage_" + index_str, spot.fullimage, spotEdited.fullimage);
                 assignFromKeyfile(keyFile, "Locallab", "Repart_" + index_str, spot.repar, spotEdited.repar);
                 assignFromKeyfile(keyFile, "Locallab", "Ciecam_" + index_str, spot.ciecam, spotEdited.ciecam);
```
Comment (Lawrence37) [inline rtengine/procparams.cc]: This can be removed

Comment (Desmis) [reply rtengine/procparams.cc]: Effectively , the line I will remove 9781 .... used twice

**Review by Lawrence37 — APPROVED** [review]
