### PR TITLE
Local adjustments - improve exposure - issue 6274

### LINKED ISSUE #6274: Local Adjustments Exposure compensation acts differently on clipped highlights
**Short description**
Local Adjustments > Dynamic Range & Exposure > Exposure compensation changes the lightness of clipped highlights at a different rate compared to the rest of the photo.

**Steps to reproduce**
1. Open an image with some clipped highlights. Start with the Neutral profile.
2. Enable Local Adjustments and add a full image spot with the Dynamic Range & Exposure tool.
3. Set Scope to 100 to make the tool affect the whole image.
4. In Exposure Tools, set everything to 0 so that nothing is enabled.
5. Drag the Exposure compensation down and observe how the image changes.

**Expected behavior**
Clipped highlights darken at more or less the same rate as the rest of the image.

**Screenshots**
Without adjustment: 
image

Clipped highlights don't darken as quickly as the rest of the image:
image

At this point, the clipped highlights "catch up":
image

Now it darkens quicker than the rest of the image:
image

### PR DESCRIPTION
**Pull request by Desmis**
Fixes #6274

### CODE REVIEW

**Comment by Desmis** [comment]
If nobody objects, I will merge tomorrow 

Jacques

File: rtengine/iplocallab.cc [hunk 1]
```diff
@@ -1648,12 +1648,13 @@ static void calcLocalParams(int sp, int oW, int oH, const LocallabParams& locall
...
-    float proexp = lp.expcomp;
-    if (std::fabs(proexp) < 0.6f) {
-        float interm = std::fabs(proexp) / 0.6f;
+/*    float proexp = lp.expcomp;
+    if (proexp > 0.f && proexp < 0.6f) {
+        float interm = proexp / 0.6f;
         interm = pow(interm, 3.f);
         lp.expcomp = proexp * interm;
     }
+*/
```
Comment (Thanatomanic) [inline rtengine/iplocallab.cc]: Hi @Desmis if this is no longer needed, it can be removed instead of commented. If necessary the git history can restore the code.

Comment (Desmis) [reply rtengine/iplocallab.cc]: OK, I remove...

Jacques
