### PR TITLE
Fix predictor modes 2-7 for lossless JPEG

### LINKED ISSUE #6036: Apple Pro RAW support
Hello, I just found samples of new raw format.
https://www.reddit.com/r/iphone/comments/jyjtt8/proraw_example_files/
Surprisingly, they are in .DNG format(though might have some extra metadata / AI stuff). 
As a comparison with normal DNG, Pro RAW appears 2 times larger per photo.
When I open using rawtherapee, the files look pinkish and with broken debayering.

What are the chances that support of those files will ever be added? 
What is your opinion on the potential of the new format and how is it better than the traditional .DNG standard?

### PR DESCRIPTION
**Pull request by SimonSegerblomRex**
Hi!

Predictor modes 2-7 were broken for `lossless_dng_load_raw` (which is used when "Canon" or "BlackMagic" isn't part of `Make`). I just copy-pasted one line from `dcraw.c` to fix the issue.

After this fix it should be possible to remove lj92 (the lib + `lossless_dnglj92_load_raw`) and always use `lossless_dng_load_raw` without having any special case for `Make`. (At least all the files I could find in #4285 seem to work with `lossless_dng_load_raw` after this fix.)

[predictor-example-files-make-test.zip](https://github.com/Beep6581/RawTherapee/files/6358269/predictor-example-files-make-test.zip)

Resolves #6036

### CODE REVIEW

File: rtengine/dcraw.cc [hunk 1]
```diff
@@ -9078,7 +9078,7 @@ void CLASS adobe_coeff (const char *make, const char *model)
     RT_matrix_from_constant = ThreeValBool::T;
   }
   // -- RT --------------------------------------------------------------------
-  
+
```
Comment (SimonSegerblomRex) [inline rtengine/dcraw.cc:9081]: Sorry about this... (auto-trimming whitespace in my editor...)

File: rtengine/dcraw.cc [hunk 2]
```diff
@@ -923,7 +923,7 @@ ushort * CLASS ljpeg_row (int jrow, struct jhead *jh)
     }
     getbits(-1);
   }
-  FORC3 row[c] = (jh->row + ((jrow & 1) + 1) * (jh->wide*jh->clrs*((jrow+c) & 1)));
```
Comment (SimonSegerblomRex) [inline rtengine/dcraw.cc:926]: This was changed by @heckflosse [here](https://github.com/Beep6581/RawTherapee/commit/f794cf684b18a9c2ca9b4ac350a10fd1ed37fc90#diff-3ca4dd32af70e9e6310586f5b5d92f55fd17859a3bc5bc9eeb4924c637846907L870). It looks like it was supposed to only be an optimization, so I guess it was just a lack of images using predictor modes > 1 back then that introduced the regression.

File: rtengine/dcraw.cc (hunk 1 above)
Comment (Floessie) [reply rtengine/dcraw.cc:9081]: No need to be sorry. This is a valid change. The one adding unnecessary whitespace made a mistake.

**Comment by SimonSegerblomRex** [comment]
I'm not planning to change anything else in this pull request. Once this has been merged I'll create a new pull request for removing lj92.

**Comment by Thanatomanic** [comment]
I've tried your fixes and they work. Apple Pro RAW files also load properly. Great stuff. :+1: for a merge. Let's wait a few more days to see if anybody else wants to comment or try it out.

**Comment by SimonSegerblomRex** [comment]
@Thanatomanic, I think it's safe to merge this, but let me know if you need help verifying the change with a particular set of images.

**Comment by Thanatomanic** [comment]
Thanks again for the PR, looking forward to the next one to further simply processing as you described!
If you do, please feel free to add your name to the `AUTHORS.txt` list
