### PR TITLE
Temperature corellation - crash with some 5D mark III - issue 7162

### LINKED ISSUE #7162: Temperature correlation auto white balance crash
**Short description**
RawTherapee 5.10 asserts/crashes (array out-of-bounds access) when using Auto WB (temperature correlation). I noticed it depends on photo contents.

**Steps to reproduce**
1. Load RAW file (DNG, NEF, ...) with default profile or "Neutral" profile.
2. Select Temperature correlation white balance.
3. Crash (or not - depends on photo contents).

**Expected behavior**
Don't crash - calculate WB properly.

**Additional information**
- Currently I don't know which details on photo causes crash, but it happens on many photos - in general, temperature correlation is unusable.
- Version of RawTherapee: 5.10 and dev:
```
Version: 5.10-370-gcc0e94165
Branch: dev
Commit: cc0e94165
Commit date: 2024-07-28
Compiler: clang 18.1.8
Processor: x86_64
System: Linux
Bit depth: 64 bits
Gtkmm: 3.24.9
Lensfun: 0.3.4.0
libjxl: 0.10.3
Build type: Debug
Build flags: -std=c++11  -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -g -ftree-vectorize
Link flags:   
OpenMP support: OFF
MMAP support: ON
Build OS: Linux 6.10.0-3-MANJARO x86_64
Build date: Wed, 31 Jul 2024 19:39:10 +0000 UTC
Build epoch: 1722454750
Build UUID: 0d89980c-0771-4d5b-9a2d-e60973211d69
```
- Backtrace: [log.txt](https://github.com/user-attachments/files/16446753/log.txt)
- [Sample file which crashes](https://s3.amazonaws.com/lifepixel/RAW-File_Samples/Normal.zip)

### PR DESCRIPTION
**Pull request by Desmis**

### CODE REVIEW

**Comment by Desmis** [comment]
@Lawrence37 
Is it possible to put this PR in 5.11 ?

File: rtengine/rawimagesource.cc [hunk 1]
```diff
@@ -6221,12 +6227,32 @@ void RawImageSource::ItcWB(bool extra, double &tempref, double &greenref, double
...
             #pragma omp parallel for
 #endif
 
             for (int y = 0; y < bfh ; ++y) {
                 for (int x = 0; x < bfw ; ++x) {
+                    if(!std::isnan(redloc[y][x])) {//eliminate wrong values and values not very usable for white balance
+                        clipitc(redloc[y][x]);
+                    } else {
+                        redloc[y][x] = 0.1f;
+                    }
```
Comment (Lawrence37) [inline rtengine/rawimagesource.cc]: Since there is a nan check for every `clipitc`, it is cleaner to put the nan logic in `clipitc` like so:
```c++
constexpr float clipitc(float x)
{
    if (std::isnan(x)) {
        return 0.1f;
    }
    return rtengine::LIM(x, 0.1f, 65534.9f);//White balance Itcwb - limit values 
}
```

Then this piece of code can be
```suggestion
                    redloc[y][x] = clipitc(redloc[y][x]);
```
By the way, the current code does not clip the values because there is no assignment.

File: rtengine/rawimagesource.cc [hunk 2]
```diff
@@ -7441,6 +7467,9 @@ void RawImageSource::getrgbloc(int begx, int begy, int yEn, int xEn, int cx, int
 {
 //    BENCHFUN
     //used by auto WB local to calculate red, green, blue in local region
+    greenloc(0, 0);
+    redloc(0, 0);
+    blueloc(0, 0);
```
Comment (Lawrence37) [inline rtengine/rawimagesource.cc]: This is not necessary because the arrays will always be resized a few lines below.

File: rtengine/rawimagesource.cc [hunk 3]
```diff
@@ -7506,7 +7531,17 @@ void RawImageSource::getrgbloc(int begx, int begy, int yEn, int xEn, int cx, int
...
+            /*    if(std::isnan(red[ii][jj]) || red[ii][jj] <= 0.f || red[ii][jj] > 65535.f) {
+                    red[ii][jj] = 0.1f;
+                }
+                if(std::isnan(green[ii][jj])|| green[ii][jj] <= 0.f || green[ii][jj] > 65535.f) {
+                    green[ii][jj] = 0.1f;
+                }
+                if(std::isnan(blue[ii][jj])|| blue[ii][jj] <= 0.f || blue[ii][jj] > 65535.f) {
+                    blue[ii][jj] = 0.1f;
+                }
+            */
```
Comment (Lawrence37) [inline rtengine/rawimagesource.cc]: Remove these comments

**Comment by Lawrence37** [comment]
@Desmis Yes, this can be included in 5.11.

File: rtengine/rawimagesource.cc (hunk 1 above)
Comment (Desmis) [reply rtengine/rawimagesource.cc]: This code
constexpr float clipitc(float x)
{
    if (std::isnan(x)) {
        return 0.1f;
    }
    return rtengine::LIM(x, 0.1f, 65534.9f);//White balance Itcwb - limit values 
}

 lead to
D:/code/repo-rtdr/rtengine/rawimagesource.cc:68:1: error: body of 'constexpr' function 'constexpr float {anonymous}::clipitc(float)' not a return-statement
   68 | }
      | ^
ninja: build stopped: subcommand failed.

Comment (Lawrence37) [reply rtengine/rawimagesource.cc]: `constexpr` is the problem.

**Review by Lawrence37 — APPROVED** [review]
